[versions]
errorproneCore = "2.50.0"
errorpronePlugin = "5.1.1"
jspecify = "1.0.1"
lombok = "1.18.48"
mybatisFlex = "1.11.8"
nullaway = "0.14.2"
spotless = "8.10.3"
springAi = "2.0.1"
springBoot = "4.1.1"
versionCatalogUpdate = "1.1.1"

[libraries]
# Spring Boot 库（统一由 springBoot 版本驱动）
aspectj-weaver = { module = "org.aspectj:aspectjweaver" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorproneCore" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
# NullAway / JSpecify
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
# Lombok 库
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mybatis-flex-processor = { module = "com.mybatis-flex:mybatis-flex-processor", version.ref = "mybatisFlex" }
# MyBatis Flex 库
mybatis-flex-spring-boot4-starter = { module = "com.mybatis-flex:mybatis-flex-spring-boot4-starter", version.ref = "mybatisFlex" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
postgresql = { module = "org.postgresql:postgresql" }
# Spring AI 库
spring-ai-starter-model-deepseek = { module = "org.springframework.ai:spring-ai-starter-model-deepseek", version.ref = "springAi" }
spring-ai-starter-model-openai = { module = "org.springframework.ai:spring-ai-starter-model-openai", version.ref = "springAi" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springBoot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "springBoot" }
spring-boot-starter-cache-test = { module = "org.springframework.boot:spring-boot-starter-cache-test", version.ref = "springBoot" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway", version.ref = "springBoot" }
spring-boot-starter-flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test", version.ref = "springBoot" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "springBoot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "springBoot" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
