-- DUNGEON 事件类型种子
INSERT
    INTO
        xt_event_type(
            activity_type,
            code,
            name,
            description
        )
    VALUES(
        'DUNGEON',
        'dungeon_area_advance',
        '深入秘境',
        '踏入{{area}}，眼前的景象与外围截然不同，灵气浓度明显提升。'
    ),
    (
        'DUNGEON',
        'dungeon_trap_triggered',
        '触发陷阱',
        '探索中不慎触发了远古禁制，受到 {{damage}} 点伤害，但禁制崩解的瞬间灵气外泄，意外获得了 +{{exp}} 修为。'
    ),
    (
        'DUNGEON',
        'dungeon_treasure_found',
        '发现秘藏',
        '在角落发现了一个隐蔽的暗格，里面放着被人遗忘的宝物。'
    ),
    (
        'DUNGEON',
        'dungeon_lore_discovery',
        '洞悉玄机',
        '墙壁上的古老铭文突然发出微光，你从中领悟到了一些天道至理，获得 +{{exp}} 修为。'
    ),
    (
        'DUNGEON',
        'dungeon_secret_chamber',
        '秘境密室',
        '在探索过程中无意触动了一个被忽视的机关——轰隆声中，一扇隐藏的石门缓缓打开。'
    ),
    (
        'DUNGEON',
        'dungeon_completed',
        '秘境通关',
        '秘境探索圆满完成！你在秘境中历练归来，修为大有精进。'
    ),
    (
        'DUNGEON',
        'dungeon_resonance',
        '灵气共振',
        '秘境中的灵气开始与你的修为产生共振，体内真元汹涌澎湃，获得 +{{exp}} 修为。'
    ),
    (
        'DUNGEON',
        'dungeon_phantom_guard',
        '幻影守卫',
        '一道半透明的虚影拦住了去路——远古大能留下的神识投影，虽然战斗力已不到生前一半但战意犹在。'
    ),
    (
        'DUNGEON',
        'dungeon_qi_spring',
        '灵气泉眼',
        '秘境深处发现一处灵气化液的小泉眼，在泉边稍稍疗伤休息便能快速恢复状态。'
    ),
    (
        'DUNGEON',
        'dungeon_earthen_reflux',
        '地脉回流',
        '秘境的地脉突然暴动，灵气反噬冲击全身，受到 {{damage}} 点伤害——但冲击过后经脉被拓宽了一丝，同时获得 +{{exp}} 修为。'
    ),
    (
        'DUNGEON',
        'dungeon_forgotten_library',
        '遗忘书阁',
        '推开一扇厚重的石门后映入眼帘的是一个布满灰尘的古老书阁，其中还散落着一些前人留下的典籍和灵材。'
    ),
    (
        'DUNGEON',
        'dungeon_elemental_wisp',
        '元素之灵',
        '秘境中游离的元素精华汇聚成了一道发光的灵体，它注视着你，似乎在等待着你去触碰。'
    );
