-- 法决种子数据
INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '金刚体',
        '运转灵气淬炼体魄，永久提升防御10%。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":10}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","defense","beginner"]'
    ),
    (
        '轻身术',
        '灵力灌注双腿，身轻如燕，永久提升身法10%。',
        'PASSIVE',
        '[{"type":"SPEED_BUFF","value":10}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","agi","beginner"]'
    ),
    (
        '蛮牛劲',
        '模仿蛮牛之力运行气血，永久提升力道10%。',
        'PASSIVE',
        '[{"type":"ATTACK_BUFF","value":10}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","str","beginner"]'
    ),
    (
        '静心诀',
        '心如止水，万念归寂，永久提升防御10%。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":10}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","wis","beginner"]'
    ),
    (
        '通明心法',
        '心通大道，慧眼如炬，永久提升防御15%。需要静心诀。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":15}]',
        'NONE',
        0,
        15,
        10,
        '["passive","wis","basic"]'
    ),
    (
        '天人感应',
        '感天悟地，道法自然，永久提升防御20%。需要通明心法。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":20}]',
        'NONE',
        0,
        30,
        30,
        '["passive","wis","intermediate"]'
    ),
    (
        '道心通明',
        '道心坚定，明悟天地至理，永久提升防御30%。需要天人感应。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":30}]',
        'NONE',
        0,
        50,
        50,
        '["passive","wis","advanced","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '破风斩',
        '刀如疾风破空而出，造成150%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.5","target":"single"}]',
        'WEAPON_TYPE',
        'BLADE',
        10,
        NULL,
        1,
        '["blade","damage","beginner"]'
    ),
    (
        '横刀断岳',
        '一记横斩力道万钧，造成220%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.2","target":"single"}]',
        'WEAPON_TYPE',
        'BLADE',
        15,
        10,
        10,
        '["blade","damage","basic"]'
    ),
    (
        '刀光如练',
        '刀势连绵不绝，连续三刀每刀80%攻击的伤害。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.8","value":3,"target":"single"}]',
        'WEAPON_TYPE',
        'BLADE',
        20,
        15,
        20,
        '["blade","multi_hit","intermediate"]'
    ),
    (
        '霸刀诀',
        '霸道无双，无视30%防御且造成180%攻击的伤害。',
        'ACTIVE',
        '[{"type":"ARMOR_BREAK","value":30,"duration":1,"target":"single"},{"type":"DAMAGE","formula":"attack*1.8","target":"single"}]',
        'WEAPON_TYPE',
        'BLADE',
        30,
        25,
        30,
        '["blade","armor_break","advanced"]'
    ),
    (
        '天刀九式',
        '九式合一，刀意纵横。连斩4次（60%攻击），且对血量低于25%的目标造成250%斩杀伤害。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.6","value":4,"target":"single"},{"type":"EXECUTE","formula":"attack*2.5","chance":0.25,"target":"single"}]',
        'WEAPON_TYPE',
        'BLADE',
        60,
        40,
        50,
        '["blade","execute","multi_hit","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '清风剑法',
        '剑如清风拂柳，造成160%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.6","target":"single"}]',
        'WEAPON_TYPE',
        'SWORD',
        10,
        NULL,
        1,
        '["sword","damage","beginner"]'
    ),
    (
        '飞仙剑法',
        '剑气如飞仙凌空，造成210%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.1","target":"single"}]',
        'WEAPON_TYPE',
        'SWORD',
        12,
        10,
        10,
        '["sword","damage","basic"]'
    ),
    (
        '万剑归宗',
        '万剑齐发，对全体敌人造成120%攻击的伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.2","target":"aoe"}]',
        'WEAPON_TYPE',
        'SWORD',
        25,
        20,
        20,
        '["sword","aoe","intermediate"]'
    ),
    (
        '剑心通明',
        '剑心如镜，照破万法。造成180%攻击伤害，同时提升自己15%防御2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.8","target":"single"},{"type":"DEFENSE_BUFF","value":15,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'SWORD',
        35,
        30,
        30,
        '["sword","damage","defense_buff","advanced"]'
    ),
    (
        '青莲剑歌',
        '剑舞如莲华绽放，连续5次每击55%攻击的伤害，附带10%吸血。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.55","value":5,"target":"single"},{"type":"LIFESTEAL","value":10,"target":"single"}]',
        'WEAPON_TYPE',
        'SWORD',
        60,
        45,
        50,
        '["sword","multi_hit","lifesteal","epic"]'
    ),
    (
        '诛仙剑诀',
        '传说可屠仙之剑，造成300%攻击的伤害，且对残血目标（HP<30%）造成450%斩杀伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.0","target":"single"},{"type":"EXECUTE","formula":"attack*4.5","chance":0.3,"target":"single"}]',
        'WEAPON_TYPE',
        'SWORD',
        90,
        60,
        70,
        '["sword","execute","legendary"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '开山斧',
        '势如破竹，一斧劈山，造成200%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.0","target":"single"}]',
        'WEAPON_TYPE',
        'AXE',
        12,
        NULL,
        1,
        '["axe","damage","beginner"]'
    ),
    (
        '旋风斧',
        '旋转横扫，对全体造成130%攻击的伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.3","target":"aoe"}]',
        'WEAPON_TYPE',
        'AXE',
        20,
        10,
        10,
        '["axe","aoe","basic"]'
    ),
    (
        '碎星斧',
        '一斧碎星辰，造成240%攻击伤害并附带40%破甲持续2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.4","target":"single"},{"type":"ARMOR_BREAK","value":40,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'AXE',
        45,
        25,
        25,
        '["axe","armor_break","intermediate"]'
    ),
    (
        '刑天斧法',
        '仿上古刑天舞干戚之势，造成260%伤害并对半血以下敌人造成380%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.6","target":"single"},{"type":"EXECUTE","formula":"attack*3.8","chance":0.5,"target":"single"}]',
        'WEAPON_TYPE',
        'AXE',
        75,
        40,
        45,
        '["axe","execute","advanced"]'
    ),
    (
        '盘古开天',
        '传说盘古开天之力，造成400%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*4.0","target":"single"}]',
        'WEAPON_TYPE',
        'AXE',
        120,
        60,
        65,
        '["axe","damage","legendary"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '穿云枪',
        '枪出如龙穿云而出，造成160%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.6","target":"single"}]',
        'WEAPON_TYPE',
        'SPEAR',
        10,
        NULL,
        1,
        '["spear","damage","beginner"]'
    ),
    (
        '游龙枪法',
        '枪势如游龙盘旋，造成230%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.3","target":"single"}]',
        'WEAPON_TYPE',
        'SPEAR',
        15,
        10,
        10,
        '["spear","damage","basic"]'
    ),
    (
        '寒芒点星',
        '枪尖寒芒如寒星点点，连刺3次每击70%攻击伤害。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.7","value":3,"target":"single"}]',
        'WEAPON_TYPE',
        'SPEAR',
        20,
        15,
        20,
        '["spear","multi_hit","intermediate"]'
    ),
    (
        '回马枪',
        '佯退诱敌，回身致命一枪造成250%伤害，对残血（<30%）造成400%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.5","target":"single"},{"type":"EXECUTE","formula":"attack*4.0","chance":0.3,"target":"single"}]',
        'WEAPON_TYPE',
        'SPEAR',
        40,
        25,
        30,
        '["spear","execute","advanced"]'
    ),
    (
        '霸王枪',
        '横扫千军，对全体造成140%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.4","target":"aoe"}]',
        'WEAPON_TYPE',
        'SPEAR',
        50,
        35,
        45,
        '["spear","aoe","advanced"]'
    ),
    (
        '破阵枪诀',
        '专破阵法，造成280%攻击伤害附带50%破甲持续2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.8","target":"single"},{"type":"ARMOR_BREAK","value":50,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'SPEAR',
        80,
        50,
        60,
        '["spear","armor_break","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '伏魔棍',
        '降妖伏魔基础棍法，造成150%攻击伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.5","target":"single"}]',
        'WEAPON_TYPE',
        'STAFF',
        10,
        NULL,
        1,
        '["staff","damage","beginner"]'
    ),
    (
        '横扫千军',
        '棍扫一大片，对全体造成120%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.2","target":"aoe"}]',
        'WEAPON_TYPE',
        'STAFF',
        20,
        10,
        10,
        '["staff","aoe","basic"]'
    ),
    (
        '定海神针',
        '重击如定海神针镇压，造成200%攻击伤害并有40%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.0","target":"single"},{"type":"STUN","chance":0.4,"duration":1,"target":"single"}]',
        'WEAPON_TYPE',
        'STAFF',
        40,
        20,
        25,
        '["staff","stun","intermediate"]'
    ),
    (
        '翻天棍法',
        '一套翻天覆地之棍，对全体造成150%伤害附带30%破甲。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.5","target":"aoe"},{"type":"ARMOR_BREAK","value":30,"duration":2,"target":"aoe"}]',
        'WEAPON_TYPE',
        'STAFF',
        60,
        35,
        40,
        '["staff","aoe","armor_break","advanced"]'
    ),
    (
        '菩提棍意',
        '以菩提之心运棍，造成230%攻击伤害并吸取25%生命。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.3","target":"single"},{"type":"LIFESTEAL","value":25,"target":"single"}]',
        'WEAPON_TYPE',
        'STAFF',
        70,
        45,
        55,
        '["staff","lifesteal","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '穿杨箭',
        '百步穿杨，精准一射造成170%攻击伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.7","target":"single"}]',
        'WEAPON_TYPE',
        'BOW',
        8,
        NULL,
        1,
        '["bow","damage","beginner"]'
    ),
    (
        '连珠箭',
        '连珠三箭，每箭65%攻击伤害。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.65","value":3,"target":"single"}]',
        'WEAPON_TYPE',
        'BOW',
        12,
        10,
        10,
        '["bow","multi_hit","basic"]'
    ),
    (
        '穿心箭',
        '一箭穿心，造成210%攻击伤害附带35%破甲。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.1","target":"single"},{"type":"ARMOR_BREAK","value":35,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'BOW',
        25,
        20,
        20,
        '["bow","armor_break","intermediate"]'
    ),
    (
        '流星箭雨',
        '箭如流星雨般落下，对全体造成125%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.25","target":"aoe"}]',
        'WEAPON_TYPE',
        'BOW',
        45,
        30,
        35,
        '["bow","aoe","advanced"]'
    ),
    (
        '追魂箭',
        '一箭追魂索命，造成250%伤害并对低血（<25%）敌人造成430%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.5","target":"single"},{"type":"EXECUTE","formula":"attack*4.3","chance":0.25,"target":"single"}]',
        'WEAPON_TYPE',
        'BOW',
        75,
        40,
        50,
        '["bow","execute","epic"]'
    ),
    (
        '射日弓',
        '后羿射日之术，造成350%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.5","target":"single"}]',
        'WEAPON_TYPE',
        'BOW',
        120,
        60,
        70,
        '["bow","damage","legendary"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '灵蛇鞭',
        '鞭如灵蛇吐信，造成140%攻击伤害并减速20%持续2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.4","target":"single"},{"type":"SLOW","value":20,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'WHIP',
        12,
        NULL,
        5,
        '["whip","damage","slow","beginner"]'
    ),
    (
        '缚龙索',
        '鞭化缚龙之索，50%概率使目标眩晕1回合。',
        'ACTIVE',
        '[{"type":"STUN","chance":0.5,"duration":1,"target":"single"}]',
        'WEAPON_TYPE',
        'WHIP',
        35,
        15,
        20,
        '["whip","stun","control","intermediate"]'
    ),
    (
        '天魔鞭法',
        '天魔乱舞之鞭，对全体造成120%伤害附带持续伤害（攻击15%×3回合）。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.2","target":"aoe"},{"type":"DOT","value":15,"duration":3,"target":"aoe"}]',
        'WEAPON_TYPE',
        'WHIP',
        60,
        35,
        40,
        '["whip","aoe","dot","advanced"]'
    ),
    (
        '修罗鞭',
        '修罗道的狂鞭，造成220%攻击伤害并吸取20%生命。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.2","target":"single"},{"type":"LIFESTEAL","value":20,"target":"single"}]',
        'WEAPON_TYPE',
        'WHIP',
        70,
        45,
        55,
        '["whip","lifesteal","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '方天画戟',
        '基础戟法，造成180%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.8","target":"single"}]',
        'WEAPON_TYPE',
        'HALBERD',
        12,
        NULL,
        10,
        '["halberd","damage","beginner"]'
    ),
    (
        '戟破苍穹',
        '一戟破空，造成230%伤害附带40%破甲。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.3","target":"single"},{"type":"ARMOR_BREAK","value":40,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'HALBERD',
        45,
        25,
        30,
        '["halberd","armor_break","intermediate"]'
    ),
    (
        '裂天戟',
        '一戟分裂天地，对全体造成140%伤害，对残血（<25%）造成380%斩杀。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.4","target":"aoe"},{"type":"EXECUTE","formula":"attack*3.8","chance":0.25,"target":"aoe"}]',
        'WEAPON_TYPE',
        'HALBERD',
        90,
        50,
        50,
        '["halberd","aoe","execute","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '震地锤',
        '一锤震地，造成190%攻击伤害，40%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.9","target":"single"},{"type":"STUN","chance":0.4,"duration":1,"target":"single"}]',
        'WEAPON_TYPE',
        'HAMMER',
        15,
        NULL,
        10,
        '["hammer","damage","stun","beginner"]'
    ),
    (
        '轰天锤',
        '一锤轰天，对全体造成130%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.3","target":"aoe"}]',
        'WEAPON_TYPE',
        'HAMMER',
        45,
        25,
        30,
        '["hammer","aoe","intermediate"]'
    ),
    (
        '碎虚锤',
        '一锤碎虚空，造成300%伤害附带60%破甲和对残血（<25%）450%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.0","target":"single"},{"type":"ARMOR_BREAK","value":60,"duration":2,"target":"single"},{"type":"EXECUTE","formula":"attack*4.5","chance":0.25,"target":"single"}]',
        'WEAPON_TYPE',
        'HAMMER',
        100,
        60,
        55,
        '["hammer","armor_break","execute","legendary"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '影刺',
        '从暗影中发起的一击，造成180%攻击伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.8","target":"single"}]',
        'WEAPON_TYPE',
        'DAGGER',
        8,
        NULL,
        5,
        '["dagger","damage","beginner"]'
    ),
    (
        '暗影杀',
        '暗影中的致命一击，对血量低于40%的目标造成300%斩杀伤害。',
        'ACTIVE',
        '[{"type":"EXECUTE","formula":"attack*3.0","chance":0.4,"target":"single"}]',
        'WEAPON_TYPE',
        'DAGGER',
        30,
        15,
        15,
        '["dagger","execute","basic"]'
    ),
    (
        '千幻刺杀',
        '幻化千影连续刺杀，连击4次每击55%攻击伤害，附带持续毒伤（10%×3回合）。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.55","value":4,"target":"single"},{"type":"DOT","value":10,"duration":3,"target":"single"}]',
        'WEAPON_TYPE',
        'DAGGER',
        50,
        30,
        30,
        '["dagger","multi_hit","dot","advanced"]'
    ),
    (
        '瞬狱杀',
        '瞬移至敌后发动致命一击，造成260%伤害附带眩晕（50%）和对残血（<20%）480%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.6","target":"single"},{"type":"STUN","chance":0.5,"duration":1,"target":"single"},{"type":"EXECUTE","formula":"attack*4.8","chance":0.2,"target":"single"}]',
        'WEAPON_TYPE',
        'DAGGER',
        80,
        50,
        50,
        '["dagger","execute","stun","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '清风拂柳',
        '扇引清风，治疗自身悟性×80%+100的生命值。',
        'ACTIVE',
        '[{"type":"HEAL","formula":"wis*0.8+100","value":80,"target":"single"}]',
        'WEAPON_TYPE',
        'FAN',
        15,
        15,
        10,
        '["fan","heal","beginner"]'
    ),
    (
        '霓裳扇舞',
        '扇舞如霓裳，对全体造成110%攻击伤害并减速15%持续2回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.1","target":"aoe"},{"type":"SLOW","value":15,"duration":2,"target":"aoe"}]',
        'WEAPON_TYPE',
        'FAN',
        40,
        25,
        25,
        '["fan","aoe","slow","intermediate"]'
    ),
    (
        '天罡扇',
        '天罡之力入扇，造成200%攻击伤害并提升自己攻击20%持续3回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.0","target":"single"},{"type":"ATTACK_BUFF","value":20,"duration":3,"target":"single"}]',
        'WEAPON_TYPE',
        'FAN',
        55,
        35,
        40,
        '["fan","attack_buff","advanced"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '拂尘净心',
        '拂尘轻扫净心田，治疗悟性×70%+80血量并提升速度15%持续2回合。',
        'ACTIVE',
        '[{"type":"HEAL","formula":"wis*0.7+80","value":70,"target":"single"},{"type":"SPEED_BUFF","value":15,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'FLYWHISK',
        20,
        15,
        10,
        '["flywhisk","heal","speed_buff","beginner"]'
    ),
    (
        '三千烦恼',
        '尘丝化三千，对全体造成120%攻击伤害并50%概率沉默2回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.2","target":"aoe"},{"type":"SILENCE","chance":0.5,"duration":2,"target":"aoe"}]',
        'WEAPON_TYPE',
        'FLYWHISK',
        45,
        30,
        25,
        '["flywhisk","aoe","silence","intermediate"]'
    ),
    (
        '太虚拂尘',
        '太虚之境化拂尘，造成210%攻击伤害并提升防御25%持续3回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.1","target":"single"},{"type":"DEFENSE_BUFF","value":25,"duration":3,"target":"single"}]',
        'WEAPON_TYPE',
        'FLYWHISK',
        60,
        40,
        40,
        '["flywhisk","defense_buff","advanced"]'
    )，(
        '金刚圈',
        '金刚圈脱手而出，造成170%攻击伤害，40%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.7","target":"single"},{"type":"STUN","chance":0.4,"duration":1,"target":"single"}]',
        'WEAPON_TYPE',
        'RING',
        12,
        NULL,
        15,
        '["ring","damage","stun","beginner"]'
    ),
    (
        '乾坤圈',
        '乾坤一圈，对全体造成115%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.15","target":"aoe"}]',
        'WEAPON_TYPE',
        'RING',
        40,
        25,
        30,
        '["ring","aoe","intermediate"]'
    ),
    (
        '日月双环',
        '日月齐出，连环双击每击90%攻击伤害，第二次必暴击（180%伤害）。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*0.9","value":2,"target":"single"}]',
        'WEAPON_TYPE',
        'RING',
        50,
        35,
        45,
        '["ring","multi_hit","advanced"]'
    ),(
        '伏魔钟',
        '钟声震荡伏妖邪，造成160%攻击伤害并50%概率沉默2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.6","target":"single"},{"type":"SILENCE","chance":0.5,"duration":2,"target":"single"}]',
        'WEAPON_TYPE',
        'BELL',
        15,
        10,
        15,
        '["bell","damage","silence","beginner"]'
    ),
    (
        '镇魂钟声',
        '钟声镇魂，对全体造成125%攻击伤害并40%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.25","target":"aoe"},{"type":"STUN","chance":0.4,"duration":1,"target":"aoe"}]',
        'WEAPON_TYPE',
        'BELL',
        45,
        30,
        30,
        '["bell","aoe","stun","intermediate"]'
    ),
    (
        '混沌钟',
        '混沌初开的钟声回荡，造成280%攻击伤害并对残血（<30%）造成420%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.8","target":"single"},{"type":"EXECUTE","formula":"attack*4.2","chance":0.3,"target":"single"}]',
        'WEAPON_TYPE',
        'BELL',
        90,
        50,
        50,
        '["bell","execute","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '兵锋诀',
        '运灵力强化兵刃，提升攻击15%持续3回合。',
        'ACTIVE',
        '[{"type":"ATTACK_BUFF","value":15,"duration":3,"target":"single"}]',
        'WEAPON_CATEGORY',
        'MELEE',
        30,
        10,
        5,
        '["melee","attack_buff","beginner"]'
    ),
    (
        '刀剑无双',
        '刀剑齐出，对全体造成140%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.4","target":"aoe"}]',
        'WEAPON_CATEGORY',
        'MELEE',
        50,
        25,
        25,
        '["melee","aoe","intermediate"]'
    ),
    (
        '兵主杀伐',
        '杀伐之气纵横，造成240%伤害并吸取20%生命。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.4","target":"single"},{"type":"LIFESTEAL","value":20,"target":"single"}]',
        'WEAPON_CATEGORY',
        'MELEE',
        80,
        40,
        45,
        '["melee","lifesteal","advanced"]'
    ),
    (
        '长驱直入',
        '以长兵之势直捣黄龙，造成200%攻击伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.0","target":"single"}]',
        'WEAPON_CATEGORY',
        'POLEARM',
        20,
        NULL,
        5,
        '["polearm","damage","beginner"]'
    ),
    (
        '横扫八荒',
        '长兵横扫八荒，对全体造成130%攻击伤害。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.3","target":"aoe"}]',
        'WEAPON_CATEGORY',
        'POLEARM',
        50,
        25,
        25,
        '["polearm","aoe","intermediate"]'
    ),
    (
        '枪出如龙',
        '全力一击如苍龙出海，对残血（<30%）造成400%斩杀。',
        'ACTIVE',
        '[{"type":"EXECUTE","formula":"attack*4.0","chance":0.3,"target":"single"}]',
        'WEAPON_CATEGORY',
        'POLEARM',
        90,
        45,
        45,
        '["polearm","execute","advanced"]'
    ),
    (
        '鹰眼术',
        '凝神聚目，提升远程攻击20%持续3回合。',
        'ACTIVE',
        '[{"type":"ATTACK_BUFF","value":20,"duration":3,"target":"single"}]',
        'WEAPON_CATEGORY',
        'RANGED',
        25,
        10,
        10,
        '["ranged","attack_buff","beginner"]'
    ),
    (
        '百步穿杨',
        '远距离精准一击，造成240%攻击伤害附带30%破甲。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.4","target":"single"},{"type":"ARMOR_BREAK","value":30,"duration":2,"target":"single"}]',
        'WEAPON_CATEGORY',
        'RANGED',
        60,
        30,
        30,
        '["ranged","armor_break","intermediate"]'
    ),
    (
        '后羿射日',
        '远古箭神之力，造成380%攻击的伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.8","target":"single"}]',
        'WEAPON_CATEGORY',
        'RANGED',
        120,
        55,
        55,
        '["ranged","damage","legendary"]'
    ),
    (
        '奇门遁甲',
        '奇兵八门变化，造成170%攻击伤害并减速20%持续2回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.7","target":"single"},{"type":"SLOW","value":20,"duration":2,"target":"single"}]',
        'WEAPON_CATEGORY',
        'EXOTIC',
        20,
        10,
        10,
        '["exotic","slow","beginner"]'
    ),
    (
        '八门金锁',
        '八门金锁阵展开，对全体造成120%伤害并50%概率沉默2回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.2","target":"aoe"},{"type":"SILENCE","chance":0.5,"duration":2,"target":"aoe"}]',
        'WEAPON_CATEGORY',
        'EXOTIC',
        55,
        30,
        30,
        '["exotic","aoe","silence","intermediate"]'
    ),
    (
        '逆乱阴阳',
        '逆转阴阳，造成250%伤害，对残血（<25%）造成430%斩杀。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.5","target":"single"},{"type":"EXECUTE","formula":"attack*4.3","chance":0.25,"target":"single"}]',
        'WEAPON_CATEGORY',
        'EXOTIC',
        90,
        50,
        50,
        '["exotic","execute","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            binding_value,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '金灵剑气',
        '以金行之力化剑气，造成180%攻击伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.8","element":"metal","target":"single"}]',
        'ELEMENT',
        'metal',
        10,
        10,
        10,
        '["metal","damage","beginner"]'
    ),
    (
        '金钟罩',
        '以金行灵力罩体，提升防御25%持续3回合。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":25,"duration":3,"target":"single"}]',
        'ELEMENT',
        'metal',
        30,
        15,
        20,
        '["metal","defense_buff","basic"]'
    ),
    (
        '太白斩魔',
        '太白金星之力斩妖除魔，造成260%攻击伤害附带40%破甲。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*2.6","element":"metal","target":"single"},{"type":"ARMOR_BREAK","value":40,"duration":2,"target":"single"}]',
        'ELEMENT',
        'metal',
        60,
        35,
        40,
        '["metal","armor_break","advanced"]'
    ),
    (
        '青木诀',
        '引木行生机滋养自身，治疗悟性×90%+120的生命值。',
        'ACTIVE',
        '[{"type":"HEAL","formula":"wis*0.9+120","value":90,"target":"single"}]',
        'ELEMENT',
        'wood',
        12,
        10,
        10,
        '["wood","heal","beginner"]'
    ),
    (
        '荆棘缠绕',
        '荆棘藤蔓缠绕敌身，造成120%攻击伤害附带持续伤害（12%×3回合）和减速20%。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.2","element":"wood","target":"single"},{"type":"DOT","value":12,"duration":3,"target":"single"},{"type":"SLOW","value":20,"duration":3,"target":"single"}]',
        'ELEMENT',
        'wood',
        35,
        20,
        20,
        '["wood","dot","slow","basic"]'
    ),
    (
        '万木逢春',
        '百花齐放万木逢春，治疗全体悟性×60%+100的生命值。',
        'ACTIVE',
        '[{"type":"HEAL","formula":"wis*0.6+100","value":60,"target":"aoe"}]',
        'ELEMENT',
        'wood',
        60,
        40,
        40,
        '["wood","heal","aoe","advanced"]'
    ),
    (
        '寒冰掌',
        '寒气凝于掌心，造成170%攻击伤害附带冰冻（30%概率冻结1回合）。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.7","element":"ice","target":"single"},{"type":"FREEZE","chance":0.3,"duration":1,"target":"single"}]',
        'ELEMENT',
        'water',
        12,
        10,
        10,
        '["water","ice","freeze","beginner"]'
    ),
    (
        '水镜术',
        '水镜映万物反弹三成伤害，提升防御20%持续3回合。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":20,"duration":3,"target":"single"}]',
        'ELEMENT',
        'water',
        30,
        15,
        20,
        '["water","defense_buff","basic"]'
    ),
    (
        '冰封万里',
        '万里冰封，对全体造成130%攻击伤害并40%概率冰冻1回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.3","element":"ice","target":"aoe"},{"type":"FREEZE","chance":0.4,"duration":1,"target":"aoe"}]',
        'ELEMENT',
        'water',
        70,
        45,
        40,
        '["water","ice","aoe","freeze","advanced"]'
    ),
    (
        '烈火掌',
        '聚火气于掌，造成190%攻击的火焰伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*1.9","element":"fire","target":"single"}]',
        'ELEMENT',
        'fire',
        10,
        NULL,
        10,
        '["fire","damage","beginner"]'
    ),
    (
        '焚天诀',
        '焚天之火燎原势，对全体造成135%攻击伤害附带持续灼烧（15%×3回合）。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.35","element":"fire","target":"aoe"},{"type":"DOT","value":15,"duration":3,"target":"aoe"}]',
        'ELEMENT',
        'fire',
        55,
        30,
        25,
        '["fire","aoe","dot","intermediate"]'
    ),
    (
        '三昧真火',
        '三昧真火焚万物，造成320%攻击伤害并附带50%破甲。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.2","element":"fire","target":"single"},{"type":"ARMOR_BREAK","value":50,"duration":2,"target":"single"}]',
        'ELEMENT',
        'fire',
        90,
        55,
        60,
        '["fire","armor_break","epic"]'
    ),
    (
        '厚土盾',
        '以大地之力凝聚盾甲，提升防御30%持续3回合。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":30,"duration":3,"target":"single"}]',
        'ELEMENT',
        'earth',
        30,
        10,
        10,
        '["earth","defense_buff","beginner"]'
    ),
    (
        '地动术',
        '震动大地，对全体造成125%攻击伤害并减速25%持续2回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.25","element":"earth","target":"aoe"},{"type":"SLOW","value":25,"duration":2,"target":"aoe"}]',
        'ELEMENT',
        'earth',
        45,
        25,
        25,
        '["earth","aoe","slow","intermediate"]'
    ),
    (
        '泰山压顶',
        '泰山之力从天而降，造成300%攻击伤害并50%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.0","element":"earth","target":"single"},{"type":"STUN","chance":0.5,"duration":1,"target":"single"}]',
        'ELEMENT',
        'earth',
        80,
        50,
        55,
        '["earth","stun","epic"]'
    );

INSERT
    INTO
        xt_skill(
            name,
            description,
            skill_type,
            effects,
            binding_type,
            cooldown_seconds,
            require_wis,
            level_requirement,
            tags
        )
    VALUES(
        '轩辕剑法',
        '黄帝轩辕氏所创战剑之法，造成350%攻击伤害并对全体波及150%伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*3.5","target":"single"},{"type":"AOE_DAMAGE","formula":"attack*1.5","target":"aoe"}]',
        'NONE',
        120,
        70,
        80,
        '["sword","legendary","damage","aoe"]'
    ),
    (
        '霸下真身',
        '龙九子之首霸下的不灭真身奥义，永久提升防御40%。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":40}]',
        'NONE',
        0,
        80,
        90,
        '["passive","con","legendary"]'
    ),
    (
        '蟠桃仙术',
        '西王母蟠桃仙根所化疗愈术，治疗全体悟性×150%+500生命值。',
        'ACTIVE',
        '[{"type":"HEAL","formula":"wis*1.5+500","value":150,"target":"aoe"}]',
        'NONE',
        180,
        80,
        85,
        '["heal","legendary","aoe"]'
    ),
    (
        '莲华涅槃',
        '濒死之际绽莲华涅槃重生，免疫死亡一次并回复50%生命值（被动触发）。',
        'PASSIVE',
        '[{"type":"HEAL","value":50,"target":"single"},{"type":"DEFENSE_BUFF","value":50,"duration":1,"target":"single"}]',
        'NONE',
        600,
        90,
        95,
        '["passive","survival","legendary"]'
    ),
    (
        '一气化三清',
        '道祖神通，分身化三，对单一目标造成3次各180%攻击的伤害。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","formula":"attack*1.8","value":3,"target":"single"}]',
        'NONE',
        120,
        80,
        90,
        '["multi_hit","legendary","dao"]'
    ),
    (
        '天罡北斗阵',
        '天罡北斗七星之力灌注，提升全体攻击25%和防御25%持续4回合。',
        'ACTIVE',
        '[{"type":"ATTACK_BUFF","value":25,"duration":4,"target":"aoe"},{"type":"DEFENSE_BUFF","value":25,"duration":4,"target":"aoe"}]',
        'NONE',
        150,
        70,
        75,
        '["aoe","buff","legendary"]'
    ),
    (
        '袖里乾坤',
        '五庄观镇元大仙秘术，禁锢敌方全体1回合（沉默+减速50%）。',
        'ACTIVE',
        '[{"type":"SILENCE","chance":1.0,"duration":1,"target":"aoe"},{"type":"SLOW","value":50,"duration":1,"target":"aoe"}]',
        'NONE',
        180,
        85,
        85,
        '["control","legendary","aoe"]'
    ),
    (
        '五雷正法',
        '召唤五方神雷，对全体造成200%攻击的雷电伤害，并有25%概率眩晕1回合。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*2.0","element":"lightning","target":"aoe"},{"type":"STUN","chance":0.25,"duration":1,"target":"aoe"}]',
        'NONE',
        100,
        60,
        70,
        '["thunder","aoe","stun","epic"]'
    ),
    (
        '血魔真经',
        '燃烧10%最大生命值，换取攻击提升40%持续5回合，此间吸血30%。',
        'ACTIVE',
        '[{"type":"ATTACK_BUFF","value":40,"duration":5,"target":"single"},{"type":"LIFESTEAL","value":30,"duration":5,"target":"single"}]',
        'NONE',
        90,
        55,
        60,
        '["lifesteal","attack_buff","evil","epic"]'
    ),
    (
        '太乙遁甲',
        '以先天演算预判敌方攻势，闪避下一回合所有攻击并使自身速度提升30%持续3回合。',
        'ACTIVE',
        '[{"type":"SPEED_BUFF","value":30,"duration":3,"target":"single"},{"type":"DEFENSE_BUFF","value":30,"duration":1,"target":"single"}]',
        'NONE',
        75,
        50,
        50,
        '["speed_buff","defense","dodge","epic"]'
    ),
    (
        '九天魔音',
        '九天之外降临的魔音贯脑，对全体造成150%伤害并附带50%概率眩晕+50%概率沉默。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","formula":"attack*1.5","target":"aoe"},{"type":"STUN","chance":0.5,"duration":1,"target":"aoe"},{"type":"SILENCE","chance":0.5,"duration":2,"target":"aoe"}]',
        'NONE',
        110,
        65,
        65,
        '["aoe","control","evil","epic"]'
    ),
    (
        '养剑术',
        '养一口先天剑意在丹田，每回合自动累积一层剑意（最多10层），释放时造成总剑意×50%攻击的真实伤害。',
        'ACTIVE',
        '[{"type":"DAMAGE","formula":"attack*stackCount*0.5","maxStacks":10,"target":"single"}]',
        'NONE',
        30,
        40,
        45,
        '["sword","stack","unique"]'
    ),
    (
        '混元功',
        '混元一中包容万象，将受到的溢出治疗转化为等额护盾持续2回合。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":15,"duration":2,"target":"single"}]',
        'NONE',
        0,
        45,
        40,
        '["passive","heal","shield","unique"]'
    ),
    (
        '踏波行',
        '轻功水上漂的进阶版——水上起飞，战斗中速度提升20%且无视减速效果。',
        'PASSIVE',
        '[{"type":"SPEED_BUFF","value":20,"target":"single"}]',
        'NONE',
        0,
        30,
        25,
        '["passive","speed","mobility"]'
    ),
    (
        '逆转丹行',
        '逆转丹道药性，将下一次治疗效果翻倍。',
        'ACTIVE',
        '[{"type":"HEAL","value":100,"target":"single"}]',
        'NONE',
        60,
        35,
        35,
        '["heal","boost","unique"]'
    ),
    (
        '偷天换日',
        '偷天之力加持，敌方下一次释放法决效果减半。',
        'ACTIVE',
        '[{"type":"SILENCE","chance":0.8,"duration":1,"target":"single"}]',
        'NONE',
        150,
        75,
        80,
        '["control","legendary"]'
    ),
    -- ==================== 冰元素 ====================
    (
        '霜刃',
        '凝聚寒霜于利刃之上，斩出冰寒一击。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":150},{"type":"SLOW","value":20,"duration":2}]',
        'ELEMENT',
        10,
        NULL,
        1,
        '["ice","damage","beginner"]'
    ),
    (
        '冰锥术',
        '凝聚冰锥刺穿敌人，有概率冻结目标。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":200},{"type":"FREEZE","value":30,"duration":1}]',
        'ELEMENT',
        20,
        10,
        10,
        '["ice","damage","freeze","basic"]'
    ),
    (
        '玄冰甲',
        '凝聚玄冰护体，攻击者受冰寒反噬。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":25,"duration":3},{"type":"REFLECT","value":10,"duration":3}]',
        'ELEMENT',
        30,
        15,
        20,
        '["ice","defense_buff","reflect","basic"]'
    ),
    (
        '千里冰封',
        '大范围冰封之术，冻结方圆百丈。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","value":140},{"type":"FREEZE","value":35,"duration":1}]',
        'ELEMENT',
        70,
        45,
        40,
        '["ice","aoe","freeze","advanced"]'
    ),
    (
        '绝对零度',
        '极寒之术，将温度降至极限。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":280},{"type":"FREEZE","value":50,"duration":2}]',
        'ELEMENT',
        90,
        55,
        60,
        '["ice","freeze","epic"]'
    ),
    -- ==================== 雷元素 ====================
    (
        '引雷诀',
        '引天雷入体，化为己用。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":160},{"type":"STUN","value":15,"duration":1}]',
        'ELEMENT',
        10,
        NULL,
        1,
        '["thunder","damage","beginner"]'
    ),
    (
        '雷甲',
        '以雷电护体，攻击者受雷击反噬。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":20,"duration":3},{"type":"COUNTER","value":20,"duration":3}]',
        'ELEMENT',
        30,
        15,
        20,
        '["thunder","defense_buff","basic"]'
    ),
    (
        '连环雷',
        '连续雷击，每击皆引天雷。',
        'ACTIVE',
        '[{"type":"MULTI_HIT","value":70,"hits":3}]',
        'ELEMENT',
        40,
        20,
        20,
        '["thunder","multi_hit","intermediate"]'
    ),
    (
        '天雷破',
        '天雷贯体而下，威力惊人。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":250},{"type":"STUN","value":40,"duration":1}]',
        'ELEMENT',
        60,
        35,
        40,
        '["thunder","stun","advanced"]'
    ),
    (
        '九天神雷',
        '引九天之雷降世，雷罚万物。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","value":180},{"type":"STUN","value":30,"duration":1}]',
        'ELEMENT',
        100,
        60,
        70,
        '["thunder","aoe","stun","epic"]'
    ),
    -- ==================== 风元素 ====================
    (
        '风刃',
        '以灵力凝成风刃，快如闪电。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":140},{"type":"SPEED_BUFF","value":10,"duration":2}]',
        'ELEMENT',
        10,
        NULL,
        1,
        '["wind","damage","beginner"]'
    ),
    (
        '旋风盾',
        '凝聚旋风化为护盾，可偏转攻击。',
        'ACTIVE',
        '[{"type":"DEFENSE_BUFF","value":20,"duration":3},{"type":"DODGE","value":20,"duration":3}]',
        'ELEMENT',
        30,
        15,
        20,
        '["wind","defense_buff","dodge","basic"]'
    ),
    (
        '风卷残云',
        '狂风席卷，摧枯拉朽。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","value":120},{"type":"SLOW","value":20,"duration":2}]',
        'ELEMENT',
        40,
        20,
        20,
        '["wind","aoe","slow","intermediate"]'
    ),
    (
        '裂风斩',
        '以风为刃，切割万物。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":240},{"type":"ARMOR_BREAK","value":30,"duration":2}]',
        'ELEMENT',
        60,
        35,
        40,
        '["wind","armor_break","advanced"]'
    ),
    (
        '天风灭世',
        '天风降世，万物寂灭。',
        'ACTIVE',
        '[{"type":"AOE_DAMAGE","value":170},{"type":"SILENCE","value":40,"duration":2}]',
        'ELEMENT',
        100,
        60,
        70,
        '["wind","aoe","silence","epic"]'
    ),
    -- ==================== 低阶通用技能 ====================
    (
        '吐纳术',
        '吐故纳新，增益灵力护体。',
        'PASSIVE',
        '[{"type":"RESIST_BUFF","value":5}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","defense","beginner"]'
    ),
    (
        '灵力护体',
        '灵力充盈于体魄，根基更厚。',
        'PASSIVE',
        '[{"type":"HP_BUFF","value":8}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","hp","beginner"]'
    ),
    (
        '聚灵诀',
        '汇聚天地灵气为己用。',
        'PASSIVE',
        '[{"type":"ATTACK_BUFF","value":5}]',
        'NONE',
        0,
        NULL,
        1,
        '["passive","attack","beginner"]'
    ),
    (
        '疾风步',
        '身法如风，来去无踪。',
        'PASSIVE',
        '[{"type":"SPEED_BUFF","value":12},{"type":"DODGE","value":5}]',
        'NONE',
        0,
        10,
        10,
        '["passive","speed","dodge","basic"]'
    ),
    (
        '铁布衫',
        '横练功夫，皮如铁布。',
        'PASSIVE',
        '[{"type":"DEFENSE_BUFF","value":15}]',
        'NONE',
        0,
        NULL,
        10,
        '["passive","defense","basic"]'
    ),
    (
        '破甲劲',
        '内劲穿透护甲，直伤本体。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":180},{"type":"ARMOR_BREAK","value":25,"duration":2}]',
        'NONE',
        20,
        10,
        10,
        '["damage","armor_break","basic"]'
    ),
    (
        '回春术',
        '灵力化为生机，治愈伤势。',
        'ACTIVE',
        '[{"type":"HEAL","value":60,"scale":"WIS"},{"type":"CLEANSE","value":1}]',
        'NONE',
        20,
        15,
        10,
        '["heal","cleanse","basic"]'
    ),
    (
        '定身术',
        '以灵力定住敌人，使其无法行动。',
        'ACTIVE',
        '[{"type":"STUN","value":40,"duration":1},{"type":"SLOW","value":20,"duration":2}]',
        'NONE',
        40,
        25,
        20,
        '["control","stun","intermediate"]'
    ),
    (
        '吸星大法',
        '吸取敌人灵力为己用。',
        'ACTIVE',
        '[{"type":"DAMAGE","value":160},{"type":"LIFESTEAL","value":15}]',
        'NONE',
        30,
        20,
        20,
        '["damage","lifesteal","intermediate"]'
    ),
    (
        '金蝉脱壳',
        '濒死之际脱壳保命。',
        'PASSIVE',
        '[{"type":"SURVIVE_LETHAL","value":20}]',
        'NONE',
        0,
        20,
        20,
        '["passive","survival","intermediate"]'
    );
