-- =====================================================================
-- 旅行事件种子数据 — "低频高风险高回报"
-- 设计规则：
--   1. 每个 ActivityEvent.params.effects 必须覆盖 EventType.description 中所有 {{key}} 模板变量
--   2. 空效果事件必须补齐效果（叙事暗示了 reward 就不能什么都不给）
--   3. 高风险：部分事件带 TAKE_DAMAGE_PERCENT（5-15% 最大生命）
--   4. 高回报：使用 ADD_EXP_PERCENT（2-8% 升级修为）代替固定 ADD_EXP
--   5. TravelCompleter.rollSubEvents 基础触发概率 0.30，命运修正后 0.21~0.39
-- =====================================================================

INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        1,
        'travel_ambush_beast',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    30
                )
            )
        )
    ),
    (
        'TRAVEL',
        1,
        'travel_broken_cart',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        )
                    ),
                    'chance',
                    0.3
                )
            )
        )
    ),
    (
        'TRAVEL',
        1,
        'travel_friendly_merchant',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        2,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_FLAT',
                    'amount',
                    15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    20
                )
            )
        )
    ),
    (
        'TRAVEL',
        2,
        'travel_injured_cultivator',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    50
                )
            )
        )
    ),
    (
        'TRAVEL',
        3,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        4,
        'travel_spring_of_spirit',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 100}]}'
    ),
    (
        'TRAVEL',
        4,
        'travel_broken_cart',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '兽骨'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        5,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        6,
        'travel_friendly_merchant',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    30
                )
            )
        )
    ),
    (
        'TRAVEL',
        6,
        'travel_wandering_elder',
        'NUMERIC',
        5,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":20}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        7,
        'travel_treasure_map',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        )
                    ),
                    'chance',
                    0.6
                )
            )
        )
    ),
    (
        'TRAVEL',
        8,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.02
                )
            )
        )
    ),
    (
        'TRAVEL',
        10,
        'travel_bandit_roadblock',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    50
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    40
                )
            )
        )
    ),
    (
        'TRAVEL',
        11,
        'travel_friendly_merchant',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        )
                    ),
                    'chance',
                    0.6
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    60
                )
            )
        )
    ),
    (
        'TRAVEL',
        11,
        'travel_wandering_elder',
        'NUMERIC',
        6,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":45}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        17,
        'travel_strange_fog',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        24,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 500}]}'
    ),
    (
        'TRAVEL',
        27,
        'travel_fallen_star',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        30,
        'travel_fallen_star',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        35,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '魂玉碎片'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        39,
        'travel_fallen_star',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        42,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    -- =================================================================
    -- 以下为之前缺失旅行事件的地图新增
    -- =================================================================
    (
        'TRAVEL',
        12,
        'travel_ambush_beast',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        12,
        'travel_spring_of_spirit',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 300}]}'
    ),
    (
        'TRAVEL',
        13,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    100
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    60
                )
            )
        )
    ),
    (
        'TRAVEL',
        13,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    3
                )
            )
        )
    ),
    (
        'TRAVEL',
        15,
        'travel_injured_cultivator',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    100
                )
            )
        )
    ),
    (
        'TRAVEL',
        15,
        'travel_friendly_merchant',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        )
                    ),
                    'chance',
                    0.5
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    50
                )
            )
        )
    ),
    (
        'TRAVEL',
        16,
        'travel_rainstorm',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        16,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '朱砂'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'TRAVEL',
        19,
        'travel_bandit_roadblock',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    150
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        19,
        'travel_strange_fog',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        20,
        'travel_wandering_elder',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        20,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 500}]}'
    ),
    (
        'TRAVEL',
        22,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                )
            )
        )
    ),
    (
        'TRAVEL',
        22,
        'travel_broken_cart',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        23,
        'travel_spring_of_spirit',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    600
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.02
                )
            )
        )
    ),
    (
        'TRAVEL',
        23,
        'travel_friendly_merchant',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        25,
        'travel_strange_fog',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    150
                )
            )
        )
    ),
    (
        'TRAVEL',
        25,
        'travel_ambush_beast',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        32,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        32,
        'travel_fallen_star',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    2
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        34,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    ),
    (
        'TRAVEL',
        36,
        'travel_ambush_beast',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        36,
        'travel_bandit_roadblock',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    300
                )
            )
        )
    ),
    (
        'TRAVEL',
        37,
        'travel_strange_fog',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        37,
        'travel_rainstorm',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                )
            )
        )
    ),
    (
        'TRAVEL',
        38,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    ),
    (
        'TRAVEL',
        38,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 1500}]}'
    ),
    (
        'TRAVEL',
        43,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'TRAVEL',
        43,
        'travel_treasure_map',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    2
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    );

-- =================================================================
-- 隐藏事件
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        14,
        'travel_wandering_elder',
        'NUMERIC',
        8,
        TRUE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":50}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '大悟道丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        28,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        TRUE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '九转金莲'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_bandit_roadblock',
        'NUMERIC',
        10,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '刑天斧法'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    );

-- =================================================================
-- 新增旅行事件（第二批）
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        4,
        'travel_hermit_cave',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP_PERCENT", "percent": 0.04}]}'
    ),
    (
        'TRAVEL',
        4,
        'travel_ancient_monument',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄晶'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        7,
        'travel_wildfire',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        9,
        'travel_mysterious_peddler',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        9,
        'travel_beast_migration',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    100
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    100
                )
            )
        )
    ),
    (
        'TRAVEL',
        14,
        'travel_mysterious_voice',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '魂玉碎片'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        18,
        'travel_flood_path',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    120
                )
            )
        )
    ),
    (
        'TRAVEL',
        18,
        'travel_mysterious_peddler',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        21,
        'travel_hermit_cave',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝'
                    ),
                    'count',
                    3
                )
            )
        )
    ),
    (
        'TRAVEL',
        21,
        'travel_beast_migration',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    250
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        24,
        'travel_cloud_pavilion',
        'NUMERIC',
        6,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":40}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.07
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        28,
        'travel_ancient_monument',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    300
                )
            )
        )
    ),
    (
        'TRAVEL',
        31,
        'travel_mysterious_voice',
        'NUMERIC',
        8,
        FALSE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '魂玉碎片'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_beast_migration',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        40,
        'travel_wildfire',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    300
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        41,
        'travel_cloud_pavilion',
        'NUMERIC',
        8,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":60}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '天外陨铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.6
                )
            )
        )
    ),
    (
        'TRAVEL',
        44,
        'travel_hermit_cave',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.07
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'TRAVEL',
        44,
        'travel_beast_migration',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    600
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    );

-- =================================================================
-- 旅行商人 — CHOICE 交互选择事件（玉简/锻造图/兽卵/装备）
-- 设计：低概率触发（weight 3-5），JS生成随机价格叙事文本
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        6,
        'travel_curious_merchant',
        'CHOICE',
        4,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一本泛黄的剑道玉简——商人咧嘴一笑：「万剑归宗，我只卖八百灵石，你小子要是识货就下手吧。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '万剑归宗玉简'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚温热的卵——商人压低声音：「火蟾卵，三百年难得一见，今天只要五百灵石，错过就没了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '火蟾卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你摇摇头转身要走，商人叹了口气：「眼力不错但不贪心——送你点路上的盘缠吧。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            50
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_EXP',
                            'amount',
                            30
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        14,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一张质地奇异的锻造图纸——商人递过来给你细看：「青冥剑图，我花了半辈子才到手，你给一千灵石它就是你的了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '青冥剑图'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一颗隐隐透出白光的卵——商人环顾四周后才说：「雪狐卵——要不是缺灵石我绝对不会卖，只要三百灵石。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '雪狐卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '「不买不卖，交个朋友。」商人见你无意购买，反而笑了笑，随手扔了一小袋灵石过来。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            100
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        22,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一柄剑身青黑如冥渊的长剑——商人眯着眼：「纯钧剑，刚从古洞里挖出来的真品，一千五百灵石你拿去，这可是剑修的好伙伴。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'CREATE_EQUIPMENT',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_equipment_template
                                WHERE
                                    name = '纯钧剑'
                            )
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚碧光流转的蛇卵——商人小心翼翼托在掌心：「碧鳞蛇卵，别看现在还小，孵出来以后比你还能打。给你算六百灵石好了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '碧鳞蛇卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你拱手婉拒，商人若有所思地看了你一眼：「也罢，能抵住诱惑的人不多了——拿着。」递来一枚丹药。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '聚灵丹'
                            ),
                            'count',
                            2
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            80
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一枚散发着圣道气息的玉简——商人神色凝重：「轩辕剑法——这是我从上古战场里九死一生带出来的。非有缘人不卖，你我相逢便是有缘——三千灵石，不二价。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '轩辕剑法玉简'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚青色光华流转的巨卵——商人用颤抖的手掀开绒布：「青鸾卵——我走遍九州只找到这么一枚。本来要价一万灵石，但我看你骨骼精奇，收你三千就好。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '青鸾卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你抱拳拒绝。商人反倒欣慰地点点头：「懂得拒绝是修道的上乘境界——这份心性就当赔你的眼缘了。」抛来数块灵石和一颗天元丹。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            300
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '天元丹'
                            ),
                            'count',
                            1
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        43,
        'travel_curious_merchant',
        'CHOICE',
        2,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一把刀身刻满龙雀纹的宝刀——商人抚刀叹道：「龙雀刀，传家之宝，今日迫不得已才卖的。五千灵石，一分也不能少。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'CREATE_EQUIPMENT',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_equipment_template
                                WHERE
                                    name = '龙雀刀'
                            )
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚金光璀璨的雕卵——商人压低声音：「金翼雕卵——整个大陆不超过三枚。我本来不卖，但我欠你师父一个人情。收你两千灵石意思一下。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '金翼雕卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你摇头推辞。商人收起货物，临别前深深看你一眼：「能见宝物而不动心，你将来造化不小——这颗太乙金丹，算我和你交个朋友。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '太乙金丹'
                            ),
                            'count',
                            1
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            500
                        )
                    )
                )
            )
        )
    );

-- 旅行商人事件变体扩展 (CHOICE事件)
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            params
        )
    VALUES(
        'TRAVEL',
        6,
        'travel_curious_merchant',
        'CHOICE',
        4,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '云来村口的茶摊旁，一位老翁摆着地摊——「灵猫卵，温顺通灵，五百灵石拿去。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '灵猫卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 500)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '老翁压低声音从袖中摸出一枚泛着霞光的卵——「九色鹿卵，祥瑞之兆，两千五百灵石，有缘者得。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 2500)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你摇摇头，老翁也不恼：「不买也罢，这壶茶算老朽请你的。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_SPIRIT_STONES', 'amount', 50),
                        jsonb_build_object('type', 'ADD_EXP', 'amount', 20)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        14,
        'travel_curious_merchant',
        'CHOICE',
        5,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '灵虚洞天入口处，一位鹤发童颜的老者席地而坐——「灵鲤卵，水中精灵，六百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '灵鲤卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 600)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '老者从怀中取出一枚雪白的卵，表面隐约有祥云纹路——「白泽幼卵，通晓万物，两千灵石，你我有缘。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '白泽幼卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 2000)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你拱手谢绝，老者微微颔首：「心性不错，这枚丹药送你。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '小聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        9,
        'travel_curious_merchant',
        'CHOICE',
        3,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '青云门遗址的断壁残垣间，一位蒙面人拦住去路——「别怕，我卖灵蛇卵的，五百灵石一条。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '灵蛇卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 500)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '蒙面人从背后摸出一枚幽蓝的卵——「玄水蛇卵，此地水脉所孕，一千八百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '玄水蛇卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 1800)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你警惕后退，蒙面人叹了口气：「罢了，这枚丹药算赔罪。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '培元丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        17,
        'travel_curious_merchant',
        'CHOICE',
        4,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '归墟海外围的礁石上，一位渔夫打扮的汉子招手——「雪兔卵，冰原灵兽，七百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '雪兔卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 700)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '汉子从船舱里取出一枚泛着寒气的卵——「霜狼卵，此兽凶猛但忠主，两千二百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '霜狼卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 2200)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你摆手拒绝，汉子也不纠缠：「那这壶酒算我请你的，暖暖身子。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        11,
        'travel_curious_merchant',
        'CHOICE',
        5,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '飞云城集市角落，一位红衣女子守着几枚火红的卵——「火鼠卵，五百灵石，城里独一份。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '火鼠卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 500)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '女子神秘一笑取出一枚金红相间的卵——「火鸦卵，天生灵禽，一千六百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '火鸦卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 1600)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你婉言谢绝，女子掩嘴轻笑：「不碍事，这枚丹药送你路上用。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '小聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        20,
        'travel_curious_merchant',
        'CHOICE',
        3,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '天机阁外山的山道上，一位书生模样的青年背着竹篓——「云鸽卵，六百灵石，此鸟最善传书。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '云鸽卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 600)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '青年从篓中取出一枚七彩流光的卵——「青鸾卵，祥瑞灵禽，两千灵石，天机阁弟子特供。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '青鸾卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 2000)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你摇头走过，青年拱手：「无妨，这枚丹药权当结个善缘。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '培元丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        13,
        'travel_curious_merchant',
        'CHOICE',
        4,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '幽冥谷深处的暗河边，一位黑衣人蹲在石上——「水蛙卵，七百灵石，此兽通水性。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '水蛙卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 700)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '黑衣人从暗河中捞出一枚幽绿的卵——「碧水蛟卵，此地水脉精华所凝，两千二百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '碧水蛟卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 2200)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你心生警惕转身便走，黑衣人也不追赶：「胆小鬼，这丹药拿去压压惊。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        8,
        'travel_curious_merchant',
        'CHOICE',
        5,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '迷雾沼泽的木桥上，一位采药女背着药篓——「风蝶卵，五百灵石，此蝶能辨风向。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '风蝶卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 500)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '采药女从篓中取出一枚紫电缠绕的卵——「雷雀卵，沼泽雷暴所生，一千六百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '雷雀卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 1600)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你摆手谢绝，采药女莞尔：「那这株草药送你，沼泽里用得上。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '小聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        15,
        'travel_curious_merchant',
        'CHOICE',
        3,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '天剑宗遗址的剑碑前，一位铸剑师模样的大汉——「金蝉卵，六百灵石，此虫能食金铁。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '金蝉卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 600)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '大汉从怀中取出一枚金光闪闪的卵——「金蛇卵，剑气所养，一千八百灵石。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '金蛇卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 1800)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你摇头离去，大汉喊住你：「等等！这丹药你拿着，剑修不易。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '培元丹'), 'count', 1)
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        19,
        'travel_curious_merchant',
        'CHOICE',
        4,
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key', 'A',
                    'text', '魔王岭的山脚茶棚里，一位胖商人满面堆笑——「福鼠卵，五百灵石，此鼠能招财。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '福鼠卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 500)
                    )
                ),
                jsonb_build_object(
                    'key', 'B',
                    'text', '胖商人神秘兮兮地取出一枚泛着银光的卵——「瑞兔卵，月华所孕，一千五百灵石，买了保平安。」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '瑞兔卵'), 'count', 1),
                        jsonb_build_object('type', 'TAKE_SPIRIT_STONES', 'amount', 1500)
                    )
                ),
                jsonb_build_object(
                    'key', 'C',
                    'text', '你笑着摇头，胖商人也不介意：「不买没关系，这茶算我请客！」',
                    'effects', jsonb_build_array(
                        jsonb_build_object('type', 'ADD_ITEM', 'template_id', (SELECT id FROM xt_item_template WHERE name = '聚灵丹'), 'count', 1)
                    )
                )
            )
        )
    );
