-- 灵兽繁育配方种子数据
INSERT INTO xt_breeding_recipe(required_tags, result_template_id, weight) VALUES
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火鼠卵'),
  100),
('["fire", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '炎雀卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛙卵'),
  100),
('["fire", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '火蚁卵'),
  100),
('["beast", "earth", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩蜥卵'),
  60),
('["fire", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '烛蝎卵'),
  100),
('["fire", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '火鸦卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '暖貂卵'),
  100),
('["fire", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '焰蝶卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火蟾卵'),
  100),
('["beast", "fire", "fur"]',
  (SELECT id FROM xt_item_template WHERE name = '炎狼卵'),
  60),
('["beast", "fire", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鬃马卵'),
  60),
('["fire", "insect", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '火蝎卵'),
  60),
('["fire", "flying", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '烈焰雀卵'),
  60),
('["beast", "earth", "fire", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩龟卵'),
  30),
('["fire", "flying", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '毕方卵'),
  60),
('["beast", "fire", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '祸斗卵'),
  60),
('["beast", "fire", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '九尾火狐卵'),
  60),
('["auspicious", "fire", "flying", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '朱雀卵'),
  30),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鲤卵'),
  100),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛙卵'),
  100),
('["beast", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '溪蟹卵'),
  60),
('["beast", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '河蚌卵'),
  60),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛇精卵'),
  100),
('["beast", "poison", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '泽蛙卵'),
  60),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雨燕卵'),
  100),
('["beast", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '溪龟卵'),
  60),
('["spirit", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水母妖卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '碧水蛟卵'),
  100),
('["beast", "defense", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '灵龟卵'),
  60),
('["beast", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '潮蟹卵'),
  60),
('["heal", "insect", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水灵蝶卵'),
  60),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄水蛇卵'),
  60),
('["beast", "defense", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '千年老龟卵'),
  30),
('["beast", "defense", "earth", "shell", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄武龟卵'),
  10),
('["beast", "dragon", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '虎蛟卵'),
  60),
('["beast", "myth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '摸鱼鲲卵'),
  60),
('["beast", "ice", "myth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冥卵'),
  10),
('["heal", "plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝妖卵'),
  60),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '藤蛇卵'),
  100),
('["heal", "plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '花精卵'),
  60),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '木灵蝶卵'),
  100),
('["flying", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠鸟卵'),
  100),
('["beast", "water", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '荷蛙卵'),
  60),
('["spirit", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '柳灵卵'),
  100),
('["beast", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '松鼠灵卵'),
  100),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '竹节虫卵'),
  100),
('["plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '花妖卵'),
  60),
('["control", "serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '古藤蛇卵'),
  60),
('["heal", "insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠玉蜂卵'),
  60),
('["beast", "strength", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '灵木猿卵'),
  60),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青藤蟒卵'),
  100),
('["insect", "poison", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '碧萝蛛卵'),
  60),
('["auspicious", "beast", "heal", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'),
  30),
('["defense", "plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '万年树妖卵'),
  60),
('["myth", "plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '建木灵卵'),
  60),
('["auspicious", "dragon", "water", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青龙卵'),
  30),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蚁卵'),
  100),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝉卵'),
  100),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蝎卵'),
  60),
('["beast", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蜥卵'),
  100),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝶卵'),
  100),
('["defense", "insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁甲虫卵'),
  60),
('["metal", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蛇卵'),
  100),
('["flying", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼雀卵'),
  100),
('["beast", "metal", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '金龟卵'),
  60),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铁背蜈蚣卵'),
  60),
('["auspicious", "flying", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金翎鹤卵'),
  60),
('["beast", "metal", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '铜角犀卵'),
  60),
('["flying", "metal", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼蝠卵'),
  60),
('["beast", "metal", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '金丝猴卵'),
  60),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁爪鹰卵'),
  60),
('["auspicious", "beast", "metal", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '白虎卵'),
  30),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '金翼雕卵'),
  60),
('["beast", "defense", "metal", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '铁骨熊卵'),
  30),
('["beast", "celestial", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '太白金星兽卵'),
  30),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '土拨鼠卵'),
  100),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛙卵'),
  100),
('["beast", "earth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '泥鳅精卵'),
  60),
('["earth", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '地蚁卵'),
  100),
('["earth", "insect", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝎卵'),
  60),
('["control", "earth", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '土蜘蛛卵'),
  60),
('["earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛇精卵'),
  100),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '泥龟卵'),
  60),
('["earth", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝶卵'),
  100),
('["beast", "defense", "earth", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '岩甲犀卵'),
  30),
('["beast", "earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '地龙蚓卵'),
  60),
('["defense", "earth", "spirit"]',
  (SELECT id FROM xt_item_template WHERE name = '石魔像卵'),
  60),
('["beast", "defense", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '厚土蟾卵'),
  60),
('["beast", "earth", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '山魈卵'),
  60),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '穿山甲灵卵'),
  60),
('["auspicious", "beast", "earth", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '麒麟卵'),
  30),
('["defense", "earth", "spirit", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '石巨人卵'),
  30),
('["defense", "earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '玄岩蟒卵'),
  60),
('["auspicious", "dragon", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '黄龙卵'),
  30),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪兔卵'),
  100),
('["ice", "insect", "silk"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蚕卵'),
  60),
('["ice", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛾卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪鼠卵'),
  100),
('["ice", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蝶卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛙卵'),
  100),
('["flying", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪雀卵'),
  100),
('["ice", "insect", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '冰甲虫卵'),
  60),
('["ice", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛇卵'),
  100),
('["beast", "ice", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '雪狐卵'),
  60),
('["auspicious", "beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '冰角鹿卵'),
  60),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜狼卵'),
  60),
('["auspicious", "flying", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '冰鹤卵'),
  60),
('["beast", "ice", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '寒蟾卵'),
  60),
('["beast", "ice", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '雪猿卵'),
  60),
('["beast", "ice", "serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '黑水玄蛇卵'),
  30),
('["flying", "ice", "phoenix"]',
  (SELECT id FROM xt_item_template WHERE name = '冰凤卵'),
  60),
('["defense", "ice", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰巨蟒卵'),
  60),
('["dragon", "ice", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰螭龙卵'),
  30),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蛙卵'),
  100),
('["insect", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蝶卵'),
  100),
('["beast", "thunder", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '电鳗卵'),
  60),
('["flying", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷雀卵'),
  100),
('["beast", "speed", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风鼠卵'),
  60),
('["insect", "poison", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电蝎卵'),
  60),
('["insect", "silk", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蚕卵'),
  60),
('["serpent", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蛇卵'),
  100),
('["insect", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电萤卵'),
  100),
('["flying", "predator", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹰卵'),
  60),
('["auspicious", "flying", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风灵鹤卵'),
  60),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电狼卵'),
  60),
('["beast", "scale", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蜥蜴卵'),
  60),
('["flying", "serpent", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风翼蛇卵'),
  60),
('["beast", "strength", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷猿卵'),
  60),
('["beast", "myth", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '夔牛卵'),
  60),
('["beast", "myth", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '飞廉卵'),
  60),
('["flying", "predator", "thunder", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹏卵'),
  30),
('["dragon", "flying", "myth", "thunder", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '应龙卵'),
  10),
('["beast", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '灵雀卵'),
  100),
('["flying", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风燕卵'),
  100),
('["beast", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '云鸽卵'),
  100),
('["flying", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹦卵'),
  100),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹭卵'),
  100),
('["fire", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '烟鹤卵'),
  100),
('["beast", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '霞鸠卵'),
  100),
('["earth", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '岚鸦卵'),
  100),
('["beast", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '霓莺卵'),
  100),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁羽鹰卵'),
  60),
('["flying", "support"]',
  (SELECT id FROM xt_item_template WHERE name = '比翼鸟卵'),
  100),
('["flying", "myth", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '云鹏卵'),
  60),
('["auspicious", "flying", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹤卵'),
  60),
('["flying", "speed", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风隼卵'),
  60),
('["flying", "stealth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹰卵'),
  60),
('["auspicious", "flying", "phoenix"]',
  (SELECT id FROM xt_item_template WHERE name = '青鸾卵'),
  60),
('["flying", "myth", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '天马卵'),
  60),
('["flying", "metal", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '大鹏金翅鸟卵'),
  30),
('["beast", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '灵蛇卵'),
  100),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青蛇卵'),
  100),
('["fire", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛇卵'),
  100),
('["beast", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '花蟒卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛟卵'),
  100),
('["earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '草蛇卵'),
  100),
('["earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛟卵'),
  100),
('["metal", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '金蛇卵'),
  100),
('["serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '墨蛇卵'),
  100),
('["poison", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '碧鳞蛇卵'),
  100),
('["dragon", "serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '蛟蜥卵'),
  60),
('["serpent", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '蟒精卵'),
  100),
('["fire", "scale", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鳞蛇卵'),
  60),
('["dragon", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '角蛇卵'),
  100),
('["dragon", "serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠蛟卵'),
  60),
('["beast", "dragon", "sword"]',
  (SELECT id FROM xt_item_template WHERE name = '螭龙卵'),
  60),
('["dragon", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '内卷蛟卵'),
  60),
('["dragon", "fire", "light", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '烛龙卵'),
  10),
('["auspicious", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '福鼠卵'),
  100),
('["auspicious", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞兔卵'),
  100),
('["auspicious", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '祥鸽卵'),
  100),
('["auspicious", "beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '吉蛙卵'),
  60),
('["auspicious", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '灵猫卵'),
  100),
('["auspicious", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '喜蛛卵'),
  100),
('["auspicious", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '福蝶卵'),
  100),
('["auspicious", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞蛇卵'),
  100),
('["auspicious", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '懒猴卵'),
  60),
('["auspicious", "beast", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '玉兔卵'),
  60),
('["auspicious", "beast", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '乘黄卵'),
  60),
('["auspicious", "beast", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽幼卵'),
  60),
('["auspicious", "flying", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞鹤卵'),
  60),
('["auspicious", "beast", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '吉祥鹿卵'),
  60),
('["auspicious", "heal", "plant"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝仙卵'),
  60),
('["auspicious", "beast", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽卵'),
  60),
('["auspicious", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '躺平貘卵'),
  30),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '瘟鼠卵'),
  100),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '毒蛙卵'),
  60),
('["evil", "insect", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '邪蛛卵'),
  60),
('["evil", "insect"]',
  (SELECT id FROM xt_item_template WHERE name = '魔蛾卵'),
  60),
('["evil", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '煞蛇卵'),
  100),
('["evil", "insect", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '鬼萤卵'),
  60),
('["evil", "insect", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '厄蝎卵'),
  60),
('["evil", "flying", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '怨蝠卵'),
  60),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '瘴蟾卵'),
  60),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇幼卵'),
  60),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮幼卵'),
  60),
('["beast", "chaos", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌幼卵'),
  60),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌幼卵'),
  60),
('["beast", "evil", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '猰貐卵'),
  60),
('["chaos", "evil", "spirit"]',
  (SELECT id FROM xt_item_template WHERE name = '浑敦卵'),
  60),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇卵'),
  60),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮卵'),
  60),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌卵'),
  60),
('["beast", "chaos", "earth", "evil", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌卵'),
  10);
