-- 灵兽繁育配方种子数据
INSERT INTO xt_breeding_recipe(required_tags, result_template_id, weight, description) VALUES
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火鼠卵'),
  100,
  'beast+fire繁育，产出火鼠'),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '炎雀卵'),
  100,
  'flying+fire繁育，产出炎雀'),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛙卵'),
  100,
  'beast+fire繁育，产出赤蛙'),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火蚁卵'),
  100,
  'insect+fire繁育，产出火蚁'),
('["beast", "fire", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩蜥卵'),
  100,
  'beast+fire+earth繁育，产出熔岩蜥'),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '烛蝎卵'),
  100,
  'insect+fire繁育，产出烛蝎'),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火鸦卵'),
  100,
  'flying+fire繁育，产出火鸦'),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '暖貂卵'),
  100,
  'beast+fire繁育，产出暖貂'),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '焰蝶卵'),
  100,
  'insect+fire繁育，产出焰蝶'),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火蟾卵'),
  100,
  'beast+fire繁育，产出火蟾'),
('["beast", "fire", "fur"]',
  (SELECT id FROM xt_item_template WHERE name = '炎狼卵'),
  100,
  'beast+fire+fur繁育，产出炎狼'),
('["beast", "fire", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鬃马卵'),
  100,
  'beast+fire+speed繁育，产出赤鬃马'),
('["insect", "fire", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '火蝎卵'),
  100,
  'insect+fire+poison繁育，产出火蝎'),
('["flying", "fire", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '烈焰雀卵'),
  100,
  'flying+fire+wind繁育，产出烈焰雀'),
('["beast", "fire", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩龟卵'),
  100,
  'beast+fire+earth+shell繁育，产出熔岩龟'),
('["flying", "fire", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '毕方卵'),
  100,
  'flying+fire+wood繁育，产出毕方'),
('["beast", "fire", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '祸斗卵'),
  100,
  'beast+fire+thunder繁育，产出祸斗'),
('["beast", "fire", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '九尾火狐卵'),
  100,
  'beast+fire+wisdom繁育，产出九尾火狐'),
('["flying", "fire", "wood", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '朱雀卵'),
  100,
  'flying+fire+wood+auspicious繁育，产出朱雀'),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鲤卵'),
  100,
  'beast+water繁育，产出灵鲤'),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛙卵'),
  100,
  'beast+water繁育，产出水蛙'),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '溪蟹卵'),
  100,
  'beast+water+shell繁育，产出溪蟹'),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '河蚌卵'),
  100,
  'beast+water+shell繁育，产出河蚌'),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛇精卵'),
  100,
  'serpent+water繁育，产出水蛇精'),
('["beast", "water", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '泽蛙卵'),
  100,
  'beast+water+poison繁育，产出泽蛙'),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雨燕卵'),
  100,
  'flying+water繁育，产出雨燕'),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '溪龟卵'),
  100,
  'beast+water+shell繁育，产出溪龟'),
('["spirit", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水母妖卵'),
  100,
  'spirit+water繁育，产出水母妖'),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '碧水蛟卵'),
  100,
  'serpent+water繁育，产出碧水蛟'),
('["beast", "water", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '灵龟卵'),
  100,
  'beast+water+defense繁育，产出灵龟'),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '潮蟹卵'),
  100,
  'beast+water+shell繁育，产出潮蟹'),
('["insect", "water", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '水灵蝶卵'),
  100,
  'insect+water+heal繁育，产出水灵蝶'),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄水蛇卵'),
  100,
  'serpent+water繁育，产出玄水蛇'),
('["beast", "water", "defense", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '千年老龟卵'),
  100,
  'beast+water+defense+shell繁育，产出千年老龟'),
('["beast", "water", "earth", "defense", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '玄武龟卵'),
  100,
  'beast+water+earth+defense+shell繁育，产出玄武龟'),
('["beast", "water", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '虎蛟卵'),
  100,
  'beast+water+dragon繁育，产出虎蛟'),
('["beast", "water", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '摸鱼鲲卵'),
  100,
  'beast+water+myth繁育，产出摸鱼鲲'),
('["beast", "water", "ice", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冥卵'),
  100,
  'beast+water+ice+myth繁育，产出玄冥'),
('["plant", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝妖卵'),
  100,
  'plant+wood+heal繁育，产出灵芝妖'),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '藤蛇卵'),
  100,
  'serpent+wood繁育，产出藤蛇'),
('["plant", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '花精卵'),
  100,
  'plant+wood+heal繁育，产出花精'),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '木灵蝶卵'),
  100,
  'insect+wood繁育，产出木灵蝶'),
('["flying", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠鸟卵'),
  100,
  'flying+wood繁育，产出翠鸟'),
('["beast", "wood", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '荷蛙卵'),
  100,
  'beast+wood+water繁育，产出荷蛙'),
('["spirit", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '柳灵卵'),
  100,
  'spirit+wood繁育，产出柳灵'),
('["beast", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '松鼠灵卵'),
  100,
  'beast+wood繁育，产出松鼠灵'),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '竹节虫卵'),
  100,
  'insect+wood繁育，产出竹节虫'),
('["plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '花妖卵'),
  100,
  'plant+wood繁育，产出花妖'),
('["serpent", "wood", "control"]',
  (SELECT id FROM xt_item_template WHERE name = '古藤蛇卵'),
  100,
  'serpent+wood+control繁育，产出古藤蛇'),
('["insect", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '翠玉蜂卵'),
  100,
  'insect+wood+heal繁育，产出翠玉蜂'),
('["beast", "wood", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '灵木猿卵'),
  100,
  'beast+wood+strength繁育，产出灵木猿'),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青藤蟒卵'),
  100,
  'serpent+wood繁育，产出青藤蟒'),
('["insect", "wood", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '碧萝蛛卵'),
  100,
  'insect+wood+poison繁育，产出碧萝蛛'),
('["beast", "wood", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'),
  100,
  'beast+wood+auspicious+heal繁育，产出九色鹿'),
('["plant", "wood", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '万年树妖卵'),
  100,
  'plant+wood+defense繁育，产出万年树妖'),
('["plant", "wood", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '建木灵卵'),
  100,
  'plant+wood+myth繁育，产出建木灵'),
('["dragon", "wood", "water", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '青龙卵'),
  100,
  'dragon+wood+water+auspicious繁育，产出青龙'),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蚁卵'),
  100,
  'insect+metal繁育，产出铁蚁'),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝉卵'),
  100,
  'insect+metal繁育，产出金蝉'),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蝎卵'),
  100,
  'insect+metal+poison繁育，产出铜蝎'),
('["beast", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蜥卵'),
  100,
  'beast+metal繁育，产出铁蜥'),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝶卵'),
  100,
  'insect+metal繁育，产出金蝶'),
('["insect", "metal", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '铁甲虫卵'),
  100,
  'insect+metal+defense繁育，产出铁甲虫'),
('["serpent", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蛇卵'),
  100,
  'serpent+metal繁育，产出铜蛇'),
('["flying", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼雀卵'),
  100,
  'flying+metal繁育，产出铁翼雀'),
('["beast", "metal", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '金龟卵'),
  100,
  'beast+metal+shell繁育，产出金龟'),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铁背蜈蚣卵'),
  100,
  'insect+metal+poison繁育，产出铁背蜈蚣'),
('["flying", "metal", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '金翎鹤卵'),
  100,
  'flying+metal+auspicious繁育，产出金翎鹤'),
('["beast", "metal", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '铜角犀卵'),
  100,
  'beast+metal+strength繁育，产出铜角犀'),
('["flying", "metal", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼蝠卵'),
  100,
  'flying+metal+stealth繁育，产出铁翼蝠'),
('["beast", "metal", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '金丝猴卵'),
  100,
  'beast+metal+wisdom繁育，产出金丝猴'),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁爪鹰卵'),
  100,
  'flying+metal+predator繁育，产出铁爪鹰'),
('["beast", "metal", "wind", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白虎卵'),
  100,
  'beast+metal+wind+auspicious繁育，产出白虎'),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '金翼雕卵'),
  100,
  'flying+metal+predator繁育，产出金翼雕'),
('["beast", "metal", "strength", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '铁骨熊卵'),
  100,
  'beast+metal+strength+defense繁育，产出铁骨熊'),
('["beast", "metal", "celestial"]',
  (SELECT id FROM xt_item_template WHERE name = '太白金星兽卵'),
  100,
  'beast+metal+celestial繁育，产出太白金星兽'),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '土拨鼠卵'),
  100,
  'beast+earth繁育，产出土拨鼠'),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛙卵'),
  100,
  'beast+earth繁育，产出石蛙'),
('["beast", "earth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '泥鳅精卵'),
  100,
  'beast+earth+water繁育，产出泥鳅精'),
('["insect", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '地蚁卵'),
  100,
  'insect+earth繁育，产出地蚁'),
('["insect", "earth", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝎卵'),
  100,
  'insect+earth+poison繁育，产出石蝎'),
('["insect", "earth", "control"]',
  (SELECT id FROM xt_item_template WHERE name = '土蜘蛛卵'),
  100,
  'insect+earth+control繁育，产出土蜘蛛'),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛇精卵'),
  100,
  'serpent+earth繁育，产出石蛇精'),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '泥龟卵'),
  100,
  'beast+earth+shell繁育，产出泥龟'),
('["insect", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝶卵'),
  100,
  'insect+earth繁育，产出石蝶'),
('["beast", "earth", "defense", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '岩甲犀卵'),
  100,
  'beast+earth+defense+strength繁育，产出岩甲犀'),
('["beast", "earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '地龙蚓卵'),
  100,
  'beast+earth+serpent繁育，产出地龙蚓'),
('["spirit", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '石魔像卵'),
  100,
  'spirit+earth+defense繁育，产出石魔像'),
('["beast", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '厚土蟾卵'),
  100,
  'beast+earth+defense繁育，产出厚土蟾'),
('["beast", "earth", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '山魈卵'),
  100,
  'beast+earth+stealth繁育，产出山魈'),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '穿山甲灵卵'),
  100,
  'beast+earth+shell繁育，产出穿山甲灵'),
('["beast", "earth", "fire", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '麒麟卵'),
  100,
  'beast+earth+fire+auspicious繁育，产出麒麟'),
('["spirit", "earth", "strength", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '石巨人卵'),
  100,
  'spirit+earth+strength+defense繁育，产出石巨人'),
('["serpent", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '玄岩蟒卵'),
  100,
  'serpent+earth+defense繁育，产出玄岩蟒'),
('["dragon", "earth", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '黄龙卵'),
  100,
  'dragon+earth+auspicious繁育，产出黄龙'),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪兔卵'),
  100,
  'beast+ice繁育，产出雪兔'),
('["insect", "ice", "silk"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蚕卵'),
  100,
  'insect+ice+silk繁育，产出冰蚕'),
('["insect", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛾卵'),
  100,
  'insect+ice繁育，产出霜蛾'),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪鼠卵'),
  100,
  'beast+ice繁育，产出雪鼠'),
('["insect", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蝶卵'),
  100,
  'insect+ice繁育，产出冰蝶'),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛙卵'),
  100,
  'beast+ice繁育，产出霜蛙'),
('["flying", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪雀卵'),
  100,
  'flying+ice繁育，产出雪雀'),
('["insect", "ice", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '冰甲虫卵'),
  100,
  'insect+ice+shell繁育，产出冰甲虫'),
('["serpent", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛇卵'),
  100,
  'serpent+ice繁育，产出霜蛇'),
('["beast", "ice", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '雪狐卵'),
  100,
  'beast+ice+wisdom繁育，产出雪狐'),
('["beast", "ice", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '冰角鹿卵'),
  100,
  'beast+ice+auspicious繁育，产出冰角鹿'),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜狼卵'),
  100,
  'beast+ice繁育，产出霜狼'),
('["flying", "ice", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '冰鹤卵'),
  100,
  'flying+ice+auspicious繁育，产出冰鹤'),
('["beast", "ice", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '寒蟾卵'),
  100,
  'beast+ice+moon繁育，产出寒蟾'),
('["beast", "ice", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '雪猿卵'),
  100,
  'beast+ice+strength繁育，产出雪猿'),
('["beast", "ice", "water", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '黑水玄蛇卵'),
  100,
  'beast+ice+water+serpent繁育，产出黑水玄蛇'),
('["flying", "ice", "phoenix"]',
  (SELECT id FROM xt_item_template WHERE name = '冰凤卵'),
  100,
  'flying+ice+phoenix繁育，产出冰凤'),
('["serpent", "ice", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰巨蟒卵'),
  100,
  'serpent+ice+defense繁育，产出玄冰巨蟒'),
('["dragon", "ice", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰螭龙卵'),
  100,
  'dragon+ice+water繁育，产出玄冰螭龙'),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蛙卵'),
  100,
  'beast+thunder繁育，产出雷蛙'),
('["insect", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蝶卵'),
  100,
  'insect+wind繁育，产出风蝶'),
('["beast", "thunder", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '电鳗卵'),
  100,
  'beast+thunder+water繁育，产出电鳗'),
('["flying", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷雀卵'),
  100,
  'flying+thunder繁育，产出雷雀'),
('["beast", "wind", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '风鼠卵'),
  100,
  'beast+wind+speed繁育，产出风鼠'),
('["insect", "thunder", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '电蝎卵'),
  100,
  'insect+thunder+poison繁育，产出电蝎'),
('["insect", "thunder", "silk"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蚕卵'),
  100,
  'insect+thunder+silk繁育，产出雷蚕'),
('["serpent", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蛇卵'),
  100,
  'serpent+wind繁育，产出风蛇'),
('["insect", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电萤卵'),
  100,
  'insect+thunder繁育，产出电萤'),
('["flying", "thunder", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹰卵'),
  100,
  'flying+thunder+predator繁育，产出雷鹰'),
('["flying", "wind", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '风灵鹤卵'),
  100,
  'flying+wind+auspicious繁育，产出风灵鹤'),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电狼卵'),
  100,
  'beast+thunder繁育，产出电狼'),
('["beast", "thunder", "scale"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蜥蜴卵'),
  100,
  'beast+thunder+scale繁育，产出雷蜥蜴'),
('["serpent", "wind", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '风翼蛇卵'),
  100,
  'serpent+wind+flying繁育，产出风翼蛇'),
('["beast", "thunder", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '雷猿卵'),
  100,
  'beast+thunder+strength繁育，产出雷猿'),
('["beast", "thunder", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '夔牛卵'),
  100,
  'beast+thunder+myth繁育，产出夔牛'),
('["beast", "wind", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '飞廉卵'),
  100,
  'beast+wind+myth繁育，产出飞廉'),
('["flying", "thunder", "wind", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹏卵'),
  100,
  'flying+thunder+wind+predator繁育，产出雷鹏'),
('["dragon", "thunder", "wind", "flying", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '应龙卵'),
  100,
  'dragon+thunder+wind+flying+myth繁育，产出应龙'),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '灵雀卵'),
  100,
  'flying+beast繁育，产出灵雀'),
('["flying", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风燕卵'),
  100,
  'flying+wind繁育，产出风燕'),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '云鸽卵'),
  100,
  'flying+beast繁育，产出云鸽'),
('["flying", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹦卵'),
  100,
  'flying+wisdom繁育，产出灵鹦'),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹭卵'),
  100,
  'flying+water繁育，产出雾鹭'),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '烟鹤卵'),
  100,
  'flying+fire繁育，产出烟鹤'),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '霞鸠卵'),
  100,
  'flying+beast繁育，产出霞鸠'),
('["flying", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '岚鸦卵'),
  100,
  'flying+earth繁育，产出岚鸦'),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '霓莺卵'),
  100,
  'flying+beast繁育，产出霓莺'),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁羽鹰卵'),
  100,
  'flying+metal+predator繁育，产出铁羽鹰'),
('["flying", "support"]',
  (SELECT id FROM xt_item_template WHERE name = '比翼鸟卵'),
  100,
  'flying+support繁育，产出比翼鸟'),
('["flying", "wind", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '云鹏卵'),
  100,
  'flying+wind+myth繁育，产出云鹏'),
('["flying", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹤卵'),
  100,
  'flying+auspicious+heal繁育，产出灵鹤'),
('["flying", "wind", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '风隼卵'),
  100,
  'flying+wind+speed繁育，产出风隼'),
('["flying", "water", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹰卵'),
  100,
  'flying+water+stealth繁育，产出雾鹰'),
('["flying", "phoenix", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '青鸾卵'),
  100,
  'flying+phoenix+auspicious繁育，产出青鸾'),
('["flying", "speed", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '天马卵'),
  100,
  'flying+speed+myth繁育，产出天马'),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '金翼雕卵'),
  100,
  'flying+metal+predator繁育，产出金翼雕'),
('["flying", "metal", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '大鹏金翅鸟卵'),
  100,
  'flying+metal+myth繁育，产出大鹏金翅鸟'),
('["serpent", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '灵蛇卵'),
  100,
  'serpent+beast繁育，产出灵蛇'),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青蛇卵'),
  100,
  'serpent+wood繁育，产出青蛇'),
('["serpent", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛇卵'),
  100,
  'serpent+fire繁育，产出赤蛇'),
('["serpent", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '花蟒卵'),
  100,
  'serpent+beast繁育，产出花蟒'),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛇精卵'),
  100,
  'serpent+water繁育，产出水蛇精'),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '草蛇卵'),
  100,
  'serpent+earth繁育，产出草蛇'),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛇精卵'),
  100,
  'serpent+earth繁育，产出石蛇精'),
('["serpent", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蛇卵'),
  100,
  'serpent+metal繁育，产出金蛇'),
('["serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '墨蛇卵'),
  100,
  'serpent繁育，产出墨蛇'),
('["serpent", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '碧鳞蛇卵'),
  100,
  'serpent+poison繁育，产出碧鳞蛇'),
('["serpent", "dragon", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '蛟蜥卵'),
  100,
  'serpent+dragon+water繁育，产出蛟蜥'),
('["serpent", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '蟒精卵'),
  100,
  'serpent+strength繁育，产出蟒精'),
('["serpent", "fire", "scale"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鳞蛇卵'),
  100,
  'serpent+fire+scale繁育，产出赤鳞蛇'),
('["serpent", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '角蛇卵'),
  100,
  'serpent+dragon繁育，产出角蛇'),
('["serpent", "dragon", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠蛟卵'),
  100,
  'serpent+dragon+wood繁育，产出翠蛟'),
('["dragon", "sword", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '螭龙卵'),
  100,
  'dragon+sword+beast繁育，产出螭龙'),
('["serpent", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '内卷蛟卵'),
  100,
  'serpent+dragon繁育，产出内卷蛟'),
('["beast", "water", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '虎蛟卵'),
  100,
  'beast+water+dragon繁育，产出虎蛟'),
('["dragon", "fire", "light", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '烛龙卵'),
  100,
  'dragon+fire+light+myth繁育，产出烛龙'),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '福鼠卵'),
  100,
  'beast+auspicious繁育，产出福鼠'),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞兔卵'),
  100,
  'beast+auspicious繁育，产出瑞兔'),
('["flying", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '祥鸽卵'),
  100,
  'flying+auspicious繁育，产出祥鸽'),
('["beast", "auspicious", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '吉蛙卵'),
  100,
  'beast+auspicious+earth繁育，产出吉蛙'),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '灵猫卵'),
  100,
  'beast+auspicious繁育，产出灵猫'),
('["insect", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '喜蛛卵'),
  100,
  'insect+auspicious繁育，产出喜蛛'),
('["insect", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '福蝶卵'),
  100,
  'insect+auspicious繁育，产出福蝶'),
('["serpent", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞蛇卵'),
  100,
  'serpent+auspicious繁育，产出瑞蛇'),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '懒猴卵'),
  100,
  'beast+auspicious繁育，产出懒猴'),
('["beast", "auspicious", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '玉兔卵'),
  100,
  'beast+auspicious+moon繁育，产出玉兔'),
('["beast", "myth", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '乘黄卵'),
  100,
  'beast+myth+auspicious繁育，产出乘黄'),
('["beast", "wisdom", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽幼卵'),
  100,
  'beast+wisdom+auspicious繁育，产出白泽幼'),
('["flying", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞鹤卵'),
  100,
  'flying+auspicious+heal繁育，产出瑞鹤'),
('["beast", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '吉祥鹿卵'),
  100,
  'beast+auspicious+heal繁育，产出吉祥鹿'),
('["plant", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝仙卵'),
  100,
  'plant+auspicious+heal繁育，产出灵芝仙'),
('["beast", "wisdom", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽卵'),
  100,
  'beast+wisdom+auspicious繁育，产出白泽'),
('["beast", "auspicious", "heal", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'),
  100,
  'beast+auspicious+heal+wood繁育，产出九色鹿'),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '躺平貘卵'),
  100,
  'beast+auspicious繁育，产出躺平貘'),
('["beast", "earth", "fire", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '麒麟卵'),
  100,
  'beast+earth+fire+auspicious繁育，产出麒麟'),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '瘟鼠卵'),
  100,
  'beast+evil繁育，产出瘟鼠'),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '毒蛙卵'),
  100,
  'beast+evil+poison繁育，产出毒蛙'),
('["insect", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '邪蛛卵'),
  100,
  'insect+evil+poison繁育，产出邪蛛'),
('["insect", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '魔蛾卵'),
  100,
  'insect+evil繁育，产出魔蛾'),
('["serpent", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '煞蛇卵'),
  100,
  'serpent+evil繁育，产出煞蛇'),
('["insect", "evil", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '鬼萤卵'),
  100,
  'insect+evil+undead繁育，产出鬼萤'),
('["insect", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '厄蝎卵'),
  100,
  'insect+evil+poison繁育，产出厄蝎'),
('["flying", "evil", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '怨蝠卵'),
  100,
  'flying+evil+undead繁育，产出怨蝠'),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '瘴蟾卵'),
  100,
  'beast+evil+poison繁育，产出瘴蟾'),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇幼卵'),
  100,
  'beast+evil+flying繁育，产出穷奇幼'),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮幼卵'),
  100,
  'beast+evil+gluttony繁育，产出饕餮幼'),
('["beast", "evil", "chaos"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌幼卵'),
  100,
  'beast+evil+chaos繁育，产出混沌幼'),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌幼卵'),
  100,
  'beast+evil繁育，产出梼杌幼'),
('["beast", "evil", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '猰貐卵'),
  100,
  'beast+evil+strength繁育，产出猰貐'),
('["spirit", "evil", "chaos"]',
  (SELECT id FROM xt_item_template WHERE name = '浑敦卵'),
  100,
  'spirit+evil+chaos繁育，产出浑敦'),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇卵'),
  100,
  'beast+evil+flying繁育，产出穷奇'),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮卵'),
  100,
  'beast+evil+gluttony繁育，产出饕餮'),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌卵'),
  100,
  'beast+evil繁育，产出梼杌'),
('["beast", "evil", "chaos", "fire", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌卵'),
  100,
  'beast+evil+chaos+fire+earth繁育，产出混沌');
