INSERT
    INTO
        xt_mutation_trait_config(
            name,
            chinese_name,
            description,
            category,
            effects,
            required_tags,
            required_quality,
            sort_order
        )
    VALUES
        (
            'SHARP_FANG',
            '锐齿',
            '利齿如刃，噬物无声。攻击+15%',
            'ATTACK',
            '[{"type":"ATTACK_PERCENT","value":15}]'::jsonb,
            NULL,
            NULL,
            1
        ),
        (
            'THICK_SKIN',
            '厚皮',
            '皮糙肉厚，刀枪难伤。防御+15%',
            'DEFENSE',
            '[{"type":"DEFENSE_PERCENT","value":15}]'::jsonb,
            NULL,
            NULL,
            2
        ),
        (
            'SWIFT',
            '疾走',
            '足下生风，迅疾如电。身法+15%',
            'SPEED',
            '[{"type":"SPEED_PERCENT","value":15}]'::jsonb,
            NULL,
            NULL,
            3
        ),
        (
            'HIGH_YIELD',
            '高产',
            '灵蕴充盈，产出丰沛。产出量+30%',
            'PRODUCTION',
            '[{"type":"OUTPUT_PERCENT","value":30}]'::jsonb,
            NULL,
            NULL,
            4
        ),
        (
            'DILIGENT',
            '勤勉',
            '孜孜不倦，日夜不息。产出间隔-25%',
            'PRODUCTION',
            '[{"type":"OUTPUT_INTERVAL_REDUCE","value":25}]'::jsonb,
            NULL,
            NULL,
            5
        ),
        (
            'RARE_PRODUCE',
            '稀产',
            '偶得天赐，物华天宝。5%概率产出稀有物品',
            'PRODUCTION',
            '[{"type":"RARE_ITEM_CHANCE","value":5}]'::jsonb,
            NULL,
            NULL,
            6
        ),
        (
            'SPIRITUAL',
            '灵悟',
            '灵台清明，道心通明。升阶品质提升概率+10%',
            'BREAKTHROUGH',
            '[{"type":"QUALITY_UP_CHANCE","value":10}]'::jsonb,
            NULL,
            NULL,
            7
        ),
        (
            'SPIRIT_DEVOUR',
            '噬灵',
            '吞噬灵气，以战养战。击杀所得修为+25%',
            'EXP',
            '[{"type":"EXP_PERCENT","value":25}]'::jsonb,
            NULL,
            NULL,
            8
        ),
        (
            'SELF_HEAL',
            '自愈',
            '灵脉贯通，伤势自愈。战斗结束恢复10%最大HP',
            'COMBAT',
            '[{"type":"ON_BATTLE_END_HEAL","value":10}]'::jsonb,
            NULL,
            NULL,
            9
        ),
        (
            'FERTILE',
            '孕灵',
            '灵气孕体，子嗣昌盛。后代品质提升概率+15%',
            'BREEDING',
            '[{"type":"BREED_QUALITY_BOOST","value":15}]'::jsonb,
            NULL,
            NULL,
            10
        ),
        (
            'PROLIFIC',
            '多产',
            '血脉旺盛，繁衍不息。繁育冷却时间-30%',
            'BREEDING',
            '[{"type":"BREED_COOLDOWN_REDUCE","value":30}]'::jsonb,
            NULL,
            NULL,
            11
        ),
        (
            'BLOOD_AWAKEN',
            '血脉觉醒',
            '远古血脉苏醒，传承不灭。后代词条继承概率提升至50%',
            'BREEDING',
            '[{"type":"INHERIT_RATE_BOOST","value":25}]'::jsonb,
            NULL,
            NULL,
            12
        ),
        (
            'COUNTER',
            '反击',
            '受击反噬，以牙还牙。受击时15%概率反击，造成攻击50%伤害',
            'COMBAT',
            '[{"type":"COUNTER_ATTACK","value":50,"condition":{"trigger":"ON_ATTACKED"}}]'::jsonb,
            NULL,
            NULL,
            13
        ),
        (
            'BLOCK',
            '格挡',
            '铜墙铁壁，固若金汤。10%概率减免50%伤害',
            'COMBAT',
            '[{"type":"DAMAGE_REDUCE_CHANCE","value":50,"condition":{"trigger":"ON_HIT"}}]'::jsonb,
            NULL,
            NULL,
            14
        ),
        (
            'LIFESTEAL',
            '吸血',
            '噬血为生，以杀养命。伤害的10%转化为HP恢复',
            'COMBAT',
            '[{"type":"LIFESTEAL_PERCENT","value":10}]'::jsonb,
            NULL,
            NULL,
            15
        ),
        (
            'CRITICAL_STRIKE',
            '暴击',
            '雷霆一击，势不可挡。15%概率造成双倍伤害',
            'ATTACK',
            '[{"type":"CRITICAL_CHANCE","value":15}]'::jsonb,
            NULL,
            NULL,
            16
        ),
        (
            'ARMOR_PENETRATE',
            '破甲',
            '破防透骨，无坚不摧。无视目标15%防御',
            'ATTACK',
            '[{"type":"ARMOR_PENETRATE_PERCENT","value":15}]'::jsonb,
            NULL,
            NULL,
            17
        ),
        (
            'FURY',
            '怒意',
            '怒火焚心，以命搏命。攻击+10%，但防御-5%',
            'ATTACK',
            '[{"type":"ATTACK_PERCENT","value":10},{"type":"DEFENSE_PERCENT","value":-5}]'::jsonb,
            NULL,
            NULL,
            18
        ),
        (
            'TOUGH_HIDE',
            '铁皮',
            '铜皮铁骨，水火不侵。受到物理伤害减免8%',
            'DEFENSE',
            '[{"type":"PHYSICAL_DAMAGE_REDUCE","value":8}]'::jsonb,
            NULL,
            NULL,
            19
        ),
        (
            'STONE_SKIN',
            '石化',
            '金刚不坏，万法不侵。5%概率免疫本次伤害',
            'DEFENSE',
            '[{"type":"IMMUNITY_CHANCE","value":5}]'::jsonb,
            NULL,
            NULL,
            20
        ),
        (
            'AGILITY',
            '灵巧',
            '身轻如燕，闪转腾挪。闪避率+10%',
            'SPEED',
            '[{"type":"DODGE_CHANCE","value":10}]'::jsonb,
            NULL,
            NULL,
            21
        ),
        (
            'BLITZ',
            '疾风',
            '快如闪电，先发制人。首次攻击身法+50%',
            'SPEED',
            '[{"type":"FIRST_ATTACK_SPEED_BOOST","value":50}]'::jsonb,
            NULL,
            NULL,
            22
        ),
        (
            'REGENERATION',
            '再生',
            '生生不息，血肉重生。每回合恢复最大HP的3%',
            'COMBAT',
            '[{"type":"HP_REGEN_PERCENT","value":3}]'::jsonb,
            NULL,
            NULL,
            23
        ),
        (
            'SPIRIT_ABSORB',
            '引灵',
            '吸纳天地，灵力充盈。战斗结束额外获得10点灵力',
            'COMBAT',
            '[{"type":"MANA_GAIN","value":10}]'::jsonb,
            NULL,
            NULL,
            24
        ),
        (
            'ANCIENT_BLOOD',
            '古血',
            '远古血脉，返璞归真。10%概率产出稀有品质后代',
            'BREEDING',
            '[{"type":"RARE_OFFSPRING_CHANCE","value":10}]'::jsonb,
            NULL,
            NULL,
            25
        ),
        (
            'TWIN_BIRTH',
            '双生',
            '阴阳并蒂，一胎双生。5%概率同时产出两只后代',
            'BREEDING',
            '[{"type":"TWIN_CHANCE","value":5}]'::jsonb,
            NULL,
            NULL,
            26
        ),
        (
            'HERITAGE',
            '传承',
            '薪火相传，青出于蓝。后代随机继承父母一个已有词条',
            'BREEDING',
            '[{"type":"INHERIT_EXISTING_TRAIT","value":100}]'::jsonb,
            NULL,
            NULL,
            27
        ),
        (
            'LUCKY',
            '福运',
            '福星高照，气运加身。稀有产出概率额外+3%',
            'PRODUCTION',
            '[{"type":"RARE_ITEM_CHANCE","value":3}]'::jsonb,
            NULL,
            NULL,
            28
        ),
        (
            'ABUNDANCE',
            '丰饶',
            '地灵人杰，物产丰饶。基础产出量+15%',
            'PRODUCTION',
            '[{"type":"OUTPUT_PERCENT","value":15}]'::jsonb,
            NULL,
            NULL,
            29
        ),
        (
            'ENLIGHTENED',
            '顿悟',
            '一朝顿悟，道法自然。修为获取+20%',
            'EXP',
            '[{"type":"EXP_PERCENT","value":20}]'::jsonb,
            NULL,
            NULL,
            30
        ),
        (
            'COMPREHEND',
            '悟道',
            '参悟天机，修为大进。击败强敌时修为+50%',
            'EXP',
            '[{"type":"EXP_PERCENT_STRONG_ENEMY","value":50}]'::jsonb,
            NULL,
            NULL,
            31
        ),
        (
            'MALEVOLENCE',
            '煞气',
            '龙威赫赫，煞气冲天。攻击+25%',
            'ATTACK',
            '[{"type":"ATTACK_PERCENT","value":25}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'IMMORTAL',
            32
        ),
        (
            'MYSTIC_ARMOR',
            '玄甲',
            '龙鳞护体，坚不可摧。防御+25%',
            'DEFENSE',
            '[{"type":"DEFENSE_PERCENT","value":25}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'SAINT',
            33
        ),
        (
            'LIGHTNING_CHASE',
            '追电',
            '追风逐电，瞬息万里。身法+30%',
            'SPEED',
            '[{"type":"SPEED_PERCENT","value":30}]'::jsonb,
            '["flying"]'::jsonb,
            'IMMORTAL',
            34
        ),
        (
            'BERSERK',
            '狂暴',
            '困兽犹斗，背水一战。HP低于30%时攻击+50%',
            'COMBAT',
            '[{"type":"LOW_HP_ATTACK_BOOST","value":50,"condition":{"trigger":"HP_BELOW","threshold":30}}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'SAINT',
            35
        ),
        (
            'PHOENIX_REBIRTH',
            '涅槃',
            '浴火重生，凤凰涅槃。死亡时10%概率复活并恢复30%HP',
            'COMBAT',
            '[{"type":"REVIVE_CHANCE","value":10,"condition":{"trigger":"ON_DEATH"}}]'::jsonb,
            '["beast"]'::jsonb,
            'SAINT',
            36
        ),
        (
            'DRAGON_BREATH',
            '龙息',
            '龙吟九霄，气吞山河。攻击时8%概率造成范围伤害',
            'ATTACK',
            '[{"type":"AOE_CHANCE","value":8}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'IMMORTAL',
            37
        ),
        (
            'PHANTOM_STEP',
            '幻步',
            '虚实难辨，如影随形。战斗开始20%概率闪避首次攻击',
            'SPEED',
            '[{"type":"FIRST_ATTACK_DODGE","value":20}]'::jsonb,
            '["flying"]'::jsonb,
            'IMMORTAL',
            38
        ),
        (
            'SOUL_CHAIN',
            '魂链',
            '生死与共，魂魄相连。15%概率将致命伤害转移给攻击者',
            'COMBAT',
            '[{"type":"DAMAGE_TRANSFER","value":15}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'DIVINE',
            39
        ),
        (
            'TIME_WARP',
            '时空扭曲',
            '颠倒时空，因果逆转。5%概率使对手跳过下一回合',
            'COMBAT',
            '[{"type":"SKIP_TURN_CHANCE","value":5}]'::jsonb,
            '["flying"]'::jsonb,
            'SAINT',
            40
        ),
        (
            'ELEMENTAL_MASTERY',
            '五行精通',
            '五行归一，万法皆通。所有属性+8%',
            'ATTACK',
            '[{"type":"ALL_STATS_PERCENT","value":8}]'::jsonb,
            '["beast"]'::jsonb,
            'DIVINE',
            41
        ),
        (
            'HEAVEN_TALENT',
            '天资',
            '天资卓绝，修行神速。升级所需修为-20%',
            'EXP',
            '[{"type":"EXP_REDUCE_PERCENT","value":20}]'::jsonb,
            '["beast"]'::jsonb,
            'SAINT',
            42
        ),
        (
            'GOLDEN_BODY',
            '金身',
            '金身护体，百邪不侵。前3回合防御+30%',
            'DEFENSE',
            '[{"type":"TEMPORARY_DEFENSE_BOOST","value":30,"condition":{"trigger":"FIRST_N_TURNS","turns":3}}]'::jsonb,
            '["beast"]'::jsonb,
            'IMMORTAL',
            43
        ),
        (
            'BLOODLUST',
            '嗜血',
            '以战养战，越战越勇。每次攻击后攻击+5%（可叠加5层）',
            'ATTACK',
            '[{"type":"STACKING_ATTACK_BOOST","value":5,"maxStacks":5}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'SAINT',
            44
        ),
        (
            'MYSTIC_EYE',
            '天眼',
            '洞察秋毫，明察万物。攻击时10%概率无视目标闪避',
            'ATTACK',
            '[{"type":"IGNORE_DODGE_CHANCE","value":10}]'::jsonb,
            '["beast"]'::jsonb,
            'IMMORTAL',
            45
        ),
        (
            'EARTH_SHAKE',
            '震地',
            '地动山摇，万物臣服。攻击时5%概率使目标眩晕跳过下回合',
            'COMBAT',
            '[{"type":"STUN_CHANCE","value":5}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'SAINT',
            46
        ),
        (
            'WIND_RIDER',
            '御风',
            '乘风而起，扶摇直上。身法+20%，闪避率+5%',
            'SPEED',
            '[{"type":"SPEED_PERCENT","value":20},{"type":"DODGE_CHANCE","value":5}]'::jsonb,
            '["flying"]'::jsonb,
            'IMMORTAL',
            47
        ),
        (
            'SPIRIT_VEIN',
            '灵脉',
            '灵脉贯通，生生不息。每回合额外恢复5点灵力',
            'COMBAT',
            '[{"type":"MANA_REGEN","value":5}]'::jsonb,
            '["beast"]'::jsonb,
            'IMMORTAL',
            48
        ),
        (
            'DESTINY',
            '天命',
            '天命所归，气运加身。所有概率性效果触发率+20%',
            'COMBAT',
            '[{"type":"PROBABILITY_MULTIPLIER","value":20}]'::jsonb,
            '["beast","dragon"]'::jsonb,
            'DIVINE',
            49
        ),
        (
            'VOID_STEP',
            '虚空步',
            '虚空挪移，神出鬼没。每回合10%概率完全闪避攻击',
            'SPEED',
            '[{"type":"EVADE_CHANCE","value":10}]'::jsonb,
            '["flying"]'::jsonb,
            'SAINT',
            50
        ),
        (
            'IMMORTAL_BODY',
            '不灭体',
            '金刚不坏，不死不灭。受到致命伤害时5%概率保留1点HP',
            'COMBAT',
            '[{"type":"SURVIVE_LETHAL_CHANCE","value":5}]'::jsonb,
            '["beast"]'::jsonb,
            'DIVINE',
            51
        );
