INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAINING',
        2,
        'training_rare_herb_found',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝'
                    ),
                    'min',
                    2,
                    'max',
                    4
                )
            )
        )
    ),
    (
        'TRAINING',
        3,
        'training_buried_treasure',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'TRAINING',
        3,
        'training_strange_stone',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '赤铜矿'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAINING',
        4,
        'training_qi_storm',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 50}]}'
    ),
    (
        'TRAINING',
        5,
        'training_rival_encounter',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAINING',
        7,
        'training_rare_herb_found',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '地火芝'
                    ),
                    'min',
                    1,
                    'max',
                    3
                )
            )
        )
    ),
    (
        'TRAINING',
        8,
        'training_evil_presence',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "TAKE_DAMAGE_FLAT", "amount": 30}]}'
    ),
    (
        'TRAINING',
        9,
        'training_ancient_ruins',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAINING',
        12,
        'training_beast_den_found',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAINING',
        14,
        'training_meditation_epiphany',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 200}]}'
    ),
    (
        'TRAINING',
        15,
        'training_ancient_ruins',
        'NUMERIC',
        12,
        FALSE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '青莲剑歌'
            )
        ),
        '{}'
    ),
    (
        'TRAINING',
        16,
        'training_rare_herb_found',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '地火芝'
                    ),
                    'min',
                    2,
                    'max',
                    5
                )
            )
        )
    ),
    (
        'TRAINING',
        20,
        'training_strange_stone',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '紫金砂'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'TRAINING',
        23,
        'training_spirit_guide',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 150}]}'
    ),
    (
        'TRAINING',
        27,
        'training_evil_presence',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "TAKE_DAMAGE_FLAT", "amount": 80}]}'
    ),
    (
        'TRAINING',
        29,
        'training_meditation_epiphany',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 500}]}'
    ),
    (
        'TRAINING',
        32,
        'training_qi_storm',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 300}]}'
    ),
    (
        'TRAINING',
        34,
        'training_meditation_epiphany',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 800}]}'
    ),
    (
        'TRAINING',
        38,
        'training_spirit_guide',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 500}]}'
    ),
    (
        'TRAINING',
        39,
        'training_meditation_epiphany',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 1000}]}'
    ),
    (
        'TRAINING',
        41,
        'training_qi_storm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 500}]}'
    );

INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAINING',
        29,
        'training_spirit_guide',
        'NUMERIC',
        8,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '一气化三清'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '魂玉碎片'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAINING',
        40,
        'training_meditation_epiphany',
        'NUMERIC',
        8,
        TRUE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":85}',
        '{"effects": [{"type": "ADD_EXP", "amount": 5000}]}'
    ),
    (
        'TRAINING',
        44,
        'training_ancient_ruins',
        'NUMERIC',
        5,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '轩辕剑法'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'CREATE_EQUIPMENT',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_equipment_template
                        WHERE
                            name = '轩辕剑'
                    )
                )
            )
        )
    );

-- =================================================================
-- 新增历练事件（第二批）
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAINING',
        2,
        'training_elemental_whisper',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAINING',
        5,
        'training_moon_tide',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 150}, {"type": "HEAL_FLAT", "amount": 80}]}'
    ),
    (
        'TRAINING',
        8,
        'training_forgotten_alchemy',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '地火芝'
                    ),
                    'min',
                    3,
                    'max',
                    6
                )
            )
        )
    ),
    (
        'TRAINING',
        10,
        'training_sword_intent',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 80}]}'
    ),
    (
        'TRAINING',
        10,
        'training_deep_insight',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 120}]}'
    ),
    (
        'TRAINING',
        12,
        'training_heavenly_fruit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    60
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAINING',
        16,
        'training_beast_training',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '兽骨'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '妖兽皮'
                        )
                    ),
                    'chance',
                    0.6
                )
            )
        )
    ),
    (
        'TRAINING',
        20,
        'training_elemental_whisper',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '寒铁'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'TRAINING',
        23,
        'training_ancient_talisman',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    200
                ),
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄晶'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAINING',
        27,
        'training_sword_intent',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 300}]}'
    ),
    (
        'TRAINING',
        27,
        'training_moon_tide',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 200}, {"type": "HEAL_FLAT", "amount": 400}]}'
    ),
    (
        'TRAINING',
        32,
        'training_deep_insight',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 600}]}'
    ),
    (
        'TRAINING',
        39,
        'training_heavenly_fruit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝'
                    ),
                    'count',
                    5
                )
            )
        )
    ),
    (
        'TRAINING',
        39,
        'training_ancient_talisman',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    1200
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '魂玉碎片'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAINING',
        44,
        'training_sword_intent',
        'NUMERIC',
        10,
        FALSE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '青莲剑歌'
            )
        ),
        '{"effects": [{"type": "ADD_EXP", "amount": 1500}]}'
    ),
    (
        'TRAINING',
        5,
        'training_beast_training',
        'NUMERIC',
        6,
        TRUE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '兽骨'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '聚灵丹'
                    ),
                    'count',
                    5
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    300
                )
            )
        )
    );
