-- ============================================================
-- 仙道 · xt_bounty 种子数据
-- ============================================================
INSERT INTO xt_bounty (map_id, name, description, duration_minutes, rewards, require_level, event_weight) VALUES
((SELECT id FROM xt_map_node WHERE name='青山镇'),'采药童子','药铺缺人手去青云山外门采集聚灵草。老板抠门报酬刚好够路费——但新手积累经验的好机会。',5,jsonb_build_array(jsonb_build_object('name','培元丹','template_id',(SELECT id FROM xt_item_template WHERE name='培元丹'),'weight',100,'min_count',1,'max_count',1,'type','rare_item')),1,100),
((SELECT id FROM xt_map_node WHERE name='落霞坊市'),'坊市跑腿','落霞坊市散修需帮忙跑腿送东西。任务无聊但能混脸熟——说不定遇到便宜货。',8,jsonb_build_array(jsonb_build_object('name','凝气丹','template_id',(SELECT id FROM xt_item_template WHERE name='凝气丹'),'weight',100,'min_count',1,'max_count',2,'type','rare_item')),3,80),
((SELECT id FROM xt_map_node WHERE name='青云山外门'),'外门巡逻','青云宗外门长老安排巡逻确保外门没妖兽闯入。大部分时间只是散步——偶遇低阶妖兽。',10,jsonb_build_array(jsonb_build_object('name','凝气丹','template_id',(SELECT id FROM xt_item_template WHERE name='凝气丹'),'weight',60,'min_count',1,'max_count',2,'type','rare_item'),jsonb_build_object('name','聚灵草种子','template_id',(SELECT id FROM xt_item_template WHERE name='聚灵草种子'),'weight',40,'min_count',1,'max_count',3,'type','rare_item')),5,70),
((SELECT id FROM xt_map_node WHERE name='青云山外门'),'妖兽清剿','外门附近出现几只妖狼需前去清理。适合想证明自己的新手。失败会得到:"道友要不先练练轻身术？"',15,jsonb_build_array(jsonb_build_object('name','筑基丹','template_id',(SELECT id FROM xt_item_template WHERE name='筑基丹'),'weight',60,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','凝气花种子','template_id',(SELECT id FROM xt_item_template WHERE name='凝气花种子'),'weight',40,'min_count',1,'max_count',2,'type','rare_item')),8,60),
((SELECT id FROM xt_map_node WHERE name='枯骨林入口'),'枯骨寻宝','富商声称祖上在枯骨林埋了宝物悬赏勇士寻找。直觉告诉是骗局——但万一有好东西呢？',20,jsonb_build_array(jsonb_build_object('name','玄铁','template_id',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',60,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','星辰砂','template_id',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',40,'min_count',1,'max_count',3,'type','rare_item')),10,50),
((SELECT id FROM xt_map_node WHERE name='枯骨林深处'),'亡者安宁','枯骨林亡魂越来越多影响坊市生意。需修士前往安抚亡魂——物理安抚(火球术雷法效果更佳)。',25,jsonb_build_array(jsonb_build_object('name','大还丹','template_id',(SELECT id FROM xt_item_template WHERE name='大还丹'),'weight',60,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','血菩提','template_id',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',40,'min_count',1,'max_count',2,'type','rare_item')),20,50),
((SELECT id FROM xt_map_node WHERE name='天阙城'),'天阙城护卫','天阙城守卫长需修士协助维护秩序。体面报酬高不用打打杀杀——就是站一天腰有点疼。',30,jsonb_build_array(jsonb_build_object('name','大还丹','template_id',(SELECT id FROM xt_item_template WHERE name='大还丹'),'weight',50,'min_count',1,'max_count',2,'type','rare_item'),jsonb_build_object('name','破障丹','template_id',(SELECT id FROM xt_item_template WHERE name='破障丹'),'weight',50,'min_count',1,'max_count',1,'type','rare_item')),30,40),
((SELECT id FROM xt_map_node WHERE name='青云山内门'),'青云内门试炼','内门弟子必经试炼——击败指定数量敌人。通过者获内门长老认可——散修眼里一文不值但奖励是真的。',35,jsonb_build_array(jsonb_build_object('name','洗髓丹','template_id',(SELECT id FROM xt_item_template WHERE name='洗髓丹'),'weight',50,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','龙鳞','template_id',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',50,'min_count',1,'max_count',2,'type','rare_item')),25,40),
((SELECT id FROM xt_map_node WHERE name='修罗场外围'),'修罗试剑','自称"剑痴"的老人找能接下他三剑的修士。奖励丰厚风险也高。',40,jsonb_build_array(jsonb_build_object('name','破障丹','template_id',(SELECT id FROM xt_item_template WHERE name='破障丹'),'weight',50,'min_count',1,'max_count',2,'type','rare_item'),jsonb_build_object('name','万年寒铁','template_id',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',50,'min_count',1,'max_count',3,'type','rare_item')),35,35),
((SELECT id FROM xt_map_node WHERE name='万妖谷'),'妖王伏诛','万妖谷深处妖王级怪物悬赏勇士诛杀。建议组队——实际组队者互不认识且最后奖励没分清。',45,jsonb_build_array(jsonb_build_object('name','破障丹','template_id',(SELECT id FROM xt_item_template WHERE name='破障丹'),'weight',50,'min_count',1,'max_count',3,'type','rare_item'),jsonb_build_object('name','凤凰翎','template_id',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',50,'min_count',1,'max_count',3,'type','rare_item')),40,30),
((SELECT id FROM xt_map_node WHERE name='九天玄刹'),'九天寻宝','九天玄刹发现未探索遗迹需要修士去调查。"去调查"是修仙界最危险动词——通常意味着第一个进去最后一个出来。',50,jsonb_build_array(jsonb_build_object('name','九转还魂丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转还魂丹'),'weight',50,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','九天息壤','template_id',(SELECT id FROM xt_item_template WHERE name='九天息壤'),'weight',50,'min_count',1,'max_count',2,'type','rare_item')),50,25),
((SELECT id FROM xt_map_node WHERE name='修罗场核心'),'血战修罗','修罗场核心大规模混战需活下去。"修罗场没任务只有生死——发布悬赏让你去就是借刀杀人。"',60,jsonb_build_array(jsonb_build_object('name','九转还魂丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转还魂丹'),'weight',40,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','舍利子','template_id',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',60,'min_count',1,'max_count',2,'type','rare_item')),60,20),
((SELECT id FROM xt_map_node WHERE name='龙渊入口'),'龙渊试炼','龙族守护者寻找有资格进入龙渊的人。试炼通过获丰厚奖励——龙族标准比天劫还离谱通过者凤毛麟角。',90,jsonb_build_array(jsonb_build_object('name','九转还魂丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转还魂丹'),'weight',40,'min_count',1,'max_count',2,'type','rare_item'),jsonb_build_object('name','舍利子','template_id',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',60,'min_count',1,'max_count',3,'type','rare_item')),70,10),
((SELECT id FROM xt_map_node WHERE name='仙界遗迹外围'),'仙帝遗宝','仙界遗迹外围发现疑似仙帝储物法宝碎片天下修士闻风而动。"仙帝遗宝面前没有道友只有竞争对手。"',120,jsonb_build_array(jsonb_build_object('name','九天息壤','template_id',(SELECT id FROM xt_item_template WHERE name='九天息壤'),'weight',40,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','舍利子','template_id',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',60,'min_count',1,'max_count',5,'type','rare_item')),90,5),
((SELECT id FROM xt_map_node WHERE name='铸剑山'),'锻铁学徒','铸剑山铁匠永远缺人——帮拉风箱搬铁块在他骂你时保持微笑。报酬一般但学锻造基础——教的都是错的。',10,jsonb_build_array(jsonb_build_object('name','玄铁','template_id',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',60,'min_count',1,'max_count',10,'type','rare_item'),jsonb_build_object('name','火灵石','template_id',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',40,'min_count',1,'max_count',3,'type','rare_item')),15,70),
((SELECT id FROM xt_map_node WHERE name='灵药谷'),'采药大典','灵药谷年度盛事——一炷香内尽可能多采药但不能踩谷主任何灵植。去年冠军踩坏朱果被追着从谷头跑到谷尾。',20,jsonb_build_array(jsonb_build_object('name','聚灵草种子','template_id',(SELECT id FROM xt_item_template WHERE name='聚灵草种子'),'weight',60,'min_count',1,'max_count',10,'type','rare_item'),jsonb_build_object('name','灵茶叶','template_id',(SELECT id FROM xt_item_template WHERE name='灵茶叶'),'weight',40,'min_count',1,'max_count',3,'type','rare_item')),25,60),
((SELECT id FROM xt_map_node WHERE name='亡魂沼泽'),'亡者安抚','沼泽亡魂激增需物理安抚(火球术雷法驱散)。"安抚亡魂不如打架爽快——至少打架有战利品。"',15,jsonb_build_array(jsonb_build_object('name','幽冥铁','template_id',(SELECT id FROM xt_item_template WHERE name='幽冥铁'),'weight',60,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','魔血石','template_id',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',40,'min_count',1,'max_count',3,'type','rare_item')),18,55),
((SELECT id FROM xt_map_node WHERE name='烈焰荒漠'),'沙海淘金','烈焰荒漠深处火灵石矿脉被沙暴蜥蜴占据。清剿蜥蜴采集火灵石——注意温度把水蒸发得比喝水快。',30,jsonb_build_array(jsonb_build_object('name','火灵石','template_id',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',50,'min_count',1,'max_count',10,'type','rare_item'),jsonb_build_object('name','星核碎片','template_id',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',50,'min_count',1,'max_count',5,'type','rare_item')),35,40),
((SELECT id FROM xt_map_node WHERE name='须弥山'),'扫地修行','扫三千六百级台阶扫完获高僧"善哉"及佛门宝物。扫到三千级会顿悟人生——然后发现还有六百级。',45,jsonb_build_array(jsonb_build_object('name','舍利子','template_id',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',50,'min_count',1,'max_count',2,'type','rare_item'),jsonb_build_object('name','菩提子','template_id',(SELECT id FROM xt_item_template WHERE name='菩提子'),'weight',50,'min_count',1,'max_count',2,'type','rare_item')),60,30),
((SELECT id FROM xt_map_node WHERE name='星辰海'),'星光采集','星辰砂天然产地——采集需精确算星光时间。天机阁历法误差不超三秒但价格不菲。本悬赏提供免费历法——采集到的分天机阁三成。',40,jsonb_build_array(jsonb_build_object('name','星辰砂','template_id',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',60,'min_count',1,'max_count',10,'type','rare_item'),jsonb_build_object('name','星核碎片','template_id',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',40,'min_count',1,'max_count',5,'type','rare_item')),50,35),
((SELECT id FROM xt_map_node WHERE name='魔界裂隙'),'封魔令','魔界裂隙涌出大量蠕虫高阶魔物。正道联盟"封魔"就是把魔赶裂隙对面——对面什么情况没人管。裂隙迟早再打开——往复循环。',50,jsonb_build_array(jsonb_build_object('name','虚空结晶','template_id',(SELECT id FROM xt_item_template WHERE name='虚空结晶'),'weight',40,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','魔血石','template_id',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',60,'min_count',1,'max_count',8,'type','rare_item')),65,30),
((SELECT id FROM xt_map_node WHERE name='无尽海'),'渡海使','自称"航海家"散修需同伴横渡无尽海——第一千三百多个报名者(前皆未归)。用聚灵草杆扎的船——但很富有(继承了一千多失踪者遗产)。',120,jsonb_build_array(jsonb_build_object('name','混沌元晶','template_id',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',60,'min_count',1,'max_count',3,'type','rare_item'),jsonb_build_object('name','天道碎片','template_id',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',40,'min_count',1,'max_count',2,'type','rare_item')),80,8),
((SELECT id FROM xt_map_node WHERE name='万妖谷深处'),'妖王狩猎','万妖谷深处极危妖王(疑似远古武神坐骑后代)。天机阁建议"五人组队每人带三颗涅槃丹"——凑到四人就互相猜疑——材料只够分两份。',90,jsonb_build_array(jsonb_build_object('name','神血石','template_id',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',50,'min_count',1,'max_count',3,'type','rare_item'),jsonb_build_object('name','九转还魂丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转还魂丹'),'weight',50,'min_count',1,'max_count',2,'type','rare_item')),90,10),
((SELECT id FROM xt_map_node WHERE name='天机阁'),'情报网','天机阁招"情报员"——从各大宗门套公开信息回来报告。"不是间谍是信息整合。"实际是抄公告——每次抄完怀疑自己在做什么见不得人的事。',15,jsonb_build_array(jsonb_build_object('name','悟道丹','template_id',(SELECT id FROM xt_item_template WHERE name='悟道丹'),'weight',100,'min_count',1,'max_count',1,'type','rare_item')),80,40),
((SELECT id FROM xt_map_node WHERE name='幽冥深渊'),'阴间快递','深渊底部"存在"声称需人间东西——带一箱"常见日用品"下深渊交给它返回。深渊怪物抢那箱东西因为好奇是什么——反转：最后发现是一堆培元丹。',60,jsonb_build_array(jsonb_build_object('name','虚空结晶','template_id',(SELECT id FROM xt_item_template WHERE name='虚空结晶'),'weight',50,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','虚空草','template_id',(SELECT id FROM xt_item_template WHERE name='虚空草'),'weight',50,'min_count',1,'max_count',3,'type','rare_item')),55,20),
((SELECT id FROM xt_map_node WHERE name='远古神墓'),'解谜大师','远古神墓发现上古谜题——解开获神祇祝福。问题是失传文字笔仙可翻译但每天十个字——历时数月马拉松解谜。最慢节奏悬赏。',180,jsonb_build_array(jsonb_build_object('name','天道碎片','template_id',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',50,'min_count',1,'max_count',5,'type','rare_item'),jsonb_build_object('name','神血石','template_id',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',50,'min_count',1,'max_count',5,'type','rare_item')),75,12),
((SELECT id FROM xt_map_node WHERE name='天道之路'),'渡劫陪跑','天道之路散修准备渡最后一道飞升天劫——需人"陪跑"。多方求证后发现：站旁边万一渡劫失败帮他把遗物带回去。最悲壮悬赏。',120,jsonb_build_array(jsonb_build_object('name','九转金丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转金丹'),'weight',40,'min_count',1,'max_count',1,'type','rare_item'),jsonb_build_object('name','天道碎片','template_id',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',60,'min_count',1,'max_count',3,'type','rare_item')),95,5),
((SELECT id FROM xt_map_node WHERE name='虚空裂缝'),'时空猎人','虚空裂缝出现虚空领主。天机阁悬赏最强修士击杀。"我相信一定有人能打败它——至于那人是不是你——就是另一问题了。"十大不可能悬赏。',240,jsonb_build_array(jsonb_build_object('name','混沌元晶','template_id',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',50,'min_count',1,'max_count',10,'type','rare_item'),jsonb_build_object('name','九转金丹','template_id',(SELECT id FROM xt_item_template WHERE name='九转金丹'),'weight',50,'min_count',1,'max_count',3,'type','rare_item')),85,5),
((SELECT id FROM xt_map_node WHERE name='混沌之源'),'本源探索','修真界最大悬赏——追寻混沌之源。无人知道在哪所以这悬赏是让你"在寻找中变强"。赏金可买整座天阙城——已挂六千年无人领。每个修士都成了悬赏本身一部分。',8760,jsonb_build_array(jsonb_build_object('name','天道碎片','template_id',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',50,'min_count',1,'max_count',20,'type','rare_item'),jsonb_build_object('name','混沌元晶','template_id',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',50,'min_count',1,'max_count',20,'type','rare_item')),100,1);
SELECT setval('xt_bounty_id_seq', (SELECT COALESCE(MAX(id), 0) FROM xt_bounty));
