-- ============================================================
-- 仙道 · xt_monster_template 种子数据
-- ============================================================
INSERT INTO xt_monster_template (name, description, monster_type, base_level, base_hp, base_attack, base_defense, base_speed, exp_reward, skills, drop_table, tags) VALUES
('山精','','BEAST',1,50,5,2,8,10,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('石灵','','BEAST',3,80,8,6,5,30,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('妖狼','','WILD_BEAST',5,120,12,5,12,50,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('食灵鼠','','BEAST',2,30,3,1,20,20,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('石魔','','ARMORED',10,300,20,25,4,100,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('枯骨将军','','EVIL',15,400,30,20,10,150,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('噬魂鬼','','EVIL',12,250,35,10,15,120,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('食人花妖','','SPIRIT',18,500,40,15,12,180,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('九尾妖狐','','SPIRIT',25,800,60,30,25,250,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('血蚊王','','FLYING',22,600,50,20,35,220,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('修罗战魂','','EVIL',30,1200,90,50,18,300,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('九头蛇','','SPIRIT',28,1500,70,60,10,280,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('玄冥龟','','ARMORED',40,3000,100,150,3,400,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('赤焰蛟龙','','FLYING',45,3500,180,100,25,450,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('噬心魔','','EVIL',48,2800,200,80,30,480,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('飞天夜叉','','FLYING',42,3000,160,90,28,420,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('远古石像鬼','','ARMORED',55,6000,250,200,15,550,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('不死凤凰','','SPIRIT',60,5000,300,150,35,600,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('修罗王','','EVIL',65,8000,400,250,25,650,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('万年妖藤','','SPIRIT',58,10000,200,200,5,580,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('远古黑龙','','FLYING',75,15000,600,400,30,750,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('天劫雷兽','','SPIRIT',85,25000,800,500,50,850,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('混沌巨兽','','SPIRIT',95,50000,1200,800,20,950,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('剑痴残魂','','HUMAN',50,4000,500,100,40,500,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('沼泽泥怪','','BEAST',18,600,25,40,3,180,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('火蝎','','BEAST',22,450,55,30,18,220,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('沙暴蜥蜴','','WILD_BEAST',30,1800,100,50,20,300,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('星尘蝶','','FLYING',35,1200,80,35,35,350,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('深渊蠕虫','','BEAST',40,4000,120,80,5,400,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('熔岩巨兽','','ARMORED',45,6000,200,150,8,450,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('虚空行者','','SPIRIT',50,5000,250,100,30,500,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('暗影刺客','','HUMAN',55,4000,350,80,40,550,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('寒冰女王','','SPIRIT',58,7000,300,150,22,580,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('九幽冥凤','','FLYING',65,10000,400,200,35,650,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('星辰守护者','','ARMORED',70,15000,500,400,12,700,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('吞噬魔','','EVIL',72,12000,450,250,25,720,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('远古武神','','HUMAN',78,20000,700,300,30,780,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('虚空领主','','SPIRIT',85,30000,900,500,35,850,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('魔界之主','','EVIL',90,40000,1100,600,30,900,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('天道化身','','SPIRIT',95,50000,1300,700,40,950,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('混沌之眼','','SPIRIT',100,80000,2000,1000,25,1000,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('万剑剑灵','','HUMAN',92,25000,1500,300,50,920,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('上古龙神','','FLYING',98,60000,1800,900,45,980,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb),
('飞升失败者','','HUMAN',100,100000,2500,1200,30,1000,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb);
SELECT setval('xt_monster_template_id_seq', (SELECT COALESCE(MAX(id), 0) FROM xt_monster_template));

-- ============================================================
-- 怪物掉落表 (drop_table)
-- category: "item" (材料/丹药/药材等) 或 "equipment" (装备模板)
-- ============================================================

-- Lv 1-8 新手怪物：基础材料、低级药材、初级装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草'),'weight',60),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',30),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='粗布道袍'),'weight',10))::jsonb WHERE name = '山精';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凝气花'),'weight',50),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',35),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='桃木符'),'weight',15))::jsonb WHERE name = '石灵';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='灵茶叶'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',25),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='破风刀'),'weight',10))::jsonb WHERE name = '妖狼';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草'),'weight',70),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草种子'),'weight',30))::jsonb WHERE name = '食灵鼠';

-- Lv 10-15 初级怪物：材料、种子、初级装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='玄铁'),'weight',50),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',30),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='青竹剑'),'weight',20))::jsonb WHERE name = '石魔';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='幽冥铁'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草种子'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凝气花种子'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='桃木符'),'weight',10))::jsonb WHERE name = '枯骨将军';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凝气花'),'weight',50),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',30),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='粗布道袍'),'weight',20))::jsonb WHERE name = '噬魂鬼';

-- Lv 18-25 中低级怪物：区域特产材料、药材、种子
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='幽冥铁'),'weight',45),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='聚灵草'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='寒光剑'),'weight',10))::jsonb WHERE name = '沼泽泥怪';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵芝'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='朱果种子'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='开山斧'),'weight',10))::jsonb WHERE name = '食人花妖';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',45),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',35),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='猎妖弓'),'weight',20))::jsonb WHERE name = '血蚊王';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵芝'),'weight',45),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',20))::jsonb WHERE name = '火蝎';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵芝孢子'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='游龙刀'),'weight',15))::jsonb WHERE name = '九尾妖狐';

-- Lv 28-35 中级怪物：材料升级、丹药、装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='冰莲种子'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='银蛇枪'),'weight',15))::jsonb WHERE name = '九头蛇';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',45),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵芝孢子'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='灵蛇鞭'),'weight',10))::jsonb WHERE name = '沙暴蜥蜴';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='筑基丹'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='碎星锤'),'weight',15))::jsonb WHERE name = '修罗战魂';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰花种子'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='破风刀'),'weight',10))::jsonb WHERE name = '星尘蝶';

-- Lv 40-50 中高级怪物：高级材料、玉简、中等装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='回春丹'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='玄铁甲'),'weight',15))::jsonb WHERE name = '玄冥龟';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='幽冥铁'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='影刃匕'),'weight',10))::jsonb WHERE name = '深渊蠕虫';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='大还丹'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='朱果种子'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='斩妖刀'),'weight',10))::jsonb WHERE name = '赤焰蛟龙';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='冰封咒玉简'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='聚灵玉佩'),'weight',20))::jsonb WHERE name = '噬心魔';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='幽冥铁'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='太阳真金'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='遁地术玉简'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='猎妖弓'),'weight',15))::jsonb WHERE name = '飞天夜叉';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='火灵石'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='落日弓'),'weight',10))::jsonb WHERE name = '熔岩巨兽';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='虚空结晶'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星辰砂'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='回春术玉简'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='星辉项链'),'weight',15))::jsonb WHERE name = '虚空行者';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='轻身术玉简'),'weight',25),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='七星剑'),'weight',15))::jsonb WHERE name = '剑痴残魂';

-- Lv 55-65 高级怪物：高级材料、玉简、稀有装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九天息壤'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='金钟罩玉简'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='天蚕宝甲'),'weight',15))::jsonb WHERE name = '远古石像鬼';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='太阳真金'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='大还丹'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='幽影匕'),'weight',10))::jsonb WHERE name = '暗影刺客';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',35),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='涅槃丹'),'weight',10),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='大摧山掌玉简'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='逍遥扇'),'weight',10))::jsonb WHERE name = '不死凤凰';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年玄冰'),'weight',40),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='万年寒铁'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='冰封咒玉简'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='乾坤杖'),'weight',10))::jsonb WHERE name = '寒冰女王';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九天息壤'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='千年灵芝孢子'),'weight',25),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='星辉道袍'),'weight',15))::jsonb WHERE name = '万年妖藤';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='血菩提'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='破障丹'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='诛仙剑'),'weight',5),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='碎星霸刀'),'weight',25))::jsonb WHERE name = '修罗王';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='生生造化丹'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九幽花'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='方天画戟'),'weight',15))::jsonb WHERE name = '九幽冥凤';

-- Lv 70-100 终局怪物：传说材料、玉简、丹方、传说装备
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='舍利子'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='御剑术玉简'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='玄武战甲'),'weight',25))::jsonb WHERE name = '星辰守护者';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='虚空结晶'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='金刚不坏玉简'),'weight',20),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='逍遥扇'),'weight',20))::jsonb WHERE name = '吞噬魔';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='凤凰翎'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙血草'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='清风诀玉简'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='龙牙项链'),'weight',15))::jsonb WHERE name = '远古黑龙';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='太阳真金'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='破障丹方'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转金莲种子'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='金刚杵'),'weight',20))::jsonb WHERE name = '远古武神';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='星核碎片'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转金丹'),'weight',5),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='大摧山掌玉简'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='苍穹弓'),'weight',30))::jsonb WHERE name = '天劫雷兽';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='虚空结晶'),'weight',30),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='虚空草'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='筑基丹方'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='混天环'),'weight',15))::jsonb WHERE name = '虚空领主';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='魔血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='破劫丹'),'weight',10),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转还魂丹'),'weight',5),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='镇魂铃'),'weight',35))::jsonb WHERE name = '魔界之主';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道花瓣'),'weight',10),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='御剑术玉简'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='裂天剑'),'weight',35))::jsonb WHERE name = '万剑剑灵';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='悟道丹'),'weight',10),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转金莲种子'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='太极道袍'),'weight',30))::jsonb WHERE name = '混沌巨兽';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='破劫丹'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道花种子'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='雷劫铠甲'),'weight',30))::jsonb WHERE name = '天道化身';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙鳞'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='神血石'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='龙血草'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转金丹'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='诛仙弓'),'weight',30))::jsonb WHERE name = '上古龙神';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道花瓣'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌藤种子'),'weight',10),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='混沌护符'),'weight',30))::jsonb WHERE name = '混沌之眼';
UPDATE xt_monster_template SET drop_table = jsonb_build_array(jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='天道碎片'),'weight',25),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='混沌元晶'),'weight',20),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='九转金丹'),'weight',15),jsonb_build_object('category','item','templateId',(SELECT id FROM xt_item_template WHERE name='破劫丹'),'weight',15),jsonb_build_object('category','equipment','templateId',(SELECT id FROM xt_equipment_template WHERE name='承影剑'),'weight',25))::jsonb WHERE name = '飞升失败者';
