-- 丹药种子数据 (xt_item_template, type=POTION)
INSERT
    INTO
        xt_item_template(
            name,
            TYPE,
            properties,
            tags,
            description
        )
    VALUES(
        '小聚灵丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":100}]}',
        '["pill","exp","entry"]',
        '入门修士服用的基础丹药，蕴含少量灵气，可快速转化为修为。'
    ),
    (
        '聚灵丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":300}]}',
        '["pill","exp","basic"]',
        '标准灵气丹，筑基修士日服十粒不皱眉，练气修士谨慎服用。'
    ),
    (
        '大聚灵丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":800}]}',
        '["pill","exp","intermediate"]',
        '灵气浓郁的丹药，金丹修士方敢直接服用，低阶修士需分次化开。'
    ),
    (
        '天元丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":2000}]}',
        '["pill","exp","advanced"]',
        '以天地元气炼成，一颗蕴含百倍于聚灵丹的灵气，元婴修士的最爱。'
    ),
    (
        '太乙金丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":5000}]}',
        '["pill","exp","epic"]',
        '传说太乙真人传下的丹方，金光流转，化神之下磕此丹犹如开挂。'
    ),
    (
        '九转仙灵丹',
        'POTION',
        '{"effects":[{"type":"exp","amount":15000}]}',
        '["pill","exp","legendary"]',
        '九转方得一颗，据说化神大圆满修士也只见过丹方。'
    ),
    (
        '回春丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":200}]}',
        '["pill","heal","basic"]',
        '草木精华炼制的疗伤丹，服下外伤即刻愈合，内伤仍需静养。'
    ),
    (
        '大还丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":600}]}',
        '["pill","heal","intermediate"]',
        '可续断骨、接经脉的疗伤圣品，光头上仙秘传丹方。'
    ),
    (
        '小还丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":1000}]}',
        '["pill","heal","intermediate"]',
        '丹如其名，小还丹却能大回血，金丹修士行走江湖的标配。'
    ),
    (
        '九转回春丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":2000}]}',
        '["pill","heal","advanced"]',
        '九转炼制的回春丹，只要还有一口气就能拉回来。'
    ),
    (
        '大回春丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":3500}]}',
        '["pill","heal","advanced"]',
        '回春丹的终极强化版，化神大能也要嗑上一颗以备不测。'
    ),
    (
        '小还魂丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":0}]}',
        '["pill","cure","rare"]',
        '以还魂草为主材炼成，可让濒死之人回转一口气，保命神丹。'
    ),
    (
        '大还魂丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":5000}]}',
        '["pill","heal","epic"]',
        '据说能生死人肉白骨，元婴修士也要备一颗防身。'
    ),
    (
        '壮骨丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":10}]}',
        '["pill","stat","str","entry"]',
        '淬炼筋骨，增力十钧，服后筋骨铮鸣，力道倍增。'
    ),
    (
        '金刚散',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"CON","amount":10}]}',
        '["pill","stat","con","entry"]',
        '锤炼皮膜内脏，固本培元，挨打时没那么疼了。'
    ),
    (
        '轻身散',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"AGI","amount":10}]}',
        '["pill","stat","agi","entry"]',
        '身轻如燕，步履如风，服后行走间悄无声息。'
    ),
    (
        '开智丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"WIS","amount":10}]}',
        '["pill","stat","wis","entry"]',
        '开启灵台，悟性大增，往日晦涩的道法豁然贯通。'
    ),
    (
        '龙力丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":30}]}',
        '["pill","stat","str","rare"]',
        '以龙血草为主材，服后力道暴涨。'
    ),
    (
        '虎骨丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":20}]}',
        '["pill","stat","str","basic"]',
        '以虎骨为主材炼制，力道稳步提升，药性温和不易反弹。'
    ),
    (
        '不动明王丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"CON","amount":30}]}',
        '["pill","stat","con","rare"]',
        '如明王端坐不动，筋骨如金刚，打不死的是我。'
    ),
    (
        '玄武甲丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"CON","amount":20}]}',
        '["pill","stat","con","basic"]',
        '以玄武龟甲碎片入药，服后皮糙肉厚扛揍翻倍。'
    ),
    (
        '踏风丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"AGI","amount":30}]}',
        '["pill","stat","agi","rare"]',
        '御风而行，踏虚凌空，金丹以下都看不清你的影子。'
    ),
    (
        '追风丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"AGI","amount":20}]}',
        '["pill","stat","agi","basic"]',
        '服后两腿生风，行走如飞，草上踏叶不留痕。'
    ),
    (
        '大悟道丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"WIS","amount":30}]}',
        '["pill","stat","wis","rare"]',
        '以菩提叶炼成，有人吃了直接顿悟破境——但那是他的机缘。'
    ),
    (
        '玲珑心丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"WIS","amount":20}]}',
        '["pill","stat","wis","basic"]',
        '开启灵台第七窍，虽不至醍醐灌顶也差不太多。'
    ),
    (
        '筑基丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.3}]}',
        '["pill","breakthrough","critical"]',
        '练气修士冲击筑基的关键丹药，一粒难求，黑市炒到天价。'
    ),
    (
        '结丹丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.35}]}',
        '["pill","breakthrough","critical"]',
        '辅助筑基圆满修士凝结金丹，失败率降低三成。'
    ),
    (
        '碎丹丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.25}]}',
        '["pill","breakthrough","intermediate"]',
        '金丹后期碎丹凝婴的辅助丹药，药力温和适合多次尝试。'
    ),
    (
        '化婴丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.4}]}',
        '["pill","breakthrough","epic"]',
        '金丹圆满破碎化婴，从此踏上真正仙途。丹成九转方可得。'
    ),
    (
        '炼神丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.3}]}',
        '["pill","breakthrough","advanced"]',
        '元婴期淬炼元神的秘制丹药，突破化神的关键助力。'
    ),
    (
        '化神丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.5}]}',
        '["pill","breakthrough","legendary"]',
        '元婴圆满冲击化神之用，此丹已成天下绝品，可遇不可求。'
    ),
    (
        '融虚丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.35}]}',
        '["pill","breakthrough","grand"]',
        '化神巅峰融化虚空踏入炼虚的奇丹，所需药材极尽珍稀。'
    ),
    (
        '大乘丹',
        'POTION',
        '{"effects":[{"type":"breakthrough","rate":0.45}]}',
        '["pill","breakthrough","mythic"]',
        '传说以九千年一熟的朱果为主材，大乘修士也未必见过丹方。'
    ),
    (
        '洗髓丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":5},{"type":"stat","statAttr":"CON","amount":5}]}',
        '["pill","special","entry"]',
        '伐毛洗髓，脱胎换骨，入门修士必服的第一粒丹药。'
    ),
    (
        '瞬回丹',
        'POTION',
        '{"effects":[{"type":"hp","amount":1000}]}',
        '["pill","heal","emergency"]',
        '危急时刻服下即可大幅回血，保命良药，行走江湖必备。'
    ),
    (
        '抗性丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":30,"duration_seconds":180}]}',
        '["pill","buff","resist"]',
        '提前服下可抵御部分负面状态，持续三炷香。'
    ),
    (
        '避毒丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":100,"duration_seconds":600}]}',
        '["pill","buff","immune"]',
        '服用后万毒不侵一炷香，深入毒沼之前务必嗑一粒。'
    ),
    (
        '清心丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"speed","amount":30,"duration_seconds":900}]}',
        '["pill","buff","mind"]',
        '祛除心魔、明心见性，渡劫前服之可定心神。'
    ),
    (
        '凝神丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"speed","amount":20,"duration_seconds":600}]}',
        '["pill","buff","mind"]',
        '凝神聚气，一刻钟内法决冷却缩短一半。'
    ),
    (
        '破甲丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"attack","amount":30,"duration_seconds":180}]}',
        '["pill","buff","offensive"]',
        '服后攻击附带破甲效果，啃不动的硬茬也变得酥脆。'
    ),
    (
        '易容丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"speed","amount":50,"duration_seconds":3600}]}',
        '["pill","buff","utility"]',
        '可改换容貌一个时辰，但灵气气息难以完全遮掩。'
    ),
    (
        '定颜丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":100,"duration_seconds":31536000}]}',
        '["pill","special","cosmetic"]',
        '永葆青春的驻颜丹，女修界最畅销丹药没有之一。'
    ),
    (
        '辟谷丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":100,"duration_seconds":86400}]}',
        '["pill","buff","utility"]',
        '服一粒可一日不食，闭关修炼必备，虽无五谷之香却胜在便捷。'
    ),
    (
        '延寿丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":10,"duration_seconds":31536000}]}',
        '["pill","special","lifespan","rare"]',
        '一颗延寿十年，凡人视若仙丹，修士视为保底续命之物。'
    ),
    (
        '天劫丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"tribulation_resist","amount":25,"duration_seconds":3600}]}',
        '["pill","buff","tribulation","epic"]',
        '渡劫专用，可抵御二成半天雷之力，但别指望它能扛第九道。'
    ),
    (
        '火灵丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"attack","amount":40,"duration_seconds":1800}]}',
        '["pill","buff","fire","uncommon"]',
        '引火灵气炼成，服后攻伐间附带灼烧之意。火修士战斗前必备。'
    ),
    (
        '寒玉丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"attack","amount":40,"duration_seconds":1800}]}',
        '["pill","buff","ice","uncommon"]',
        '以千年寒玉为引，服后寒气透骨、每次出手都如冰锥刺体。'
    ),
    (
        '雷罡丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"attack","amount":50,"duration_seconds":1200}]}',
        '["pill","buff","thunder","rare"]',
        '天雷淬炼的刚猛丹药，服后攻击如雷霆炸裂，但事后浑身酥麻。'
    ),
    (
        '木灵丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":40,"duration_seconds":1800}]}',
        '["pill","buff","wood","uncommon"]',
        '草木精华凝聚成丹，服后皮韧如古木，耐打翻倍。'
    ),
    (
        '暴击丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"attack","amount":60,"duration_seconds":900}]}',
        '["pill","buff","combat","rare"]',
        '短时间内攻击暴涨的猛丹，出手如电招招要命。'
    ),
    (
        '闪避丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"speed","amount":40,"duration_seconds":1800}]}',
        '["pill","buff","combat","uncommon"]',
        '身法灵丹，服后身形如落叶飘忽，敌人连衣角都摸不到。'
    ),
    (
        '双倍丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"speed","amount":60,"duration_seconds":1800}]}',
        '["pill","buff","utility","rare"]',
        '服后出手速度快到出现残影，一盏茶内攻速猛增。'
    ),
    (
        '探宝丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"defense","amount":30,"duration_seconds":3600}]}',
        '["pill","buff","utility","uncommon"]',
        '服后周身灵气壁垒增强，可安全深入凶险之地采集珍材。'
    ),
    (
        '炼体丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":15}]}',
        '["pill","stat","str","intermediate"]',
        '比壮骨丹更上一层的炼体丹，力道稳步提升，适合筑基中期修士。'
    ),
    (
        '淬骨丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"CON","amount":15}]}',
        '["pill","stat","con","intermediate"]',
        '骨如金玉筋似蛟龙，淬骨之后更抗揍。'
    ),
    (
        '疾风丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"AGI","amount":15}]}',
        '["pill","stat","agi","intermediate"]',
        '服后脚下生风行步如飞，追风丹的亲民版。'
    ),
    (
        '启灵丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"WIS","amount":15}]}',
        '["pill","stat","wis","intermediate"]',
        '灵台渐明悟性渐开，配合菩提树下打坐效果更佳。'
    ),
    (
        '破境丹',
        'POTION',
        '{"effects":[{"type":"stat","statAttr":"STR","amount":8},{"type":"stat","statAttr":"CON","amount":8},{"type":"stat","statAttr":"AGI","amount":8},{"type":"stat","statAttr":"WIS","amount":8}]}',
        '["pill","special","rare"]',
        '四象之力齐加身，攻防速智全面提升，突破前的底气也多了一分。'
    ),
    (
        '避雷丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"tribulation_resist","amount":15,"duration_seconds":3600}]}',
        '["pill","buff","tribulation","basic"]',
        '服下后周身灵气化为薄薄雷盾，可在雷劫中减免一成半伤害。入门修士的渡劫必备。'
    ),
    (
        '化劫丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"tribulation_resist","amount":40,"duration_seconds":3600}]}',
        '["pill","buff","tribulation","rare"]',
        '以千年雷击木炼成，可将四成雷劫之力化为虚无，金丹以上渡劫常备。'
    ),
    (
        '渡厄金丹',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"tribulation_resist","amount":60,"duration_seconds":3600}]}',
        '["pill","buff","tribulation","legendary"]',
        '渡劫期修士疯抢的至宝，服下后能将六成天雷卸去，一颗难求如凤毛麟角。'
    ),
    (
        '招雷散',
        'POTION',
        '{"effects":[{"type":"buff","attribute":"tribulation_resist","amount":-40,"duration_seconds":3600}]}',
        '["pill","buff","tribulation","rare"]',
        '以引雷木为主材的奇异丹药，服下后雷劫威力暴涨四成，但渡过则有额外修为奖励。高风险高回报。'
    );
