-- 灵兽卵种子数据 (xt_item_template, type=BEAST_EGG)
-- production_items 中的 template_id 和 skill_pool 中的 skill_id 用 name 字符串代替
INSERT INTO xt_item_template (name, type, properties, tags, description) VALUES
('灵猫卵',   'BEAST_EGG', '{"grow_time":24,"production_items":[{"weight":70,"name":"灵芝"},{"weight":30,"name":"何首乌"}],"skill_pool":{"innate_skills":[{"skill_name":"金刚体","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"轻身术","weight":50}]}}',  '["beast_egg","common","beast"]', '一只黏人的灵猫，会找药草和在你打坐时蹭你。'),
('铁羽鹰卵', 'BEAST_EGG', '{"grow_time":48,"production_items":[{"weight":60,"name":"妖兽皮"},{"weight":40,"name":"兽骨"}],"skill_pool":{"innate_skills":[{"skill_name":"穿杨箭","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"连珠箭","weight":30}]}}',  '["beast_egg","uncommon","flying"]', '展翅三丈的铁羽鹰，不仅是战斗伙伴更是坐骑。'),
('雪狐卵',   'BEAST_EGG', '{"grow_time":36,"production_items":[{"weight":80,"name":"雪莲"},{"weight":20,"name":"冰魄花"}],"skill_pool":{"innate_skills":[{"skill_name":"寒冰掌","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"冰封万里","weight":20}]}}',  '["beast_egg","uncommon","ice"]', '浑身雪白的灵狐，喜欢在雪地里打滚，产出寒属性药材。'),
('火蟾卵',   'BEAST_EGG', '{"grow_time":36,"production_items":[{"weight":70,"name":"地火芝"},{"weight":30,"name":"太阳花"}],"skill_pool":{"innate_skills":[{"skill_name":"烈火掌","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"焚天诀","weight":25}]}}',  '["beast_egg","uncommon","fire"]', '腹部火红的大蟾蜍，看似憨态可掬实则战力超群，专产火属性材料。'),
('青鸾卵',   'BEAST_EGG', '{"grow_time":72,"production_items":[{"weight":50,"name":"凤羽"},{"weight":50,"name":"天心兰"}],"skill_pool":{"innate_skills":[{"skill_name":"清风拂柳","unlock":"tier_1"},{"skill_name":"鹰眼术","unlock":"tier_2"}],"awakening_skills":[{"skill_name":"霓裳扇舞","weight":15}]}}',  '["beast_egg","rare","flying","phoenix"]', '青色的凤凰后裔，优雅而高傲，凤凰血脉使其自带祥瑞之气。'),
('玄武龟卵', 'BEAST_EGG', '{"grow_time":96,"production_items":[{"weight":60,"name":"龙鳞"},{"weight":40,"name":"玄晶"}],"skill_pool":{"innate_skills":[{"skill_name":"铁布衫","unlock":"tier_1"},{"skill_name":"金钟罩","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"万劫不磨","weight":10}]}}',  '["beast_egg","epic","beast","defense"]', '背负龟蛇的玄武后裔，防御无双，据说万年之后可化作一方城池。'),
('乘黄卵',   'BEAST_EGG', '{"grow_time":72,"production_items":[{"weight":50,"name":"龙血草"},{"weight":50,"name":"九天仙草"}],"skill_pool":{"innate_skills":[{"skill_name":"震地锤","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"轰天锤","weight":10}]}}',  '["beast_egg","rare","beast","myth"]', '《山海经》中的神兽，其状如狐，背生角，乘之寿二千。'),
('灵蚕卵',   'BEAST_EGG', '{"grow_time":12,"production_items":[{"weight":100,"name":"灵蚕丝"}],"skill_pool":{"innate_skills":[{"skill_name":"静心诀","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"清风拂柳","weight":5}]}}',   '["beast_egg","common","silk"]', '小小的灵蚕，不打架不惹事，安安静静吐丝就是它最大的贡献。'),
('夔牛卵',   'BEAST_EGG', '{"grow_time":120,"production_items":[{"weight":40,"name":"魂玉碎片"},{"weight":40,"name":"龙鳞"},{"weight":20,"name":"混沌石"}],"skill_pool":{"innate_skills":[{"skill_name":"镇魂钟声","unlock":"tier_1"},{"skill_name":"逆乱阴阳","unlock":"tier_2"}],"awakening_skills":[{"skill_name":"混沌钟","weight":5}]}}',  '["beast_egg","legendary","beast","thunder"]', '上古异兽夔牛，状如牛、苍身无角、一足，出入水则必有风雨，其声如雷。'),
('玉兔卵',   'BEAST_EGG', '{"grow_time":24,"production_items":[{"weight":80,"name":"灵芝孢子"},{"weight":20,"name":"天心兰种子"}],"skill_pool":{"innate_skills":[{"skill_name":"龙象般若功","unlock":"tier_1"}],"awakening_skills":[{"skill_name":"天人感应","weight":30}]}}',  '["beast_egg","common","beast","moon"]', '月宫玉兔的凡间血脉，不仅可爱还能帮你打理灵田，但别让它偷吃你的灵药。'),
('穷奇卵',   'BEAST_EGG', '{"grow_time":168,"production_items":[{"weight":40,"name":"白虎骨"},{"weight":40,"name":"先天庚金"},{"weight":20,"name":"混沌石"}],"skill_pool":{"innate_skills":[{"skill_name":"刑天斧法","unlock":"tier_1"},{"skill_name":"兵主杀伐","unlock":"tier_2"}],"awakening_skills":[{"skill_name":"盘古开天","weight":3}]}}',  '["beast_egg","legendary","beast","evil"]', '上古四凶之一，形似虎而有翼，性情凶暴但认主后忠心不二。');
