-- ============================================================
-- 紫府秘境 (紫府真人飞升前留下的秘境, 金属性)
-- 入口: xt_map_node id=31 (紫府秘境, HIDDEN_ZONE)
-- ============================================================
INSERT
    INTO
        dungeon_template(
            name,
            description,
            map_node_id,
            min_level,
            max_level
        )
    VALUES(
        '紫府秘境',
        '传说紫府真人飞升前留下的秘境，紫色灵气凝聚为液，汇成小溪在秘境中流淌。紫府真人一生精研金系功法，秘境中处处弥漫着锋锐的金气。',
        31,
        5,
        30
    );

DO $$ DECLARE d_id BIGINT;

BEGIN SELECT
    id INTO
        d_id
    FROM
        dungeon_template
    WHERE
        name = '紫府秘境';

-- ==================== 外围 (OUTER) ====================
-- 1. 灵药圃 - GATHER (非战斗采集)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            loot_pool
        )
    VALUES(
        d_id,
        'OUTER',
        '灵药圃',
        'GATHER',
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '灵芝'
                ),
                'weight',
                40,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '血参'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '朱砂'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '龙血草'
                ),
                'weight',
                10,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );

-- 2. 试炼碑 - COMBAT (通道候选)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool,
            is_passage
        )
    VALUES(
        d_id,
        'OUTER',
        '试炼碑',
        'COMBAT',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '铁甲虫'
                ),
                'weight',
                50
            ),
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '山贼'
                ),
                'weight',
                50
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄铁矿石'
                ),
                'weight',
                40,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '小聚灵丹'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '兽骨'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                2
            )
        ),
        TRUE
    );

-- 3. 散修遗居 - SEARCH
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            loot_pool,
            is_passage
        )
    VALUES(
        d_id,
        'OUTER',
        '散修遗居',
        'SEARCH',
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄铁矿石'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '兽骨'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '聚灵丹'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '妖兽皮'
                ),
                'weight',
                10,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '灵雀卵'
                ),
                'weight',
                10,
                'minQty',
                1,
                'maxQty',
                1
            )
        ),
        TRUE
    );

-- ==================== 内围 (INNER) ====================
-- 4. 灵兽巢穴 - COMBAT
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool
        )
    VALUES(
        d_id,
        'INNER',
        '灵兽巢穴',
        'COMBAT',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '猿妖'
                ),
                'weight',
                50
            ),
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '冰狼'
                ),
                'weight',
                50
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '兽骨'
                ),
                'weight',
                35,
                'minQty',
                2,
                'maxQty',
                4
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '妖兽皮'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '大聚灵丹'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );

-- 5. 炼器室 - COMBAT
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool
        )
    VALUES(
        d_id,
        'INNER',
        '炼器室',
        'COMBAT',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '石魔'
                ),
                'weight',
                70
            ),
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '铁甲虫'
                ),
                'weight',
                30
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄铁矿石'
                ),
                'weight',
                30,
                'minQty',
                2,
                'maxQty',
                5
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '寒铁'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                2
            )
        )
    );

-- 6. 残破丹房 - SEARCH
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            loot_pool
        )
    VALUES(
        d_id,
        'INNER',
        '残破丹房',
        'SEARCH',
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '小聚灵丹'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '聚灵丹'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '筑基丹'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '壮骨丹'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '开智丹'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );

-- 7. 藏经阁 - SEARCH
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            loot_pool
        )
    VALUES(
        d_id,
        'INNER',
        '藏经阁',
        'SEARCH',
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '金刚体玉简'
                ),
                'weight',
                35,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '金灵剑气玉简'
                ),
                'weight',
                35,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '霸刀诀玉简'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );

-- 8. 阵法遗址 - COMBAT (通道候选)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool,
            is_passage
        )
    VALUES(
        d_id,
        'INNER',
        '阵法遗址',
        'COMBAT',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '金甲尸'
                ),
                'weight',
                50
            ),
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '石魔'
                ),
                'weight',
                50
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '寒铁'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '天外陨铁'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                1
            )
        ),
        TRUE
    );

-- 9. 守护者·金甲将 - BOSS (击败获得核心令符，通道候选)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool,
            is_passage
        )
    VALUES(
        d_id,
        'INNER',
        '守护者·金甲将',
        'BOSS',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '金甲尸'
                ),
                'weight',
                100
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                40,
                'minQty',
                2,
                'maxQty',
                5
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                35,
                'minQty',
                2,
                'maxQty',
                4
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '大聚灵丹'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '白泽幼卵'
                ),
                'weight',
                10,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '青鸾卵'
                ),
                'weight',
                10,
                'minQty',
                1,
                'maxQty',
                1
            )
        ),
        TRUE
    );

-- ==================== 核心 (CORE) ====================
-- 10. 传承殿 - BOSS
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool
        )
    VALUES(
        d_id,
        'CORE',
        '传承殿',
        'BOSS',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '修罗'
                ),
                'weight',
                100
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                35,
                'minQty',
                3,
                'maxQty',
                6
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '天外陨铁'
                ),
                'weight',
                35,
                'minQty',
                1,
                'maxQty',
                2
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '霸刀诀玉简'
                ),
                'weight',
                30,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );

-- 11. 宗门宝库 - SEARCH (通道候选)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            loot_pool,
            is_passage
        )
    VALUES(
        d_id,
        'CORE',
        '宗门宝库',
        'SEARCH',
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                25,
                'minQty',
                3,
                'maxQty',
                8
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                25,
                'minQty',
                3,
                'maxQty',
                8
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '天外陨铁'
                ),
                'weight',
                20,
                'minQty',
                1,
                'maxQty',
                3
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '大聚灵丹'
                ),
                'weight',
                15,
                'minQty',
                2,
                'maxQty',
                5
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '筑基丹'
                ),
                'weight',
                15,
                'minQty',
                1,
                'maxQty',
                3
            )
        ),
        TRUE
    );

-- 12. 镇守BOSS·紫府真魂 - BOSS (最终BOSS, 击败通关)
INSERT
    INTO
        dungeon_poi_config(
            dungeon_id,
            area,
            name,
            poi_type,
            monster_pool,
            loot_pool
        )
    VALUES(
        d_id,
        'CORE',
        '镇守BOSS·紫府真魂',
        'BOSS',
        jsonb_build_array(
            jsonb_build_object(
                'monsterTemplateId',
                (
                    SELECT
                        id
                    FROM
                        xt_monster_template
                    WHERE
                        name = '修罗'
                ),
                'weight',
                100
            )
        ),
        jsonb_build_array(
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '魂玉碎片'
                ),
                'weight',
                30,
                'minQty',
                5,
                'maxQty',
                10
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '玄晶'
                ),
                'weight',
                25,
                'minQty',
                5,
                'maxQty',
                10
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '天外陨铁'
                ),
                'weight',
                25,
                'minQty',
                1,
                'maxQty',
                5
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '大聚灵丹'
                ),
                'weight',
                20,
                'minQty',
                3,
                'maxQty',
                8
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '九色鹿卵'
                ),
                'weight',
                8,
                'minQty',
                1,
                'maxQty',
                1
            ),
            jsonb_build_object(
                'type',
                'ITEM',
                'templateId',
                (
                    SELECT
                        id
                    FROM
                        xt_item_template
                    WHERE
                        name = '金翼雕卵'
                ),
                'weight',
                8,
                'minQty',
                1,
                'maxQty',
                1
            )
        )
    );
END $$;
