-- 种子数据 (xt_item_template, type=SEED)
INSERT INTO xt_item_template (name, type, properties, tags, description) VALUES
('灵芝孢子',   'SEED', jsonb_build_object('grow_time', 24, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='灵芝')))),  '["seed","herb","common"]', '灵芝的孢子粉，撒入灵田可长出灵芝。农桑之道，贵在耐心。'),
('血参种子',   'SEED', jsonb_build_object('grow_time', 36, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='血参')))),  '["seed","herb","uncommon"]', '血参的种子，三年结籽一次，种出的血参年份可期。'),
('雪莲种子',   'SEED', jsonb_build_object('grow_time', 48, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='雪莲')))),  '["seed","herb","ice","uncommon"]', '天山雪莲的种子，需寒性灵田方可种植，成熟后入药极佳。'),
('地火芝孢子', 'SEED', jsonb_build_object('grow_time', 24, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='地火芝')))),  '["seed","herb","fire","uncommon"]', '地火芝的孢子，生于岩浆裂隙，种在火脉灵田产量翻倍。'),
('紫丹参苗',   'SEED', jsonb_build_object('grow_time', 30, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='紫丹参')))),  '["seed","herb","healing","uncommon"]', '紫丹参的幼苗，种下后一月可收，是炼制疗伤丹药的基础。'),
('天心兰种子', 'SEED', jsonb_build_object('grow_time', 72, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='天心兰')))),  '["seed","herb","wisdom","rare"]', '天心兰的种子，花开放时能让人心旷神怡，助益悟道修行。'),
('太阳花种子', 'SEED', jsonb_build_object('grow_time', 48, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='太阳花')))),  '["seed","herb","fire","uncommon"]', '向阳而生的灵花，日照越足长势越旺，花瓣可入药。'),
('菩提树种',   'SEED', jsonb_build_object('grow_time', 168, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='菩提叶')))), '["seed","tree","wisdom","epic"]', '菩提古树的树种，种下后需等待整整七天才破土，叶可助人顿悟。'),
('何首乌苗',   'SEED', jsonb_build_object('grow_time', 72, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='何首乌')))),  '["seed","herb","uncommon"]', '何首乌的幼苗，种植需三年，但药效随年份倍增。'),
('龙血草种子', 'SEED', jsonb_build_object('grow_time', 96, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='龙血草')))),  '["seed","herb","dragon","rare"]', '龙血草的种子，据说只有龙气浸润之地才能发芽。'),
('幽冥花种子', 'SEED', jsonb_build_object('grow_time', 96, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='幽冥花')))),  '["seed","herb","dark","rare"]', '幽冥花的种子，需阴气充沛的灵田，只在子夜发芽。'),
('还魂草种子', 'SEED', jsonb_build_object('grow_time', 120, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='还魂草')))), '["seed","herb","cure","rare"]', '还魂草的种子，生长极慢，但一株可救一命。'),
('冰魄花种子', 'SEED', jsonb_build_object('grow_time', 96, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='冰魄花')))),  '["seed","herb","ice","rare"]', '冰魄花的种子，离开寒潭即枯，种植条件苛刻。'),
('星月花种子', 'SEED', jsonb_build_object('grow_time', 48, 'reharvest', 0, 'production_items', jsonb_build_array(jsonb_build_object('weight', 1, 'template_id', (SELECT id FROM xt_item_template WHERE name='星月花')))),  '["seed","herb","star","uncommon"]', '星月花的种子，吸收夜间星月精华生长，花开如星河璀璨。');
