-- =====================================================================
-- 旅行事件种子数据 — "低频高风险高回报"
-- 设计规则：
--   1. 每个 ActivityEvent.params.effects 必须覆盖 EventType.description 中所有 {{key}} 模板变量
--   2. 空效果事件必须补齐效果（叙事暗示了 reward 就不能什么都不给）
--   3. 高风险：部分事件带 TAKE_DAMAGE_PERCENT（5-15% 最大生命）
--   4. 高回报：使用 ADD_EXP_PERCENT（2-8% 升级修为）代替固定 ADD_EXP
--   5. TravelCompleter.rollSubEvents 基础触发概率 0.30，命运修正后 0.21~0.39
-- =====================================================================

INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        1,
        'travel_ambush_beast',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    30
                )
            )
        )
    ),
    (
        'TRAVEL',
        1,
        'travel_broken_cart',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        )
                    ),
                    'chance',
                    0.3
                )
            )
        )
    ),
    (
        'TRAVEL',
        1,
        'travel_friendly_merchant',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        2,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_FLAT',
                    'amount',
                    15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    20
                )
            )
        )
    ),
    (
        'TRAVEL',
        2,
        'travel_injured_cultivator',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    50
                )
            )
        )
    ),
    (
        'TRAVEL',
        3,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        4,
        'travel_spring_of_spirit',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 100}]}'
    ),
    (
        'TRAVEL',
        4,
        'travel_broken_cart',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '兽骨'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        5,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        6,
        'travel_friendly_merchant',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    30
                )
            )
        )
    ),
    (
        'TRAVEL',
        6,
        'travel_wandering_elder',
        'NUMERIC',
        5,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":20}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        7,
        'travel_treasure_map',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        )
                    ),
                    'chance',
                    0.6
                )
            )
        )
    ),
    (
        'TRAVEL',
        8,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.02
                )
            )
        )
    ),
    (
        'TRAVEL',
        10,
        'travel_bandit_roadblock',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    50
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    40
                )
            )
        )
    ),
    (
        'TRAVEL',
        11,
        'travel_friendly_merchant',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        )
                    ),
                    'chance',
                    0.6
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    60
                )
            )
        )
    ),
    (
        'TRAVEL',
        11,
        'travel_wandering_elder',
        'NUMERIC',
        6,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":45}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        17,
        'travel_strange_fog',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        24,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 500}]}'
    ),
    (
        'TRAVEL',
        27,
        'travel_fallen_star',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        30,
        'travel_fallen_star',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        35,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '魂玉碎片'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        39,
        'travel_fallen_star',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        42,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    -- =================================================================
    -- 以下为之前缺失旅行事件的地图新增
    -- =================================================================
    (
        'TRAVEL',
        12,
        'travel_ambush_beast',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        12,
        'travel_spring_of_spirit',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 300}]}'
    ),
    (
        'TRAVEL',
        13,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    100
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    60
                )
            )
        )
    ),
    (
        'TRAVEL',
        13,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    3
                )
            )
        )
    ),
    (
        'TRAVEL',
        15,
        'travel_injured_cultivator',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    100
                )
            )
        )
    ),
    (
        'TRAVEL',
        15,
        'travel_friendly_merchant',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        )
                    ),
                    'chance',
                    0.5
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    50
                )
            )
        )
    ),
    (
        'TRAVEL',
        16,
        'travel_rainstorm',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        16,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '朱砂'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'TRAVEL',
        19,
        'travel_bandit_roadblock',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    150
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        19,
        'travel_strange_fog',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        20,
        'travel_wandering_elder',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        20,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 500}]}'
    ),
    (
        'TRAVEL',
        22,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                )
            )
        )
    ),
    (
        'TRAVEL',
        22,
        'travel_broken_cart',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        23,
        'travel_spring_of_spirit',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    600
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.02
                )
            )
        )
    ),
    (
        'TRAVEL',
        23,
        'travel_friendly_merchant',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        25,
        'travel_strange_fog',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    150
                )
            )
        )
    ),
    (
        'TRAVEL',
        25,
        'travel_ambush_beast',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        32,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        32,
        'travel_fallen_star',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    2
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        34,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    ),
    (
        'TRAVEL',
        36,
        'travel_ambush_beast',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        36,
        'travel_bandit_roadblock',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    300
                )
            )
        )
    ),
    (
        'TRAVEL',
        37,
        'travel_strange_fog',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        37,
        'travel_rainstorm',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                )
            )
        )
    ),
    (
        'TRAVEL',
        38,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    ),
    (
        'TRAVEL',
        38,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 1500}]}'
    ),
    (
        'TRAVEL',
        43,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'TRAVEL',
        43,
        'travel_treasure_map',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    2
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    );

-- =================================================================
-- 隐藏事件
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        14,
        'travel_wandering_elder',
        'NUMERIC',
        8,
        TRUE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":50}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '大悟道丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        28,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        TRUE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '九转金莲'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_bandit_roadblock',
        'NUMERIC',
        10,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '刑天斧法'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                )
            )
        )
    );

-- =================================================================
-- 新增旅行事件（第二批）
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        4,
        'travel_hermit_cave',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP_PERCENT", "percent": 0.04}]}'
    ),
    (
        'TRAVEL',
        4,
        'travel_ancient_monument',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄晶'
                        )
                    ),
                    'chance',
                    0.4
                )
            )
        )
    ),
    (
        'TRAVEL',
        7,
        'travel_wildfire',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.04
                )
            )
        )
    ),
    (
        'TRAVEL',
        9,
        'travel_mysterious_peddler',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '地火芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵木'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        9,
        'travel_beast_migration',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    100
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    100
                )
            )
        )
    ),
    (
        'TRAVEL',
        14,
        'travel_mysterious_voice',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '魂玉碎片'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'TRAVEL',
        18,
        'travel_flood_path',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    120
                )
            )
        )
    ),
    (
        'TRAVEL',
        18,
        'travel_mysterious_peddler',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '寒铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '朱砂'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.5
                )
            )
        )
    ),
    (
        'TRAVEL',
        21,
        'travel_hermit_cave',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝'
                    ),
                    'count',
                    3
                )
            )
        )
    ),
    (
        'TRAVEL',
        21,
        'travel_beast_migration',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    250
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        24,
        'travel_cloud_pavilion',
        'NUMERIC',
        6,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":40}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.07
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'TRAVEL',
        28,
        'travel_ancient_monument',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                ),
                jsonb_build_object(
                    'type',
                    'HEAL_FLAT',
                    'amount',
                    300
                )
            )
        )
    ),
    (
        'TRAVEL',
        31,
        'travel_mysterious_voice',
        'NUMERIC',
        8,
        FALSE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '魂玉碎片'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_beast_migration',
        'NUMERIC',
        18,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.12
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    ),
    (
        'TRAVEL',
        40,
        'travel_wildfire',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.10
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    300
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    ),
    (
        'TRAVEL',
        41,
        'travel_cloud_pavilion',
        'NUMERIC',
        8,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":60}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '天外陨铁'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '紫金砂'
                        )
                    ),
                    'chance',
                    0.6
                )
            )
        )
    ),
    (
        'TRAVEL',
        44,
        'travel_hermit_cave',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.07
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'TRAVEL',
        44,
        'travel_beast_migration',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.15
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    600
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.06
                )
            )
        )
    );

-- =================================================================
-- 旅行商人 — CHOICE 交互选择事件（玉简/锻造图/兽卵/装备）
-- 设计：低概率触发（weight 3-5），JS生成随机价格叙事文本
-- =================================================================
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        6,
        'travel_curious_merchant',
        'CHOICE',
        4,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一本泛黄的剑道玉简——商人咧嘴一笑：「万剑归宗，我只卖八百灵石，你小子要是识货就下手吧。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '万剑归宗玉简'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚温热的卵——商人压低声音：「火蟾卵，三百年难得一见，今天只要五百灵石，错过就没了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '火蟾卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你摇摇头转身要走，商人叹了口气：「眼力不错但不贪心——送你点路上的盘缠吧。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            50
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_EXP',
                            'amount',
                            30
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        14,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一张质地奇异的锻造图纸——商人递过来给你细看：「青冥剑图，我花了半辈子才到手，你给一千灵石它就是你的了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '青冥剑图'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一颗隐隐透出白光的卵——商人环顾四周后才说：「雪狐卵——要不是缺灵石我绝对不会卖，只要三百灵石。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '雪狐卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '「不买不卖，交个朋友。」商人见你无意购买，反而笑了笑，随手扔了一小袋灵石过来。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            100
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        22,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一柄剑身青黑如冥渊的长剑——商人眯着眼：「纯钧剑，刚从古洞里挖出来的真品，一千五百灵石你拿去，这可是剑修的好伙伴。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'CREATE_EQUIPMENT',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_equipment_template
                                WHERE
                                    name = '纯钧剑'
                            )
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚碧光流转的蛇卵——商人小心翼翼托在掌心：「碧鳞蛇卵，别看现在还小，孵出来以后比你还能打。给你算六百灵石好了。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '碧鳞蛇卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你拱手婉拒，商人若有所思地看了你一眼：「也罢，能抵住诱惑的人不多了——拿着。」递来一枚丹药。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '聚灵丹'
                            ),
                            'count',
                            2
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            80
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        33,
        'travel_curious_merchant',
        'CHOICE',
        3,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一枚散发着圣道气息的玉简——商人神色凝重：「轩辕剑法——这是我从上古战场里九死一生带出来的。非有缘人不卖，你我相逢便是有缘——三千灵石，不二价。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '轩辕剑法玉简'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚青色光华流转的巨卵——商人用颤抖的手掀开绒布：「青鸾卵——我走遍九州只找到这么一枚。本来要价一万灵石，但我看你骨骼精奇，收你三千就好。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '青鸾卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你抱拳拒绝。商人反倒欣慰地点点头：「懂得拒绝是修道的上乘境界——这份心性就当赔你的眼缘了。」抛来数块灵石和一颗天元丹。',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            300
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '天元丹'
                            ),
                            'count',
                            1
                        )
                    )
                )
            )
        )
    ),
    (
        'TRAVEL',
        43,
        'travel_curious_merchant',
        'CHOICE',
        2,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'options',
            jsonb_build_array(
                jsonb_build_object(
                    'key',
                    'A',
                    'text',
                    '一把刀身刻满龙雀纹的宝刀——商人抚刀叹道：「龙雀刀，传家之宝，今日迫不得已才卖的。五千灵石，一分也不能少。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'CREATE_EQUIPMENT',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_equipment_template
                                WHERE
                                    name = '龙雀刀'
                            )
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'B',
                    'text',
                    '一枚金光璀璨的雕卵——商人压低声音：「金翼雕卵——整个大陆不超过三枚。我本来不卖，但我欠你师父一个人情。收你两千灵石意思一下。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '金翼雕卵'
                            ),
                            'count',
                            1
                        )
                    )
                ),
                jsonb_build_object(
                    'key',
                    'C',
                    'text',
                    '你摇头推辞。商人收起货物，临别前深深看你一眼：「能见宝物而不动心，你将来造化不小——这颗太乙金丹，算我和你交个朋友。」',
                    'effects',
                    jsonb_build_array(
                        jsonb_build_object(
                            'type',
                            'ADD_ITEM',
                            'template_id',
                            (
                                SELECT
                                    id
                                FROM
                                    xt_item_template
                                WHERE
                                    name = '太乙金丹'
                            ),
                            'count',
                            1
                        ),
                        jsonb_build_object(
                            'type',
                            'ADD_SPIRIT_STONES',
                            'amount',
                            500
                        )
                    )
                )
            )
        )
    );
