-- 新增法决种子数据 (冰/雷/风元素 + 低阶通用技能)
INSERT INTO xt_skill(name, description, skill_type, effects, binding_type, cooldown_seconds, require_wis, level_requirement, tags) VALUES
('霜刃', '凝聚寒霜于利刃之上，斩出冰寒一击。', 'ACTIVE', '[{"type":"DAMAGE","value":150},{"type":"SLOW","value":20,"duration":2}]', 'ELEMENT', 10, NULL, 1, '["ice","damage","beginner"]'),
('冰锥术', '凝聚冰锥刺穿敌人，有概率冻结目标。', 'ACTIVE', '[{"type":"DAMAGE","value":200},{"type":"FREEZE","value":30,"duration":1}]', 'ELEMENT', 20, 10, 10, '["ice","damage","freeze","basic"]'),
('玄冰甲', '凝聚玄冰护体，攻击者受冰寒反噬。', 'ACTIVE', '[{"type":"DEFENSE_BUFF","value":25,"duration":3},{"type":"REFLECT","value":10,"duration":3}]', 'ELEMENT', 30, 15, 20, '["ice","defense_buff","reflect","basic"]'),
('千里冰封', '大范围冰封之术，冻结方圆百丈。', 'ACTIVE', '[{"type":"AOE_DAMAGE","value":140},{"type":"FREEZE","value":35,"duration":1}]', 'ELEMENT', 70, 45, 40, '["ice","aoe","freeze","advanced"]'),
('绝对零度', '极寒之术，将温度降至极限。', 'ACTIVE', '[{"type":"DAMAGE","value":280},{"type":"FREEZE","value":50,"duration":2}]', 'ELEMENT', 90, 55, 60, '["ice","freeze","epic"]'),
('引雷诀', '引天雷入体，化为己用。', 'ACTIVE', '[{"type":"DAMAGE","value":160},{"type":"STUN","value":15,"duration":1}]', 'ELEMENT', 10, NULL, 1, '["thunder","damage","beginner"]'),
('雷甲', '以雷电护体，攻击者受雷击反噬。', 'ACTIVE', '[{"type":"DEFENSE_BUFF","value":20,"duration":3},{"type":"COUNTER","value":20,"duration":3}]', 'ELEMENT', 30, 15, 20, '["thunder","defense_buff","basic"]'),
('连环雷', '连续雷击，每击皆引天雷。', 'ACTIVE', '[{"type":"MULTI_HIT","value":70,"hits":3}]', 'ELEMENT', 40, 20, 20, '["thunder","multi_hit","intermediate"]'),
('天雷破', '天雷贯体而下，威力惊人。', 'ACTIVE', '[{"type":"DAMAGE","value":250},{"type":"STUN","value":40,"duration":1}]', 'ELEMENT', 60, 35, 40, '["thunder","stun","advanced"]'),
('九天神雷', '引九天之雷降世，雷罚万物。', 'ACTIVE', '[{"type":"AOE_DAMAGE","value":180},{"type":"STUN","value":30,"duration":1}]', 'ELEMENT', 100, 60, 70, '["thunder","aoe","stun","epic"]'),
('风刃', '以灵力凝成风刃，快如闪电。', 'ACTIVE', '[{"type":"DAMAGE","value":140},{"type":"SPEED_BUFF","value":10,"duration":2}]', 'ELEMENT', 10, NULL, 1, '["wind","damage","beginner"]'),
('旋风盾', '凝聚旋风化为护盾，可偏转攻击。', 'ACTIVE', '[{"type":"DEFENSE_BUFF","value":20,"duration":3},{"type":"DODGE","value":20,"duration":3}]', 'ELEMENT', 30, 15, 20, '["wind","defense_buff","dodge","basic"]'),
('风卷残云', '狂风席卷，摧枯拉朽。', 'ACTIVE', '[{"type":"AOE_DAMAGE","value":120},{"type":"SLOW","value":20,"duration":2}]', 'ELEMENT', 40, 20, 20, '["wind","aoe","slow","intermediate"]'),
('裂风斩', '以风为刃，切割万物。', 'ACTIVE', '[{"type":"DAMAGE","value":240},{"type":"ARMOR_BREAK","value":30,"duration":2}]', 'ELEMENT', 60, 35, 40, '["wind","armor_break","advanced"]'),
('天风灭世', '天风降世，万物寂灭。', 'ACTIVE', '[{"type":"AOE_DAMAGE","value":170},{"type":"SILENCE","value":40,"duration":2}]', 'ELEMENT', 100, 60, 70, '["wind","aoe","silence","epic"]'),
('吐纳术', '吐故纳新，增益灵力护体。', 'PASSIVE', '[{"type":"RESIST_BUFF","value":5}]', 'NONE', 0, NULL, 1, '["passive","defense","beginner"]'),
('灵力护体', '灵力充盈于体魄，根基更厚。', 'PASSIVE', '[{"type":"HP_BUFF","value":8}]', 'NONE', 0, NULL, 1, '["passive","hp","beginner"]'),
('聚灵诀', '汇聚天地灵气为己用。', 'PASSIVE', '[{"type":"ATTACK_BUFF","value":5}]', 'NONE', 0, NULL, 1, '["passive","attack","beginner"]'),
('疾风步', '身法如风，来去无踪。', 'PASSIVE', '[{"type":"SPEED_BUFF","value":12},{"type":"DODGE","value":5}]', 'NONE', 0, 10, 10, '["passive","speed","dodge","basic"]'),
('铁布衫', '横练功夫，皮如铁布。', 'PASSIVE', '[{"type":"DEFENSE_BUFF","value":15}]', 'NONE', 0, NULL, 10, '["passive","defense","basic"]'),
('破甲劲', '内劲穿透护甲，直伤本体。', 'ACTIVE', '[{"type":"DAMAGE","value":180},{"type":"ARMOR_BREAK","value":25,"duration":2}]', 'NONE', 20, 10, 10, '["damage","armor_break","basic"]'),
('回春术', '灵力化为生机，治愈伤势。', 'ACTIVE', '[{"type":"HEAL","value":60,"scale":"WIS"},{"type":"CLEANSE","value":1}]', 'NONE', 20, 15, 10, '["heal","cleanse","basic"]'),
('定身术', '以灵力定住敌人，使其无法行动。', 'ACTIVE', '[{"type":"STUN","value":40,"duration":1},{"type":"SLOW","value":20,"duration":2}]', 'NONE', 40, 25, 20, '["control","stun","intermediate"]'),
('吸星大法', '吸取敌人灵力为己用。', 'ACTIVE', '[{"type":"DAMAGE","value":160},{"type":"LIFESTEAL","value":15}]', 'NONE', 30, 20, 20, '["damage","lifesteal","intermediate"]'),
('金蝉脱壳', '濒死之际脱壳保命。', 'PASSIVE', '[{"type":"SURVIVE_LETHAL","value":20}]', 'NONE', 0, 20, 20, '["passive","survival","intermediate"]');
