-- 材料种子数据 (xt_item_template, type=MATERIAL)
-- properties 存储锻材三性: RIGIDITY(刚/硬度), TOUGHNESS(韧/延展), SPIRIT(灵/灵气蕴含度)
INSERT INTO xt_item_template (name, type, properties, tags, description) VALUES
('玄铁矿石',   'MATERIAL', '{"RIGIDITY":8,"TOUGHNESS":3,"SPIRIT":1}', '["ore","metal","craft","common"]', '天地间最基础的灵矿，蕴含微弱灵气，是初入仙途者炼器首选。'),
('寒铁',       'MATERIAL', '{"RIGIDITY":10,"TOUGHNESS":4,"SPIRIT":2}', '["ore","metal","craft","ice","uncommon"]', '产自极北冰原的千年寒铁，质地冰凉，锻造刀剑可带寒芒。'),
('赤铜矿',     'MATERIAL', '{"RIGIDITY":9,"TOUGHNESS":5,"SPIRIT":2}', '["ore","metal","craft","fire","uncommon"]', '熔岩山脉深处的铜矿，自带火气，锤击时火星四溅。'),
('天外陨铁',   'MATERIAL', '{"RIGIDITY":15,"TOUGHNESS":7,"SPIRIT":4}', '["ore","metal","craft","rare"]', '天外飞星陨落后所化，暗含星辰之力，是炼制上品法器的核心材料。'),
('玄晶',       'MATERIAL', '{"RIGIDITY":5,"TOUGHNESS":3,"SPIRIT":12}', '["ore","crystal","craft","rare"]', '矿脉核心凝结的透明晶石，可灌注大量灵气，元婴修士亦视若珍宝。'),
('紫金砂',     'MATERIAL', '{"RIGIDITY":6,"TOUGHNESS":8,"SPIRIT":5}', '["ore","craft","supplement","rare"]', '河床深处淘出的紫色砂金，炼制法器时加入少许可大幅提升品质。'),
('魂玉碎片',   'MATERIAL', '{"RIGIDITY":3,"TOUGHNESS":2,"SPIRIT":15}', '["ore","soul","craft","epic"]', '远古修士神魂凝聚而成的玉质碎片，触摸时有微弱的意志波动。'),
('灵木',       'MATERIAL', '{"RIGIDITY":3,"TOUGHNESS":6,"SPIRIT":2}', '["wood","craft","common"]', '灵脉附近生长的百年灵木，质地坚韧，是制符炼器的木材基础。'),
('千年灵木',   'MATERIAL', '{"RIGIDITY":7,"TOUGHNESS":10,"SPIRIT":6}', '["wood","craft","rare"]', '历经千年灵气浸润的灵木，纹理如玉，炼器师梦寐以求的木材。'),
('兽骨',       'MATERIAL', '{"RIGIDITY":6,"TOUGHNESS":4,"SPIRIT":1}', '["bone","craft","common"]', '妖兽陨落后的遗留骨架，骨骼中仍残存微弱妖力。'),
('妖兽皮',     'MATERIAL', '{"RIGIDITY":2,"TOUGHNESS":8,"SPIRIT":1}', '["leather","craft","common"]', '猎杀妖兽剥取的完整皮毛，刀枪不入，是制甲之上选。'),
('灵蚕丝',     'MATERIAL', '{"RIGIDITY":1,"TOUGHNESS":9,"SPIRIT":4}', '["silk","craft","uncommon"]', '灵蚕吐出的银白蚕丝，轻盈通透却坚韧无比，用以织造法袍。'),
('地脉精华',   'MATERIAL', '{"RIGIDITY":0,"TOUGHNESS":0,"SPIRIT":18}', '["essence","craft","epic"]', '大地深处凝聚的精华，呈现琥珀色液态，是炼制进化石的主材。'),
('龙鳞',       'MATERIAL', '{"RIGIDITY":20,"TOUGHNESS":18,"SPIRIT":10}', '["scale","craft","dragon","legendary"]', '真龙蜕变所遗的一片龙鳞，刀枪不入水火不侵，传说级炼器材料。'),
('凤羽',       'MATERIAL', '{"RIGIDITY":15,"TOUGHNESS":8,"SPIRIT":15}', '["feather","craft","phoenix","legendary"]', '凤凰涅槃时掉落的一根尾羽，火光流转，蕴含重生之力。'),
('混沌石',     'MATERIAL', '{"RIGIDITY":25,"TOUGHNESS":25,"SPIRIT":25}', '["ore","craft","chaos","mythic"]', '混沌初开时便存在的原初之石，内部似有宇宙生灭，古往今来仅存数块。'),
('朱砂',       'MATERIAL', '{"RIGIDITY":1,"TOUGHNESS":1,"SPIRIT":5}', '["mineral","alchemy","common"]', '丹砂研磨而成的细粉，炼丹时用以调和药性，品质纯正则丹成率大增。'),
('月华露',     'MATERIAL', '{"RIGIDITY":0,"TOUGHNESS":0,"SPIRIT":8}', '["essence","alchemy","uncommon"]', '月圆之夜采集的月光凝露，炼丹时滴入数滴可提升丹药灵性。'),
('白虎骨',     'MATERIAL', '{"RIGIDITY":18,"TOUGHNESS":14,"SPIRIT":6}', '["bone","craft","beast","epic"]', '西方白虎的真骨，蕴含着杀伐之气，锻造成器威力无穷。'),
('先天庚金',   'MATERIAL', '{"RIGIDITY":22,"TOUGHNESS":10,"SPIRIT":8}', '["metal","craft","origin","epic"]', '先天五行中金行本源所化的庚金，天下金器之祖。'),
('九幽冥铁',   'MATERIAL', '{"RIGIDITY":16,"TOUGHNESS":12,"SPIRIT":7}', '["ore","metal","craft","dark","epic"]', '幽冥地底万丈深处淬炼的玄铁，阴气逼人，触之如坠冰窟。'),
('天雷竹',     'MATERIAL', '{"RIGIDITY":5,"TOUGHNESS":8,"SPIRIT":10}', '["wood","craft","thunder","rare"]', '被天雷劈中后不死的灵竹，竹身含雷纹，法器掺入可添雷击之威。'),
('万载玄冰',   'MATERIAL', '{"RIGIDITY":12,"TOUGHNESS":4,"SPIRIT":8}', '["ice","craft","rare"]', '极北冰眼万年不化的玄冰核心，三尺之内呵气成冰。'),
('太阳真金',   'MATERIAL', '{"RIGIDITY":24,"TOUGHNESS":15,"SPIRIT":12}', '["metal","craft","fire","legendary"]', '太阳星核脱落的一小块神金，炽热无比，非化神修为不得触碰。'),
('虚空石',     'MATERIAL', '{"RIGIDITY":2,"TOUGHNESS":2,"SPIRIT":16}', '["ore","craft","space","rare"]', '空间裂缝中浮出的透明石头，内含芥子世界，储物法宝的核心。');
