-- 地灵形态种子数据 (spirit_form)
-- 各有3-5个喜欢/讨厌的 tag
INSERT
    INTO
        spirit_form(
            name,
            description,
            liked_tags,
            disliked_tags
        )
    VALUES(
        '小狐妖',
        '毛茸茸的狐耳少女，会偷偷往你的仓库里塞药草——但别让她发现你在吃狐狸肉。',
        '["herb","beast","healing","seed","silk"]',
        '["demon","poison","evil","metal","draconic"]'
    ),
    (
        '剑灵',
        '从古剑中苏醒的剑魂，不怎么说话但看剑的眼神很专注。',
        '["sword","blade","attack","ore","metal"]',
        '["poison","dark","chaos","staff","herb"]'
    ),
    (
        '老槐树精',
        '不知活了多少年的槐树精，说话慢悠悠的，喜欢讲过去的故事——虽然讲了也记不住。',
        '["wood","herb","seed","tree","earth"]',
        '["fire","poison","metal","chaos","demon"]'
    ),
    (
        '石狮子',
        '镇宅石狮成精，威严中带着几分憨态，喜欢收集亮晶晶的小物件。',
        '["defense","ore","craft","metal","fortune"]',
        '["water","ice","flying","silk","poison"]'
    ),
    (
        '书灵',
        '从一个千年古籍中化出的灵体，知识渊博但稍微有点书呆子气。',
        '["wisdom","skill_jade","water","silk","star"]',
        '["fire","beast","chaos","demon","warrior"]'
    ),
    (
        '蝴蝶仙',
        '一只修炼千年的蝴蝶，振翅时花气飘散，喜欢花花草草。',
        '["flower","herb","seed","silk","healing"]',
        '["fire","metal","poison","dark","evil"]'
    ),
    (
        '黑白无常',
        '一个活泼的小无常，负责帮忙管理仓库的"灵魂"，喜欢有死气的东西。',
        '["dark","soul","evil","ghost","cure"]',
        '["yang","fire","sun","wisdom","healing"]'
    ),
    (
        '金蟾',
        '三足金蟾，蹲在灵石堆上就不动了，喜欢金光闪闪的东西。',
        '["metal","ore","fortune","gem","gold"]',
        '["water","ice","herb","seed","wood"]'
    ),
    (
        '童子',
        '穿着红肚兜的仙童，天真烂漫，对丹药有着天生的嗅觉。',
        '["pill","potion","fire","yang","sweet"]',
        '["dark","poison","evil","bitter","soul"]'
    ),
    (
        '麒麟',
        '祥瑞之兽麒麟的分灵，不愿看到杀戮，喜欢和平。',
        '["auspicious","healing","wisdom","herb","defense"]',
        '["warrior","evil","chaos","demon","attack"]'
    ),
    (
        '饕餮',
        '上古凶兽饕餮之灵，食欲旺盛，对各类灵材有着近乎偏执的渴求。',
        '["beast_egg","pill","potion","food","sweet"]',
        '["poison","bitter","soul","evil","undead"]'
    ),
    (
        '白泽',
        '博学多闻的白泽之灵，有什么问题都可以问它。',
        '["wisdom","knowledge","star","skill_jade","water"]',
        '["ignorance","chaos","evil","poison","warrior"]'
    ),
    (
        '花妖',
        '花丛中化出的小妖灵，喜欢漂亮的东西和香喷喷的药草。',
        '["flower","herb","silk","beauty","sweet"]',
        '["ore","metal","bone","leather","dark"]'
    ),
    (
        '矿灵',
        '矿洞里的小精灵，对矿石有天然的亲和力，会帮主人找到好矿脉。',
        '["ore","metal","gem","craft","earth"]',
        '["wood","herb","silk","flower","water"]'
    ),
    (
        '铁匠灵',
        '生前是天下第一铁匠的残魂，看到好材料就忍不住想打铁。',
        '["ore","metal","craft","forge","fire"]',
        '["silk","herb","flower","poison","water"]'
    ),
    (
        '酿酒仙',
        '只关心酿酒这件事的仙灵，每天都醉醺醺的，但酿出的仙酿天下无双。',
        '["fruit","herb","water","sweet","wood"]',
        '["metal","ore","bone","dryness","warrior"]'
    ),
    (
        '灯灵',
        '一盏千年长明灯化出的灵体，散发着温暖的光。',
        '["light","fire","wisdom","peace","healing"]',
        '["dark","evil","ghost","undead","chaos"]'
    ),
    (
        '天狗',
        '传说中的天狗之灵，每到月食就特别兴奋（其实是饿了想吃月亮）。',
        '["moon","dark","beast","flying","star"]',
        '["sun","fire","metal","attack","loud"]'
    ),
    (
        '云灵',
        '一朵云成精了，软绵绵的像棉花糖，喜欢晒太阳变胖再下雨变瘦。',
        '["water","flying","sky","peace","weather"]',
        '["fire","dryness","metal","ore","underground"]'
    ),
    (
        '风灵',
        '一阵风成精了，来无影去无踪，最喜欢吹乱你的符纸然后咯咯笑。',
        '["flying","wind","speed","sky","freedom"]',
        '["earth","ore","defense","stillness","metal"]'
    ),
    (
        '河童',
        '虽然叫河童但更像个水塘里的小霸王，头顶的圆盘永远盛着水。',
        '["water","fish","herb","cucumber","peace"]',
        '["fire","dryness","metal","sword","attack"]'
    ),
    (
        '天禄',
        '辟邪纳财的瑞兽天禄之灵，能为主人带来好运。',
        '["fortune","auspicious","metal","gem","healing"]',
        '["misfortune","evil","curse","chaos","poverty"]'
    ),
    (
        '精卫',
        '精卫填海的执念化灵，小小一只但叼石头的毅力让人动容。',
        '["sea","water","bird","stone","persistence"]',
        '["giveup","evil","chaos","lazy","demon"]'
    ),
    (
        '山童',
        '小山神座下的童子灵体，憨态可掬，把整座山当自家后院。',
        '["earth","stone","ore","mountain","craft"]',
        '["water","flood","sea","fish","flying"]'
    ),
    (
        '灶君',
        '灶神的童子灵体，喜欢往你的丹炉里偷加一把火。',
        '["fire","cook","pill","food","warm"]',
        '["raw","cold","ice","water","bitter"]'
    ),
    (
        '白猿',
        '山中白猿成精，会模仿人打铁炼丹——但成品质量令人担忧。',
        '["beast","mimic","wood","fruit","skill_jade"]',
        '["metal","forge","craft","fire","serious"]'
    ),
    (
        '青鸟',
        '西王母座下的三青鸟之一的分灵，负责传递仙界的消息。',
        '["flying","bird","message","wisdom","phoenix"]',
        '["dark","evil","silence","ignorance","demon"]'
    ),

    -- ========== 新增形态 ==========

    -- 禽兽部
    (
        '捣药兔',
        '月宫中偷跑下来的玉兔，三瓣嘴永远在嚼着什么药材，偶尔会吐出成型的丹丸。',
        '["herb","pill","moon","skill_jade","sweet"]',
        '["fire","beast","metal","warrior","blood"]'
    ),
    (
        '夜瞳',
        '一只黑猫蹲在暗处，瞳孔里倒映着星辰运转的轨迹，据说能看穿一切虚妄。',
        '["moon","dark","silk","star","dagger"]',
        '["water","loud","warrior","metal","light"]'
    ),
    (
        '丹顶翁',
        '活了不知多少年的丹顶鹤，总是单脚站着闭目养神，开口就是"老夫当年……"。',
        '["flying","bird","wisdom","herb","star"]',
        '["beast","poison","dark","metal","chaos"]'
    ),
    (
        '锦鳞君',
        '一尾五彩锦鲤化形，自称"纵横江湖八百载"，其实只在灵泉池子里游过。',
        '["water","fish","fortune","gem","beauty"]',
        '["fire","dryness","metal","beast","flying"]'
    ),
    (
        '偷桃儿',
        '一只毛手毛脚的猴子，总在偷吃灵果时被抓现行，然后眨巴着眼睛装可怜。',
        '["fruit","beast","wood","seed","herb"]',
        '["metal","forge","ore","serious","stillness"]'
    ),
    (
        '衔芝客',
        '一头角上缠着灵气的白鹿，口中永远衔着一株灵芝，却从不自己吃掉。',
        '["wood","herb","healing","beast","earth"]',
        '["metal","fire","chaos","demon","evil"]'
    ),
    (
        '玄甲公',
        '龟甲上刻着上古卦象的老龟，说话慢到令人抓狂，但每次开口都是箴言。',
        '["defense","water","wisdom","earth","tortoise"]',
        '["fire","noise","speed","chaos","flying"]'
    ),
    (
        '霜翅',
        '一只通体冰蓝的蝴蝶，翅膀所过之处凝出细碎的霜花，美则美矣，冻手。',
        '["ice","flower","beauty","herb","silk"]',
        '["fire","summer","beast","warrior","metal"]'
    ),
    (
        '金睛',
        '一只乌鸦蹲在枝头，金色的眼珠骨碌碌转着，仿佛什么都瞒不过它。',
        '["flying","bird","wisdom","metal","moon"]',
        '["dark","evil","ignorance","chaos","water"]'
    ),
    (
        '月影',
        '一头银白色的狼灵，只在月圆之夜凝实身形，平时像一缕青烟飘忽不定。',
        '["moon","dark","beast","speed","star"]',
        '["sun","fire","light","metal","day"]'
    ),
    (
        '玉鸣蝉',
        '一只通体如白玉雕成的蝉，振动翅膀时发出玉石相击般的清响，闻者心安。',
        '["wood","summer","peace","healing","wisdom"]',
        '["winter","cold","ice","noise","water"]'
    ),
    (
        '青羽雀',
        '一只圆滚滚的小雀，羽毛是最纯粹的天青色，喜欢站在灵田边啄刚冒头的嫩芽。',
        '["flying","bird","seed","herb","spring"]',
        '["dark","poison","evil","metal","ore"]'
    ),
    (
        '赤练',
        '一条筷子长的小蛇，通体赤红如烧红的铁线，看着吓人其实温顺得很。',
        '["fire","beast","herb","yang","speed"]',
        '["ice","water","winter","defense","stillness"]'
    ),
    (
        '紫电貂',
        '一道紫色闪电般的小貂，安静时缩成一团毛球，跑起来连剑修都追不上。',
        '["speed","beast","flying","wind","thunder"]',
        '["stillness","earth","defense","water","tortoise"]'
    ),
    (
        '白额客',
        '一头小白虎不知从哪座山头溜达下来，看着威风凛凛其实还没断奶。',
        '["beast","attack","metal","warrior","blade"]',
        '["plant","herb","water","healing","silk"]'
    ),

    -- 草木部
    (
        '参童子',
        '一个白白胖胖的娃娃，头顶三片绿叶，动不动就往土里钻，说是在"修炼遁地术"。',
        '["herb","earth","wood","healing","seed"]',
        '["fire","metal","beast","dryness","poison"]'
    ),
    (
        '雪莲子',
        '一朵雪莲中诞生的灵体，周身萦绕着凛冽的寒气，靠近三尺便如坠冰窟。',
        '["ice","herb","water","healing","beauty"]',
        '["fire","summer","beast","chaos","evil"]'
    ),
    (
        '桃夭夭',
        '一株千年桃树的花灵，粉衣粉裙，走到哪里都有花瓣无风自落。',
        '["flower","wood","spring","beauty","sweet"]',
        '["winter","cold","metal","poison","evil"]'
    ),
    (
        '青莲君',
        '端坐于莲台之上的青莲化身，神色淡然，开口便是禅机——虽然多半听不懂。',
        '["flower","water","peace","healing","wisdom"]',
        '["fire","mud","poison","chaos","evil"]'
    ),
    (
        '翠竹翁',
        '一竿老竹弯腰驼背成了精，风吹过时浑身噼啪作响，自称"会骨传导养生术"。',
        '["wood","wind","peace","craft","earth"]',
        '["fire","metal","beast","chaos","demon"]'
    ),
    (
        '牡丹卿',
        '一朵牡丹花中诞生的贵女灵体，每天要用灵露梳妆三遍，嫌弃你种的灵田不够气派。',
        '["flower","beauty","silk","fortune","sweet"]',
        '["mud","beast","ore","metal","poison"]'
    ),
    (
        '桂香儿',
        '一个圆脸小姑娘，满身桂花香，喜欢在秋天收集花瓣酿酒。',
        '["flower","wood","autumn","sweet","food"]',
        '["summer","beast","metal","poison","evil"]'
    ),
    (
        '寒梅女',
        '一株雪中红梅化灵，性情清冷寡言，但会在凛冬为你折一枝花色最好的。',
        '["flower","wood","winter","ice","beauty"]',
        '["summer","fire","beast","chaos","evil"]'
    ),
    (
        '幽兰客',
        '生于幽谷的兰草化灵，喜静不喜闹，经常捧着书一看就是一整天。',
        '["flower","herb","peace","wisdom","beauty"]',
        '["noise","chaos","beast","metal","fire"]'
    ),
    (
        '秋菊翁',
        '篱笆下的老菊花成了精，爱喝菊花茶，爱晒太阳，自称"养老界第一人"。',
        '["flower","herb","autumn","peace","healing"]',
        '["summer","beast","metal","chaos","evil"]'
    ),
    (
        '苍松公',
        '一棵千年古松化灵，身姿挺拔如剑，风雪不改其色。',
        '["wood","winter","earth","defense","peace"]',
        '["fire","chaos","beast","summer","evil"]'
    ),
    (
        '柳依依',
        '一株水边垂柳化灵，长发及腰，温柔似水，但被惹急了会用柳条抽人。',
        '["wood","water","peace","silk","herb"]',
        '["fire","metal","beast","warrior","attack"]'
    ),
    (
        '藤儿',
        '一根会走路的藤蔓，喜欢缠着一切温暖的东西——包括你的胳膊和丹炉。',
        '["wood","herb","seed","water","growth"]',
        '["fire","metal","axe","dryness","winter"]'
    ),

    -- 天象部
    (
        '雨童子',
        '一个光脚的小男孩，走到哪里哪里就下毛毛雨，脚下永远跟着一洼清水。',
        '["water","spring","growth","herb","seed"]',
        '["fire","dryness","sun","desert","metal"]'
    ),
    (
        '雪姬',
        '一袭白衣的女子，长发如雪，沉默寡言，但会在你炼丹炉过热时悄悄降下温。',
        '["ice","winter","water","beauty","peace"]',
        '["fire","summer","sun","beast","chaos"]'
    ),
    (
        '雾娘',
        '晨雾中诞生的灵体，身形容貌永远朦朦胧胧，说话也像隔着一层纱。',
        '["water","mystery","peace","herb","flying"]',
        '["fire","sun","metal","ore","warrior"]'
    ),
    (
        '虹娘',
        '雨后彩虹化灵，七色衣裙流光溢彩，性格活泼得像一道小闪电。',
        '["light","beauty","water","flying","star"]',
        '["dark","evil","metal","ore","bone"]'
    ),
    (
        '露珠儿',
        '清晨第一滴露水化灵，晶莹剔透，性子安静，在阳光下会闪闪发光。',
        '["water","herb","healing","beauty","dawn"]',
        '["fire","sun","metal","beast","dryness"]'
    ),
    (
        '泉先生',
        '一眼灵泉中诞生的老成灵体，性情温和，滔滔不绝地讲"当年这泉眼是如何如何"。',
        '["water","healing","earth","peace","growth"]',
        '["fire","dryness","chaos","evil","metal"]'
    ),
    (
        '溪丫头',
        '山涧溪流化灵，蹦蹦跳跳哼着歌，一会儿不停，把石头都磨圆了。',
        '["water","music","peace","growth","flying"]',
        '["fire","stillness","metal","ore","dryness"]'
    ),
    (
        '霞姑',
        '晚霞中诞生的灵体，披着橙红与紫金色的光芒，每天最开心的是日落时分。',
        '["light","flying","beauty","sun","peace"]',
        '["dark","evil","metal","beast","water"]'
    ),
    (
        '岚君',
        '山谷间的雾气化形，一身青白衣袍若隐若现，最喜欢把整座福地罩在云遮雾绕中。',
        '["water","flying","mystery","peace","wood"]',
        '["fire","sun","metal","warrior","loud"]'
    ),
    (
        '霜降',
        '深秋第一场霜化灵，不言不语，但所过之处叶片都镶上了一层银边。',
        '["ice","autumn","water","beauty","peace"]',
        '["fire","summer","sun","beast","growth"]'
    ),

    -- 器物部
    (
        '竹笛生',
        '一支青竹笛化灵，一副书生打扮，吹出的曲子能让灵植加速生长。',
        '["wood","music","peace","herb","growth"]',
        '["metal","noise","beast","chaos","fire"]'
    ),
    (
        '玉箫客',
        '一管古玉箫化灵，青衫落拓，月下独奏时连灵兽都会安静下来聆听。',
        '["wood","music","peace","moon","wisdom"]',
        '["noise","loud","beast","chaos","fire"]'
    ),
    (
        '紫金葫',
        '一个紫金色的葫芦成了精，能把灵气都吸进去再慢慢吐出来，自称"灵气净化器"。',
        '["herb","potion","wood","craft","storage"]',
        '["metal","ore","beast","warrior","fire"]'
    ),
    (
        '水墨君',
        '一幅未干的水墨画成了精，能在墙上、地上、甚至你脸上即兴作画。',
        '["wisdom","beauty","peace","craft","mystery"]',
        '["beast","metal","ore","fire","chaos"]'
    ),
    (
        '小丹炉',
        '一个巴掌大的三足小丹炉，整天蹦蹦跳跳地追着你喊"炼一炉嘛炼一炉嘛"。',
        '["pill","potion","fire","craft","metal"]',
        '["water","ice","herb","wood","raw"]'
    ),
    (
        '青瓷盏',
        '一只天青色的瓷盏化灵，温润如玉，只喝灵泉水泡的茶，劣茶入盏会皱眉。',
        '["water","peace","craft","herb","beauty"]',
        '["metal","ore","beast","warrior","fire"]'
    ),
    (
        '油纸伞',
        '一把老油纸伞成了精，伞面上画着烟雨江南，下雨天撑开就能听见隐约的评弹声。',
        '["water","silk","craft","wood","beauty"]',
        '["fire","sun","dryness","metal","beast"]'
    ),
    (
        '碧玉簪',
        '一根碧玉簪化灵，身姿纤细修长，说话直来直去，从不在背后说人闲话。',
        '["beauty","silk","gem","craft","defense"]',
        '["warrior","beast","metal","ore","chaos"]'
    ),
    (
        '沧浪珠',
        '一颗深海中孕育的明珠化灵，内有潮汐声，靠近它就能闻到海风的味道。',
        '["water","gem","light","beauty","star"]',
        '["fire","metal","beast","ore","earth"]'
    ),
    (
        '古玉珮',
        '一块布满沁色的古玉化灵，温润内敛，挂在哪里就能保哪里一方平安。',
        '["defense","fortune","beauty","peace","auspicious"]',
        '["evil","chaos","demon","dark","poison"]'
    ),
    (
        '松烟墨',
        '一方徽墨化灵，满身松烟香气，最喜欢在空白的纸上龙飞凤舞。',
        '["wisdom","craft","skill_jade","ink","beauty"]',
        '["beast","chaos","noise","warrior","fire"]'
    ),
    (
        '老算盘',
        '一把包了浆的老算盘成了精，噼里啪啦打得飞快，连灵石利息都要算到小数点后三位。',
        '["craft","wisdom","fortune","metal","wood"]',
        '["chaos","beast","herb","flower","water"]'
    ),

    -- 奇趣部
    (
        '绣球娘',
        '一个大红绣球成了精，每天都在蹦蹦跳跳，最喜欢被人抛起来再接住。',
        '["silk","beauty","fortune","auspicious","craft"]',
        '["metal","ore","beast","warrior","fire"]'
    ),
    (
        '老蒲扇',
        '一把豁了边的蒲扇成了精，夏天呼啦呼啦扇风，冬天被塞在角落也不抱怨。',
        '["summer","wind","peace","wood","craft"]',
        '["winter","metal","beast","water","chaos"]'
    ),
    (
        '茶宠儿',
        '一只被茶水养了几十年的紫砂金蟾茶宠化灵，浑身茶香，离了茶汤就犯蔫。',
        '["water","peace","craft","herb","warm"]',
        '["metal","ore","beast","warrior","noise"]'
    ),
    (
        '白玉拂尘',
        '一柄白玉为柄、银丝为尾的拂尘化灵，轻轻一挥便能扫去萦绕的浊气。',
        '["healing","peace","wisdom","light","craft"]',
        '["dark","evil","chaos","poison","beast"]'
    ),
    (
        '酒葫芦',
        '一个不知道装了多少年灵酒的老葫芦，走路摇摇晃晃，说话带着三分醉意。',
        '["wine","fruit","sweet","herb","water"]',
        '["metal","ore","dryness","warrior","beast"]'
    ),
    (
        '红灯笼',
        '一盏大红宫灯成了精，天一黑就自动点亮，把福地照得暖融融的。',
        '["light","fire","festival","warm","beauty"]',
        '["dark","evil","water","ice","ghost"]'
    ),
    (
        '残局',
        '一局下到一半的残棋化灵，每天都在自言自语"这步不该这么走……"。',
        '["wisdom","strategy","peace","knowledge","water"]',
        '["chaos","beast","noise","demon","attack"]'
    ),
    (
        '旧蒲团',
        '一个被修士坐了上百年的蒲团化灵，软绵绵的，谁坐上去都会不知不觉入定。',
        '["peace","wisdom","healing","wood","earth"]',
        '["noise","chaos","beast","warrior","fire"]'
    ),
    (
        '半卷书',
        '一册残破的古籍化灵，内容不全所以说话说一半留一半，急死个人。',
        '["wisdom","skill_jade","knowledge","mystery","water"]',
        '["fire","beast","chaos","demon","warrior"]'
    ),
    (
        '断弦琴',
        '一张断了一根弦的古琴化灵，弹出的曲子略带哀伤，但意外地好听。',
        '["wood","music","peace","beauty","moon"]',
        '["metal","noise","chaos","demon","warrior"]'
    );
