-- DUNGEON 活动事件种子 — 绑定到紫府秘境 (dungeon_template id=1)
INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            params
        )
    VALUES(
        'DUNGEON',
        1,
        'dungeon_trap_triggered',
        'NUMERIC',
        15,
        FALSE,
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'TAKE_DAMAGE_PERCENT',
                    'amount',
                    0.08
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.02
                )
            )
        )
    ),
    (
        'DUNGEON',
        1,
        'dungeon_treasure_found',
        'NUMERIC',
        12,
        FALSE,
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄晶'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '天外陨铁'
                        )
                    ),
                    'chance',
                    0.4
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    80
                )
            )
        )
    ),
    (
        'DUNGEON',
        1,
        'dungeon_lore_discovery',
        'NUMERIC',
        10,
        FALSE,
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.03
                )
            )
        )
    ),
    (
        'DUNGEON',
        1,
        'dungeon_secret_chamber',
        'NUMERIC',
        3,
        TRUE,
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '魂玉碎片'
                    ),
                    'count',
                    2
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                ),
                jsonb_build_object(
                    'type',
                    'ADD_EXP_PERCENT',
                    'percent',
                    0.05
                )
            )
        )
    );
