INSERT
    INTO
        xt_event_type(
            activity_type,
            code,
            name,
            description
        )
    VALUES(
        'TRAVEL',
        'travel_ambush_beast',
        '突遇妖兽',
        '赶路途中突然遭遇妖兽袭击，不得不停下来应对。'
    ),
    (
        'TRAVEL',
        'travel_broken_cart',
        '路边破车',
        '路边有一辆废弃的马车，里面或许有什么值钱的东西。'
    ),
    (
        'TRAVEL',
        'travel_rainstorm',
        '暴雨阻路',
        '一场突如其来的大暴雨让你寸步难行，只能暂避。'
    ),
    (
        'TRAVEL',
        'travel_friendly_merchant',
        '路遇商队',
        '一支友善的商队邀请你同行，可能会分享一些消息和物资。'
    ),
    (
        'TRAVEL',
        'travel_injured_cultivator',
        '受伤修士',
        '路边倒着一位受伤的修士，帮他就可能在日后得报。'
    ),
    (
        'TRAVEL',
        'travel_wandering_elder',
        '途中遇仙',
        '一位白发白须的老者坐在路边石头上打盹——不，他不是凡人。'
    ),
    (
        'TRAVEL',
        'travel_treasure_map',
        '藏宝图碎片',
        '风吹来一张发黄的纸头——看起来像古董藏宝图的一角。'
    ),
    (
        'TRAVEL',
        'travel_bridge_collapse',
        '桥塌了',
        '你正要过桥结果桥塌了——修仙界也有豆腐渣工程。'
    ),
    (
        'TRAVEL',
        'travel_bandit_roadblock',
        '路匪拦路',
        '一伙不知天高地厚的路匪拦住了去去路——你可是修士哎。'
    ),
    (
        'TRAVEL',
        'travel_strange_fog',
        '奇雾迷踪',
        '突然起了大雾伸手不见五指，雾中似乎还有东西在移动。'
    ),
    (
        'TRAVEL',
        'travel_fallen_star',
        '陨星坠地',
        '一颗流星在你前方不远处坠落了——赶去看看有没有陨铁。'
    ),
    (
        'TRAVEL',
        'travel_spring_of_spirit',
        '灵泉偶遇',
        '路边突然出现一汪灵气四溢的泉水，看起来可以喝。'
    );
