INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'BOUNTY_SIDE',
        1,
        'bounty_clue_found',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    80
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    30
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        5,
        'bounty_monster_interference',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    50
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        10,
        'bounty_extra_target',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    150
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    60
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        15,
        'bounty_hidden_cache',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '聚灵丹'
                    ),
                    'count',
                    3
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    100
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        20,
        'bounty_rival_hunter',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    200
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    80
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        25,
        'bounty_witness_arrives',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    100
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '兽骨'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        40,
        'bounty_clue_found',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    150
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        50,
        'bounty_monster_interference',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    300
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    150
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        60,
        'bounty_cultivation_boost',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        70,
        'bounty_extra_target',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    400
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    200
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        80,
        'bounty_hidden_cache',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝'
                    ),
                    'count',
                    2
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        120,
        'bounty_rival_hunter',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    600
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    300
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        150,
        'bounty_witness_arrives',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    1000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    500
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        200,
        'bounty_cultivation_boost',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    800
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        250,
        'bounty_clue_found',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        300,
        'bounty_monster_interference',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    400
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        350,
        'bounty_extra_target',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    1200
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    600
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        400,
        'bounty_cultivation_boost',
        'NUMERIC',
        5,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    10000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    5000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '大悟道丹'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '青鸾卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天人感应玉简'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        6,
        'bounty_hidden_cache',
        'NUMERIC',
        6,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    1500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '小聚灵丹'
                    ),
                    'count',
                    3
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        20,
        'bounty_extra_target',
        'NUMERIC',
        6,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '灵芝妖卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '青木诀玉简'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        51,
        'bounty_ancient_secret',
        'NUMERIC',
        5,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    800
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '冰魄花'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '雪狐卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '聚灵丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        91,
        'bounty_fateful_encounter',
        'NUMERIC',
        5,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    3000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    1500
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '朱砂'
                    ),
                    'count',
                    3
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '火蟾卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '大聚灵丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        101,
        'bounty_cultivation_boost',
        'NUMERIC',
        5,
        TRUE,
        'STAT_THRESHOLD',
        jsonb_build_object(
            'stat',
            'WIS',
            'min',
            45
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    5000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '碧鳞蛇卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '水镜术玉简'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        165,
        'bounty_spirit_revelation',
        'NUMERIC',
        5,
        TRUE,
        'STAT_THRESHOLD',
        jsonb_build_object(
            'stat',
            'WIS',
            'min',
            55
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    8000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    3000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '白泽卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '太乙金丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        191,
        'bounty_ancient_secret',
        'NUMERIC',
        5,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '轩辕剑法'
            )
        ),
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    10000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    5000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '轩辕剑法玉简'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '九转仙灵丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'BOUNTY_SIDE',
        247,
        'bounty_extra_target',
        'NUMERIC',
        5,
        TRUE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_EXP',
                    'amount',
                    4000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_SPIRIT_STONES',
                    'amount',
                    2000
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '金翼雕卵'
                    ),
                    'count',
                    1
                ),
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '龙力丹'
                    ),
                    'count',
                    1
                )
            )
        )
    );
