INSERT
    INTO
        xt_event_type(
            activity_type,
            code,
            name,
            description
        )
    VALUES(
        'TRAVEL',
        'travel_ambush_beast',
        '突遇妖兽',
        '赶路途中突然遭遇妖兽袭击，不得不停下来应对。'
    ),
    (
        'TRAVEL',
        'travel_broken_cart',
        '路边破车',
        '路边有一辆废弃的马车，里面或许有什么值钱的东西。'
    ),
    (
        'TRAVEL',
        'travel_rainstorm',
        '暴雨阻路',
        '一场突如其来的大暴雨让你寸步难行，只能暂避。'
    ),
    (
        'TRAVEL',
        'travel_friendly_merchant',
        '路遇商队',
        '一支友善的商队邀请你同行，可能会分享一些消息和物资。'
    ),
    (
        'TRAVEL',
        'travel_injured_cultivator',
        '受伤修士',
        '路边倒着一位受伤的修士，帮他就可能在日后得报。'
    ),
    (
        'TRAVEL',
        'travel_wandering_elder',
        '途中遇仙',
        '一位白发白须的老者坐在路边石头上打盹——不，他不是凡人。'
    ),
    (
        'TRAVEL',
        'travel_treasure_map',
        '藏宝图碎片',
        '风吹来一张发黄的纸头——看起来像古董藏宝图的一角。'
    ),
    (
        'TRAVEL',
        'travel_bridge_collapse',
        '桥塌了',
        '你正要过桥结果桥塌了——修仙界也有豆腐渣工程。'
    ),
    (
        'TRAVEL',
        'travel_bandit_roadblock',
        '路匪拦路',
        '一伙不知天高地厚的路匪拦住了去去路——你可是修士哎。'
    ),
    (
        'TRAVEL',
        'travel_strange_fog',
        '奇雾迷踪',
        '突然起了大雾伸手不见五指，雾中似乎还有东西在移动。'
    ),
    (
        'TRAVEL',
        'travel_fallen_star',
        '陨星坠地',
        '一颗流星在你前方不远处坠落了——赶去看看有没有陨铁。'
    ),
    (
        'TRAVEL',
        'travel_spring_of_spirit',
        '灵泉偶遇',
        '路边突然出现一汪灵气四溢的泉水，看起来可以喝。'
    ),
    (
        'TRAVEL',
        'travel_hermit_cave',
        '隐士洞穴',
        '路旁藤蔓遮掩的崖壁上隐隐露出一道裂缝，里面似乎别有洞天。'
    ),
    (
        'TRAVEL',
        'travel_mysterious_voice',
        '神秘呼唤',
        '不知从何处传来一声悠远的呼唤，似有若无但直透神魂——不像是幻听。'
    ),
    (
        'TRAVEL',
        'travel_wildfire',
        '山林野火',
        '前方山林浓烟滚滚来势汹汹，要从这边绕过去吗？'
    ),
    (
        'TRAVEL',
        'travel_ancient_monument',
        '古碑遗迹',
        '路边杂草丛中立有一块残碑，碑文虽已模糊但残存笔意中隐约透着非凡之力。'
    ),
    (
        'TRAVEL',
        'travel_flood_path',
        '洪水阻路',
        '连日暴雨导致山洪暴发冲垮了官道，放眼望去一片泥泞。'
    ),
    (
        'TRAVEL',
        'travel_cloud_pavilion',
        '云中楼阁',
        '云开雾散之时天际隐约显出飞檐斗拱，是真实出现在那里的仙阁还是海市蜃楼？'
    ),
    (
        'TRAVEL',
        'travel_mysterious_peddler',
        '神秘小贩',
        '道旁一个不起眼的小摊上摆着几件物什，摆摊的老者闭目养神似睡非睡。'
    ),
    (
        'TRAVEL',
        'travel_beast_migration',
        '兽潮奔袭',
        '远处传来隆隆蹄声——是妖兽迁徙！来不及躲的话只能硬扛了。'
    ),
    (
        'TRAVEL',
        'travel_curious_merchant',
        '旅行商人',
        '一位背着竹篓的旅行商人主动上前搭话：「道友且慢——老朽这篓子里有几件从秘境带出来的好货，你若有兴趣不如看一眼再做决定。」'
    );
