-- 灵兽繁育配方种子数据
INSERT INTO xt_breeding_recipe(required_tags, result_template_id, weight) VALUES
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火鼠卵'),
  100),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '炎雀卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛙卵'),
  100),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火蚁卵'),
  100),
('["beast", "fire", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩蜥卵'),
  100),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '烛蝎卵'),
  100),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火鸦卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '暖貂卵'),
  100),
('["insect", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '焰蝶卵'),
  100),
('["beast", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '火蟾卵'),
  100),
('["beast", "fire", "fur"]',
  (SELECT id FROM xt_item_template WHERE name = '炎狼卵'),
  100),
('["beast", "fire", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鬃马卵'),
  100),
('["insect", "fire", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '火蝎卵'),
  100),
('["flying", "fire", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '烈焰雀卵'),
  100),
('["beast", "fire", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '熔岩龟卵'),
  100),
('["flying", "fire", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '毕方卵'),
  100),
('["beast", "fire", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '祸斗卵'),
  100),
('["beast", "fire", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '九尾火狐卵'),
  100),
('["flying", "fire", "wood", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '朱雀卵'),
  100),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鲤卵'),
  100),
('["beast", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛙卵'),
  100),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '溪蟹卵'),
  100),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '河蚌卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛇精卵'),
  100),
('["beast", "water", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '泽蛙卵'),
  100),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雨燕卵'),
  100),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '溪龟卵'),
  100),
('["spirit", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水母妖卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '碧水蛟卵'),
  100),
('["beast", "water", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '灵龟卵'),
  100),
('["beast", "water", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '潮蟹卵'),
  100),
('["insect", "water", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '水灵蝶卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄水蛇卵'),
  100),
('["beast", "water", "defense", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '千年老龟卵'),
  100),
('["beast", "water", "earth", "defense", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '玄武龟卵'),
  100),
('["beast", "water", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '虎蛟卵'),
  100),
('["beast", "water", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '摸鱼鲲卵'),
  100),
('["beast", "water", "ice", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冥卵'),
  100),
('["plant", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝妖卵'),
  100),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '藤蛇卵'),
  100),
('["plant", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '花精卵'),
  100),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '木灵蝶卵'),
  100),
('["flying", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠鸟卵'),
  100),
('["beast", "wood", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '荷蛙卵'),
  100),
('["spirit", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '柳灵卵'),
  100),
('["beast", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '松鼠灵卵'),
  100),
('["insect", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '竹节虫卵'),
  100),
('["plant", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '花妖卵'),
  100),
('["serpent", "wood", "control"]',
  (SELECT id FROM xt_item_template WHERE name = '古藤蛇卵'),
  100),
('["insect", "wood", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '翠玉蜂卵'),
  100),
('["beast", "wood", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '灵木猿卵'),
  100),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青藤蟒卵'),
  100),
('["insect", "wood", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '碧萝蛛卵'),
  100),
('["beast", "wood", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'),
  100),
('["plant", "wood", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '万年树妖卵'),
  100),
('["plant", "wood", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '建木灵卵'),
  100),
('["dragon", "wood", "water", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '青龙卵'),
  100),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蚁卵'),
  100),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝉卵'),
  100),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蝎卵'),
  100),
('["beast", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁蜥卵'),
  100),
('["insect", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蝶卵'),
  100),
('["insect", "metal", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '铁甲虫卵'),
  100),
('["serpent", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铜蛇卵'),
  100),
('["flying", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼雀卵'),
  100),
('["beast", "metal", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '金龟卵'),
  100),
('["insect", "metal", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '铁背蜈蚣卵'),
  100),
('["flying", "metal", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '金翎鹤卵'),
  100),
('["beast", "metal", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '铜角犀卵'),
  100),
('["flying", "metal", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '铁翼蝠卵'),
  100),
('["beast", "metal", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '金丝猴卵'),
  100),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁爪鹰卵'),
  100),
('["beast", "metal", "wind", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白虎卵'),
  100),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '金翼雕卵'),
  100),
('["beast", "metal", "strength", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '铁骨熊卵'),
  100),
('["beast", "metal", "celestial"]',
  (SELECT id FROM xt_item_template WHERE name = '太白金星兽卵'),
  100),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '土拨鼠卵'),
  100),
('["beast", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛙卵'),
  100),
('["beast", "earth", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '泥鳅精卵'),
  100),
('["insect", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '地蚁卵'),
  100),
('["insect", "earth", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝎卵'),
  100),
('["insect", "earth", "control"]',
  (SELECT id FROM xt_item_template WHERE name = '土蜘蛛卵'),
  100),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛇精卵'),
  100),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '泥龟卵'),
  100),
('["insect", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蝶卵'),
  100),
('["beast", "earth", "defense", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '岩甲犀卵'),
  100),
('["beast", "earth", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '地龙蚓卵'),
  100),
('["spirit", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '石魔像卵'),
  100),
('["beast", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '厚土蟾卵'),
  100),
('["beast", "earth", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '山魈卵'),
  100),
('["beast", "earth", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '穿山甲灵卵'),
  100),
('["beast", "earth", "fire", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '麒麟卵'),
  100),
('["spirit", "earth", "strength", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '石巨人卵'),
  100),
('["serpent", "earth", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '玄岩蟒卵'),
  100),
('["dragon", "earth", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '黄龙卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪兔卵'),
  100),
('["insect", "ice", "silk"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蚕卵'),
  100),
('["insect", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛾卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪鼠卵'),
  100),
('["insect", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '冰蝶卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛙卵'),
  100),
('["flying", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '雪雀卵'),
  100),
('["insect", "ice", "shell"]',
  (SELECT id FROM xt_item_template WHERE name = '冰甲虫卵'),
  100),
('["serpent", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜蛇卵'),
  100),
('["beast", "ice", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '雪狐卵'),
  100),
('["beast", "ice", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '冰角鹿卵'),
  100),
('["beast", "ice"]',
  (SELECT id FROM xt_item_template WHERE name = '霜狼卵'),
  100),
('["flying", "ice", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '冰鹤卵'),
  100),
('["beast", "ice", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '寒蟾卵'),
  100),
('["beast", "ice", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '雪猿卵'),
  100),
('["beast", "ice", "water", "serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '黑水玄蛇卵'),
  100),
('["flying", "ice", "phoenix"]',
  (SELECT id FROM xt_item_template WHERE name = '冰凤卵'),
  100),
('["serpent", "ice", "defense"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰巨蟒卵'),
  100),
('["dragon", "ice", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '玄冰螭龙卵'),
  100),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蛙卵'),
  100),
('["insect", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蝶卵'),
  100),
('["beast", "thunder", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '电鳗卵'),
  100),
('["flying", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '雷雀卵'),
  100),
('["beast", "wind", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '风鼠卵'),
  100),
('["insect", "thunder", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '电蝎卵'),
  100),
('["insect", "thunder", "silk"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蚕卵'),
  100),
('["serpent", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风蛇卵'),
  100),
('["insect", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电萤卵'),
  100),
('["flying", "thunder", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹰卵'),
  100),
('["flying", "wind", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '风灵鹤卵'),
  100),
('["beast", "thunder"]',
  (SELECT id FROM xt_item_template WHERE name = '电狼卵'),
  100),
('["beast", "thunder", "scale"]',
  (SELECT id FROM xt_item_template WHERE name = '雷蜥蜴卵'),
  100),
('["serpent", "wind", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '风翼蛇卵'),
  100),
('["beast", "thunder", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '雷猿卵'),
  100),
('["beast", "thunder", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '夔牛卵'),
  100),
('["beast", "wind", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '飞廉卵'),
  100),
('["flying", "thunder", "wind", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '雷鹏卵'),
  100),
('["dragon", "thunder", "wind", "flying", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '应龙卵'),
  100),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '灵雀卵'),
  100),
('["flying", "wind"]',
  (SELECT id FROM xt_item_template WHERE name = '风燕卵'),
  100),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '云鸽卵'),
  100),
('["flying", "wisdom"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹦卵'),
  100),
('["flying", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹭卵'),
  100),
('["flying", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '烟鹤卵'),
  100),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '霞鸠卵'),
  100),
('["flying", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '岚鸦卵'),
  100),
('["flying", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '霓莺卵'),
  100),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '铁羽鹰卵'),
  100),
('["flying", "support"]',
  (SELECT id FROM xt_item_template WHERE name = '比翼鸟卵'),
  100),
('["flying", "wind", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '云鹏卵'),
  100),
('["flying", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵鹤卵'),
  100),
('["flying", "wind", "speed"]',
  (SELECT id FROM xt_item_template WHERE name = '风隼卵'),
  100),
('["flying", "water", "stealth"]',
  (SELECT id FROM xt_item_template WHERE name = '雾鹰卵'),
  100),
('["flying", "phoenix", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '青鸾卵'),
  100),
('["flying", "speed", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '天马卵'),
  100),
('["flying", "metal", "predator"]',
  (SELECT id FROM xt_item_template WHERE name = '金翼雕卵'),
  100),
('["flying", "metal", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '大鹏金翅鸟卵'),
  100),
('["serpent", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '灵蛇卵'),
  100),
('["serpent", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '青蛇卵'),
  100),
('["serpent", "fire"]',
  (SELECT id FROM xt_item_template WHERE name = '赤蛇卵'),
  100),
('["serpent", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '花蟒卵'),
  100),
('["serpent", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '水蛇精卵'),
  100),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '草蛇卵'),
  100),
('["serpent", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '石蛇精卵'),
  100),
('["serpent", "metal"]',
  (SELECT id FROM xt_item_template WHERE name = '金蛇卵'),
  100),
('["serpent"]',
  (SELECT id FROM xt_item_template WHERE name = '墨蛇卵'),
  100),
('["serpent", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '碧鳞蛇卵'),
  100),
('["serpent", "dragon", "water"]',
  (SELECT id FROM xt_item_template WHERE name = '蛟蜥卵'),
  100),
('["serpent", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '蟒精卵'),
  100),
('["serpent", "fire", "scale"]',
  (SELECT id FROM xt_item_template WHERE name = '赤鳞蛇卵'),
  100),
('["serpent", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '角蛇卵'),
  100),
('["serpent", "dragon", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '翠蛟卵'),
  100),
('["dragon", "sword", "beast"]',
  (SELECT id FROM xt_item_template WHERE name = '螭龙卵'),
  100),
('["serpent", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '内卷蛟卵'),
  100),
('["beast", "water", "dragon"]',
  (SELECT id FROM xt_item_template WHERE name = '虎蛟卵'),
  100),
('["dragon", "fire", "light", "myth"]',
  (SELECT id FROM xt_item_template WHERE name = '烛龙卵'),
  100),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '福鼠卵'),
  100),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞兔卵'),
  100),
('["flying", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '祥鸽卵'),
  100),
('["beast", "auspicious", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '吉蛙卵'),
  100),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '灵猫卵'),
  100),
('["insect", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '喜蛛卵'),
  100),
('["insect", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '福蝶卵'),
  100),
('["serpent", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞蛇卵'),
  100),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '懒猴卵'),
  100),
('["beast", "auspicious", "moon"]',
  (SELECT id FROM xt_item_template WHERE name = '玉兔卵'),
  100),
('["beast", "myth", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '乘黄卵'),
  100),
('["beast", "wisdom", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽幼卵'),
  100),
('["flying", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '瑞鹤卵'),
  100),
('["beast", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '吉祥鹿卵'),
  100),
('["plant", "auspicious", "heal"]',
  (SELECT id FROM xt_item_template WHERE name = '灵芝仙卵'),
  100),
('["beast", "wisdom", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '白泽卵'),
  100),
('["beast", "auspicious", "heal", "wood"]',
  (SELECT id FROM xt_item_template WHERE name = '九色鹿卵'),
  100),
('["beast", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '躺平貘卵'),
  100),
('["beast", "earth", "fire", "auspicious"]',
  (SELECT id FROM xt_item_template WHERE name = '麒麟卵'),
  100),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '瘟鼠卵'),
  100),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '毒蛙卵'),
  100),
('["insect", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '邪蛛卵'),
  100),
('["insect", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '魔蛾卵'),
  100),
('["serpent", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '煞蛇卵'),
  100),
('["insect", "evil", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '鬼萤卵'),
  100),
('["insect", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '厄蝎卵'),
  100),
('["flying", "evil", "undead"]',
  (SELECT id FROM xt_item_template WHERE name = '怨蝠卵'),
  100),
('["beast", "evil", "poison"]',
  (SELECT id FROM xt_item_template WHERE name = '瘴蟾卵'),
  100),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇幼卵'),
  100),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮幼卵'),
  100),
('["beast", "evil", "chaos"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌幼卵'),
  100),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌幼卵'),
  100),
('["beast", "evil", "strength"]',
  (SELECT id FROM xt_item_template WHERE name = '猰貐卵'),
  100),
('["spirit", "evil", "chaos"]',
  (SELECT id FROM xt_item_template WHERE name = '浑敦卵'),
  100),
('["beast", "evil", "flying"]',
  (SELECT id FROM xt_item_template WHERE name = '穷奇卵'),
  100),
('["beast", "evil", "gluttony"]',
  (SELECT id FROM xt_item_template WHERE name = '饕餮卵'),
  100),
('["beast", "evil"]',
  (SELECT id FROM xt_item_template WHERE name = '梼杌卵'),
  100),
('["beast", "evil", "chaos", "fire", "earth"]',
  (SELECT id FROM xt_item_template WHERE name = '混沌卵'),
  100);
