INSERT
    INTO
        xt_event_type(
            activity_type,
            code,
            name,
            description
        )
    VALUES(
        'BOUNTY_SIDE',
        'bounty_clue_found',
        '找到悬赏线索',
        '在执行悬赏过程中发现了额外的线索——任务可能比想象的复杂。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_betrayal',
        '委托人的背叛',
        '委托人其实是个骗子——他的真实目的另有隐情。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_extra_target',
        '额外目标出现',
        '悬赏目标之外竟然还有一个副目标，价值也不低——顺手做掉？'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_hidden_cache',
        '发现秘密藏宝',
        '追踪悬赏目标时无意中发现了他们的隐秘藏宝库。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_witness_arrives',
        '目击者登场',
        '一个自称是目击者的NPC出现，带来了关于悬赏目标的新情报。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_rival_hunter',
        '竞争者登场',
        '另一个赏金猎人也盯上了你的目标——看谁先得手。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_monster_interference',
        '妖兽搅局',
        '正追着目标呢突然窜出一只妖兽打乱了局面。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_cultivation_boost',
        '悬赏中的顿悟',
        '在执行悬赏的激烈战斗中竟意外地突破了修为瓶颈。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_ancient_secret',
        '上古秘藏',
        '在你仔细搜查现场时，无意间触动了一个被忽略的机关——轰隆声中，一扇隐藏的石门缓缓打开，露出了一间尘封千年的密室。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_spirit_revelation',
        '灵机一现',
        '正当你准备离开时，天地间的灵气突然出现了异样的波动——冥冥之中似乎有什么在指引你走向一个意想不到的方向。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_fateful_encounter',
        '命运邂逅',
        '一位神秘修士突然出现在你面前，他似乎一直在等你——"你就是接了这个悬赏的人？很好，我有些话要单独对你说……"'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_environmental_insight',
        '天时地利',
        '你敏锐地察觉到周围环境的异常——原来此地暗藏玄机，只有真正用心观察的人才能发现其中的奥妙。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_target_messages',
        '目标传讯',
        '悬赏目标竟主动留下了一段传音——别怕，是你该怕的人来了。跟踪此线索反而获得了一些意外发现。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_local_help',
        '本地义助',
        '一位当地老猎户听闻你在追猎目标，主动提供了地形情报和补给。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_unexpected_delay',
        '意外耽搁',
        '追踪途中中了目标布下的陷阱，耽误了一些时间——好在陷阱中也藏了东西。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_weather_turn',
        '天时骤变',
        '天公不作美，原本追寻多时的悬赏在最好的天气里忽然变故频生，但也带来了新的契机。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_target_cornered',
        '目标穷途',
        '悬赏目标被逼入绝境不打算束手就擒——垂死挣扎虽然凶险但你也不是吃素的。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_mysterious_benefactor',
        '神秘助力',
        '一个戴着斗笠的神秘人悄悄留下了一处藏宝点：这些东西是给你的——不要辜负委托人。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_treasure_trail',
        '追宝线索',
        '盘问目标喽啰得到一条额外线索：他们还在附近埋了一处藏宝。'
    ),
    (
        'BOUNTY_SIDE',
        'bounty_sabotage',
        '克扣报酬',
        '委托人在你执行任务时偷偷篡改了报酬份额——但你还是发现了他留在公告板上的原始约定。'
    );
