-- 福地事件模板种子数据
INSERT INTO fudi_event_template (name, description, effects, selection_weight)
VALUES
('下雨了', '细雨绵绵，灵气充沛',
 '[{"type": "ADD_EXP_PERCENT", "percent": 5}]'::jsonb, 100),
('刮风了', '微风拂过，带来远方的气息',
 '[]'::jsonb, 100),
('迷路的灵兽', '一只迷路的小灵兽闯入了福地',
 '[]'::jsonb, 90),
('灵蝶飞舞', '一群发光的灵蝶在福地中翩翩起舞',
 '[{"type": "ADD_SPIRIT_STONES", "amount": 3}]'::jsonb, 100),
('神秘访客', '一位神秘的修士路过此地',
 '[{"type": "ADD_RANDOM_ITEM", "poolId": "MATERIAL_COMMON"}]'::jsonb, 80),
('灵草枯萎', '一株灵草不知为何突然枯萎了',
 '[]'::jsonb, 90),
('灵兽诞生', '福地中诞生了一只新的小灵兽',
 '[{"type": "ADD_EXP_PERCENT", "percent": 8}]'::jsonb, 80),
('灵气恢复', '福地的灵气自然恢复了一些',
 '[{"type": "HEAL_FLAT", "amount": 30}]'::jsonb, 100),
('回忆旧主', '地灵想起了曾经的主人',
 '[]'::jsonb, 80),
('初遇回忆', '地灵回忆起与你的初次相遇',
 '[]'::jsonb, 80),
('史莱姆恶作剧', '一只小史莱姆偷偷溜进了福地',
 '[]'::jsonb, 70),
('物品失踪', '你发现一件小物品不见了',
 '[]'::jsonb, 70);
