-- 法决玉简种子数据 (xt_item_template, type=SKILL_JADE)
INSERT INTO xt_item_template (name, type, properties, tags, description)
VALUES
('破风斩玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '破风斩')),
  '["skill_jade","blade","damage"]'::jsonb,
  '刀法基础篇，以迅捷之势破开罡风的一斩。'),
('清风剑法玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '清风剑法')),
  '["skill_jade","sword","damage"]'::jsonb,
  '入门剑法，飘逸灵动如清风拂面，实则剑气暗藏。'),
('万剑归宗玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '万剑归宗')),
  '["skill_jade","sword","aoe"]'::jsonb,
  '御剑生万千，归宗化归一。剑修梦寐以求的群杀绝学。'),
('金刚体玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '金刚体')),
  '["skill_jade","passive","defense"]'::jsonb,
  '金刚体法决的玉简，提升防御力，简单粗暴。'),
('轻身术玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '轻身术')),
  '["skill_jade","passive","agi"]'::jsonb,
  '让身体变轻的法术，跑得快跳得高，实战逃命两不误。'),
('蛮牛劲玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '蛮牛劲')),
  '["skill_jade","passive","str"]'::jsonb,
  '模仿蛮牛之力的体术，力大无穷但不是变成牛。'),
('静心诀玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '静心诀')),
  '["skill_jade","passive","wis"]'::jsonb,
  '静中见真境，淡中识本然。增加悟性的基础心法。'),
('烈火掌玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '烈火掌')),
  '["skill_jade","fire","damage"]'::jsonb,
  '聚火气于掌间，催发炽热掌力。火属性法决入门。'),
('寒冰掌玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '寒冰掌')),
  '["skill_jade","water","ice","damage"]'::jsonb,
  '寒气凝于手，触之冻三尺。水属性入门法决。'),
('青木诀玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '青木诀')),
  '["skill_jade","wood","heal"]'::jsonb,
  '引木行生气滋养自身，可恢复伤势。长途历练必备。'),
('金灵剑气玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '金灵剑气')),
  '["skill_jade","metal","damage"]'::jsonb,
  '以金行道韵化为剑气，锋锐不可挡。'),
('霸刀诀玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '霸刀诀')),
  '["skill_jade","blade","damage","armor_break"]'::jsonb,
  '霸道无我的刀法，一刀之下，管你什么甲胄统统劈开。'),
('诛仙剑诀玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '诛仙剑诀')),
  '["skill_jade","sword","execute"]'::jsonb,
  '传闻中可屠仙的剑诀——但也得你修炼到那个境界。'),
('焚天诀玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '焚天诀')),
  '["skill_jade","fire","aoe","dot"]'::jsonb,
  '焚天之火，燎原之势，持续灼烧敌人。'),
('轩辕剑法玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '轩辕剑法')),
  '["skill_jade","sword","legendary"]'::jsonb,
  '相传是黄帝轩辕氏的战剑之法，剑出则万灵俱灭。'),
('霸下真身玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '霸下真身')),
  '["skill_jade","passive","con","legendary"]'::jsonb,
  '龙九子之首霸下的不灭真身，修炼到顶无人能破防。'),
('蟠桃仙术玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '蟠桃仙术')),
  '["skill_jade","heal","legendary"]'::jsonb,
  '以西王母蟠桃仙根所化的疗愈术，生死人肉白骨。'),
('射日弓玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '射日弓')),
  '["skill_jade","bow","execute"]'::jsonb,
  '后羿射日遗留下的箭法奥义，一箭穿九日。'),
('莲华涅槃玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '莲华涅槃')),
  '["skill_jade","heal","defense","legendary"]'::jsonb,
  '莲台涅槃之法，濒死之际可浴火重生一次。'),
('万劫不磨玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '万劫不磨')),
  '["skill_jade","passive","defense","epic"]'::jsonb,
  '千劫万磨身不损，道心坚定方成圣。'),
('横刀断岳玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '横刀断岳')),
  '["skill_jade","blade","damage"]'::jsonb,
  '一刀劈出可断山岳之势，刀法之中正大道的体现。'),
('剑心通明玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '剑心通明')),
  '["skill_jade","sword","damage","defense_buff"]'::jsonb,
  '剑心透彻则万法不惑，攻守兼备的中阶剑法。'),
('开山斧玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '开山斧')),
  '["skill_jade","axe","damage"]'::jsonb,
  '以破竹之势劈山开石的斧法，力大者尤爱。'),
('穿云枪玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '穿云枪')),
  '["skill_jade","spear","damage"]'::jsonb,
  '枪尖破云而出，迅猛无匹的枪法。'),
('伏魔棍玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '伏魔棍')),
  '["skill_jade","staff","damage"]'::jsonb,
  '降妖伏魔的基础棍法，简单实用。'),
('穿杨箭玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '穿杨箭')),
  '["skill_jade","bow","damage"]'::jsonb,
  '百步穿杨的精准箭术，弓手入门必学。'),
('灵蛇鞭玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '灵蛇鞭')),
  '["skill_jade","whip","damage","slow"]'::jsonb,
  '如灵蛇吐信的鞭法，可减缓敌速。'),
('方天画戟玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '方天画戟')),
  '["skill_jade","halberd","damage"]'::jsonb,
  '方天画戟的基础用法，威风凛凛。'),
('震地锤玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '震地锤')),
  '["skill_jade","hammer","damage","stun"]'::jsonb,
  '一锤震地的蛮横锤法，运气好能砸晕对手。'),
('影刺玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '影刺')),
  '["skill_jade","dagger","damage"]'::jsonb,
  '从暗影中发起的致命一击，刺客入门。'),
('清风拂柳玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '清风拂柳')),
  '["skill_jade","fan","heal"]'::jsonb,
  '以扇引生机，疗愈自身或友方的风雅之术。'),
('拂尘净心玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '拂尘净心')),
  '["skill_jade","flywhisk","heal","speed_buff"]'::jsonb,
  '拂尘轻扫，净心凝神，增加速度。'),
('金刚圈玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '金刚圈')),
  '["skill_jade","ring","damage","stun"]'::jsonb,
  '乾坤圈之术的筑基版，专敲脑门。'),
('伏魔钟玉简', 'SKILL_JADE',
  jsonb_build_object('skill_id', (SELECT id FROM xt_skill WHERE name = '伏魔钟')),
  '["skill_jade","bell","damage","silence"]'::jsonb,
  '钟声震荡，魔音贯耳，可封人法决。');
