INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        1,
        'travel_ambush_beast',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        1,
        'travel_broken_cart',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_RANDOM_ITEM',
                    'template_ids',
                    jsonb_build_array(
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '灵芝'
                        ),
                        (
                            SELECT
                                id
                            FROM
                                xt_item_template
                            WHERE
                                name = '玄铁矿石'
                        )
                    ),
                    'chance',
                    0.3
                )
            )
        )
    ),
    (
        'TRAVEL',
        1,
        'travel_friendly_merchant',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        2,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        2,
        'travel_injured_cultivator',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 50}]}'
    ),
    (
        'TRAVEL',
        3,
        'travel_fallen_star',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '玄铁矿石'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        4,
        'travel_spring_of_spirit',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 100}]}'
    ),
    (
        'TRAVEL',
        4,
        'travel_broken_cart',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        5,
        'travel_rainstorm',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        6,
        'travel_friendly_merchant',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        6,
        'travel_wandering_elder',
        'NUMERIC',
        5,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":20}',
        '{}'
    ),
    (
        'TRAVEL',
        7,
        'travel_treasure_map',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        8,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        10,
        'travel_bandit_roadblock',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        11,
        'travel_friendly_merchant',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        11,
        'travel_wandering_elder',
        'NUMERIC',
        6,
        FALSE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":45}',
        '{}'
    ),
    (
        'TRAVEL',
        17,
        'travel_strange_fog',
        'NUMERIC',
        20,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        24,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "HEAL_FLAT", "amount": 500}]}'
    ),
    (
        'TRAVEL',
        27,
        'travel_fallen_star',
        'NUMERIC',
        12,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        30,
        'travel_fallen_star',
        'NUMERIC',
        15,
        FALSE,
        NULL,
        '{}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '天外陨铁'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        35,
        'travel_strange_fog',
        'NUMERIC',
        15,
        FALSE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '魂玉碎片'
            )
        ),
        '{}'
    ),
    (
        'TRAVEL',
        39,
        'travel_fallen_star',
        'NUMERIC',
        8,
        FALSE,
        NULL,
        '{}',
        '{}'
    ),
    (
        'TRAVEL',
        42,
        'travel_wandering_elder',
        'NUMERIC',
        10,
        FALSE,
        NULL,
        '{}',
        '{"effects": [{"type": "ADD_EXP", "amount": 50}]}'
    );

INSERT
    INTO
        xt_activity_event(
            activity_type,
            owner_id,
            code,
            event_type,
            weight,
            is_hidden,
            trigger_type,
            trigger_params,
            params
        )
    VALUES(
        'TRAVEL',
        14,
        'travel_wandering_elder',
        'NUMERIC',
        8,
        TRUE,
        'STAT_THRESHOLD',
        '{"stat":"WIS","min":50}',
        jsonb_build_object(
            'effects',
            jsonb_build_array(
                jsonb_build_object(
                    'type',
                    'ADD_ITEM',
                    'template_id',
                    (
                        SELECT
                            id
                        FROM
                            xt_item_template
                        WHERE
                            name = '大悟道丹'
                    ),
                    'count',
                    1
                )
            )
        )
    ),
    (
        'TRAVEL',
        28,
        'travel_spring_of_spirit',
        'NUMERIC',
        10,
        TRUE,
        'HAS_ITEM',
        jsonb_build_object(
            'item_template_id',
            (
                SELECT
                    id
                FROM
                    xt_item_template
                WHERE
                    name = '九转金莲'
            )
        ),
        '{}'
    ),
    (
        'TRAVEL',
        33,
        'travel_bandit_roadblock',
        'NUMERIC',
        10,
        TRUE,
        'HAS_SKILL',
        jsonb_build_object(
            'skill_id',
            (
                SELECT
                    id
                FROM
                    xt_skill
                WHERE
                    name = '刑天斧法'
            )
        ),
        '{}'
    );
