-- 材料 —— 草药类 (id 47-70)
INSERT INTO xt_item_template (id, name, type, rarity, properties, tags, description, max_stack) VALUES
(47, '灵草', 'MATERIAL', 'COMMON', '{}'::jsonb, '["herb","spirit","common"]'::jsonb, '蕴含灵气的草药，炼药常用材料', 99),
(48, '铜骨草', 'MATERIAL', 'COMMON', '{}'::jsonb, '["herb","common"]'::jsonb, '最常见的低级灵草', 99),
(49, '清心草', 'MATERIAL', 'COMMON', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":1}}', '["herb","common","curative"]'::jsonb, '可清心安神的草药', 99),
(50, '银叶草', 'MATERIAL', 'COMMON', '{}'::jsonb, '["herb","common"]'::jsonb, '叶片呈银白色的低级灵草', 99),
(51, '毒龙草', 'MATERIAL', 'RARE', '{}'::jsonb, '["herb","poison","rare"]'::jsonb, '剧毒草药，用于炼制毒药或高级金创药', 99),
(52, '灵芝', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":2}}', '["herb","spirit","rare"]'::jsonb, '灵气浓郁的仙草，炼制高级丹药必备', 99),
(53, '冰魄花', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":2}}', '["herb","ice","rare","alchemy"]'::jsonb, '只生长在极寒之地的奇花，花瓣如冰晶般剔透', 99),
(54, '噬魂菇', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":0}}', '["herb","poison","rare","dark"]'::jsonb, '生长于阴暗洞窟的诡异蘑菇', 50),
(55, '七叶莲', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":2}}', '["herb","rare","curative"]'::jsonb, '七片叶子各呈一色的珍奇莲花', 50),
(56, '九幽兰', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":0}}', '["herb","dark","rare","poison"]'::jsonb, '只生长于九幽之地的暗色兰花', 30),
(57, '紫金藤', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":2,"con":2,"agi":0,"wis":0}}', '["herb","rare"]'::jsonb, '紫金色的藤蔓，坚韧异常', 50),
(58, '月光菇', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":3}}', '["herb","spirit","rare"]'::jsonb, '只在月光下生长的灵菇', 50),
(59, '朱雀血藤', 'MATERIAL', 'EPIC', '{"base_stat_bonus":{"str":4,"con":0,"agi":0,"wis":0}}', '["herb","fire","epic"]'::jsonb, '据说是朱雀血洒落凡间所生', 30),
(60, '千年人参', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":2,"con":2,"agi":0,"wis":2}}', '["herb","rare","prestige"]'::jsonb, '极为珍贵的炼药材料', 50),
(61, '龙血草', 'MATERIAL', 'EPIC', '{"base_stat_bonus":{"str":5,"con":3,"agi":0,"wis":0}}', '["herb","dragon","epic","forge_potion"]'::jsonb, '传说以真龙之血浇灌而生', 50),
(62, '天心花', 'MATERIAL', 'EPIC', '{"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":6}}', '["herb","spirit","epic","wisdom"]'::jsonb, '只在月圆之夜绽放', 30),
(63, '天山雪莲', 'MATERIAL', 'EPIC', '{"base_stat_bonus":{"str":0,"con":4,"agi":0,"wis":3}}', '["herb","ice","epic","curative"]'::jsonb, '百年一绽的天山雪莲', 20),
(64, '长生果', 'MATERIAL', 'EPIC', '{"base_stat_bonus":{"str":3,"con":5,"agi":0,"wis":3}}', '["herb","epic","longevity"]'::jsonb, '传说中的长生果，极为稀有', 10),
(65, '万年玄参', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":3,"con":5,"agi":0,"wis":3}}', '["herb","rare","prestige","longevity"]'::jsonb, '在雪山深处生长万年的玄参', 20),
(66, '赤火莲', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":3,"con":0,"agi":0,"wis":2}}', '["herb","fire","rare","harvest"]'::jsonb, '火属性仙草，炼制火系丹药的主材', 50),
(67, '玄冰莲', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":2}}', '["herb","ice","rare","harvest"]'::jsonb, '冰属性仙草，炼制冰系丹药的主材', 50),
(68, '幽冥花', 'MATERIAL', 'RARE', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":0}}', '["herb","dark","rare","harvest","poison"]'::jsonb, '暗属性奇花，深黑花瓣如夜', 20),
(69, '金芝', 'MATERIAL', 'LEGENDARY', '{"base_stat_bonus":{"str":5,"con":5,"agi":0,"wis":5}}', '["herb","gold","legendary","harvest"]'::jsonb, '传说中的金芝，极为珍贵的仙草', 5),
(70, '菩提叶', 'MATERIAL', 'LEGENDARY', '{"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":8}}', '["herb","wisdom","legendary"]'::jsonb, '菩提树之叶，蕴含开悟之力', 1);
