-- 种子
INSERT INTO xt_item_template (name, type, properties, tags, description, max_stack) VALUES
('灵草种子', 'SEED', '{"grow_time":24,"yields":["灵草"],"survive_rate":90}', '["seed","spirit","common"]'::jsonb, '最基础的灵草种子，成活率高，新手入门首选', 999),
('铜骨草种子', 'SEED', '{"grow_time":18,"yields":["铜骨草"],"survive_rate":90}', '["seed","common"]'::jsonb, '长势极快的灵草种子，产量稳定' , 999),
('清心草种子', 'SEED', '{"grow_time":24,"yields":["清心草"],"survive_rate":85}', '["seed","common"]'::jsonb, '清心静气的好东西——种一片，心静自然凉', 999),
('银叶草种子', 'SEED', '{"grow_time":18,"yields":["银叶草"],"survive_rate":90}', '["seed","common"]'::jsonb, '叶片泛银光，种在田里煞是好看——观赏价值大于实用', 999),
('赤火莲子', 'SEED', '{"grow_time":48,"yields":["赤火莲"],"survive_rate":80}', '["seed","fire","rare"]'::jsonb, '火属性种子，成熟需48小时——心急吃不了热豆腐，也等不来赤火莲', 999),
('玄冰莲子', 'SEED', '{"grow_time":48,"yields":["玄冰莲"],"survive_rate":80}', '["seed","ice","rare"]'::jsonb, '冰属性种子，需种在阴凉处——夏天种它最合适', 999),
('冰魄花种子', 'SEED', '{"grow_time":36,"yields":["冰魄花"],"survive_rate":80}', '["seed","ice","rare"]'::jsonb, '三十六小时开花，比大多功法突破还快', 999),
('幽冥花种子', 'SEED', '{"grow_time":60,"yields":["幽冥花"],"survive_rate":65}', '["seed","dark","rare"]'::jsonb, '喜阴畏光的奇花，种下去就别老去看了——它不喜欢', 999),
('紫金藤种子', 'SEED', '{"grow_time":36,"yields":["紫金藤"],"survive_rate":75}', '["seed","rare"]'::jsonb, '紫金色的藤蔓，种的时候间距要大——这玩意儿会抢地盘', 999),
('九幽兰种子', 'SEED', '{"grow_time":72,"yields":["九幽兰"],"survive_rate":55}', '["seed","dark","rare"]'::jsonb, '生于九幽之地的兰花，对环境极为挑剔——一株难求', 999),
('万年玄参种子', 'SEED', '{"grow_time":96,"yields":["万年玄参"],"survive_rate":50}', '["seed","prestige","rare"]'::jsonb, '种下之后要等四天——筑基期修士都该结丹了', 999),
('朱雀血藤种子', 'SEED', '{"grow_time":72,"yields":["朱雀血藤"],"survive_rate":55}', '["seed","fire","epic"]'::jsonb, '据说是朱雀血所化，种它需要耐心——以及防火意识', 999),
('天山雪莲种子', 'SEED', '{"grow_time":96,"yields":["天山雪莲"],"survive_rate":45}', '["seed","ice","epic"]'::jsonb, '雪莲娇贵，成活不足五成——但种出来了就值回票价', 999),
('龙血草种子', 'SEED', '{"grow_time":48,"yields":["龙血草"],"survive_rate":70}', '["seed","dragon","epic"]'::jsonb, '号称龙血滋养——但谁也不知道是不是真有龙', 999),
('天心花种子', 'SEED', '{"grow_time":60,"yields":["天心花"],"survive_rate":60}', '["seed","spirit","epic"]'::jsonb, '需在月圆之夜播种——如果你分不清哪天是月圆，多试几次', 999),
('长生果种子', 'SEED', '{"grow_time":120,"yields":["长生果"],"survive_rate":30}', '["seed","epic","longevity"]'::jsonb, '种下去的时候炼气期，收获的时候该准备结丹了', 999),
('金芝种子', 'SEED', '{"grow_time":72,"yields":["金芝"],"survive_rate":50}', '["seed","gold","legendary"]'::jsonb, '传说中的金色灵芝——种出来是本事，种不出来是常态', 999),
('菩提叶种子', 'SEED', '{"grow_time":120,"yields":["菩提叶"],"survive_rate":25}', '["seed","wisdom","legendary"]'::jsonb, '菩提树之种，成活率仅四分之一——适合有耐心的大毅力者', 999),
('聚灵草种子', 'SEED', '{"grow_time":12,"yields":["灵草"],"survive_rate":95}', '["seed","spirit","common"]'::jsonb, '十二小时速收——修仙界的豆芽菜，新手致富第一步', 999),
('凝血草种子', 'SEED', '{"grow_time":18,"yields":["凝血草"],"survive_rate":90}', '["seed","common"]'::jsonb, '种田入门首选，稳如老狗，建议新手大面积播种', 999),
('龙涎草种子', 'SEED', '{"grow_time":48,"yields":["龙涎草"],"survive_rate":65}', '["seed","dragon","rare"]'::jsonb, '据说有真龙涎过的地方才会长——真假未知', 999),
('还魂花种子', 'SEED', '{"grow_time":96,"yields":["还魂花"],"survive_rate":30}', '["seed","curative","epic"]'::jsonb, '冥界之花，传说能起死回生——但建议别指望它', 999),
('七星海棠种子', 'SEED', '{"grow_time":84,"yields":["七星海棠"],"survive_rate":35}', '["seed","star","epic"]'::jsonb, '需三天半成熟，花瓣对应北斗七星——种的时候别数错了', 999),
('飞仙草种子', 'SEED', '{"grow_time":168,"yields":["飞仙草"],"survive_rate":10}', '["seed","legendary","immortal"]'::jsonb, '七天成熟，成活率一成——种植界的地狱难度', 999),
('七叶莲种子', 'SEED', '{"grow_time":48,"yields":["七叶莲"],"survive_rate":70}', '["seed","curative","rare"]'::jsonb, '七叶各色，观赏与药用兼备——种一株赏心悦目', 999),
('月光菇孢子', 'SEED', '{"grow_time":36,"yields":["月光菇"],"survive_rate":75}', '["seed","spirit","rare"]'::jsonb, '只在月光下生长的菌菇——阴天不会耽误它，别担心', 999),
('星灵花种子', 'SEED', '{"grow_time":72,"yields":["天心花"],"survive_rate":40}', '["seed","star","epic"]'::jsonb, '需在夜晚播种，星光照耀下长势更佳——夜猫子专属', 999);
