-- 装备 —— 武器
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('木剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":1,"base_stat_bonus":{"str":1,"con":0,"agi":0,"wis":0},"base_attack":2,"base_defense":0,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '削木而成的简陋短剑', 1),
       ('竹剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":3,"base_stat_bonus":{"str":2,"con":0,"agi":1,"wis":0},"base_attack":3,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '青竹削制而成的轻剑，虽简陋却颇为锋利', 1),
       ('青铜剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":5,"base_stat_bonus":{"str":3,"con":0,"agi":1,"wis":0},"base_attack":5,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '普通青铜铸剑', 1),
       ('铁剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":10,"base_stat_bonus":{"str":3,"con":0,"agi":1,"wis":0},"base_attack":5,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '一把普通的铁剑', 1),
       ('精铁剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":15,"base_stat_bonus":{"str":5,"con":0,"agi":2,"wis":0},"base_attack":10,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '精铁百锻而成的利剑', 1),
       ('灵剑', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":20,"base_stat_bonus":{"str":8,"con":0,"agi":3,"wis":2},"base_attack":15,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '蕴含灵气的宝剑', 1),
       ('玄铁剑', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":25,"base_stat_bonus":{"str":10,"con":2,"agi":2,"wis":0},"base_attack":20,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '以千年玄铁铸成，挥动间寒光凛冽', 1),
       ('破军刀', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":30,"base_stat_bonus":{"str":13,"con":5,"agi":-2,"wis":0},"base_attack":28,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '沉重霸道的战刀，一刀可破千军', 1),
       ('青云剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":35,"base_stat_bonus":{"str":15,"con":0,"agi":8,"wis":5},"base_attack":35,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '青云峰镇山之宝，剑气如虹直冲云霄', 1),
       ('碎星刀', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":38,"base_stat_bonus":{"str":17,"con":4,"agi":4,"wis":0},"base_attack":40,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '刀芒可碎星辰', 1),
       ('碧水剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":40,"base_stat_bonus":{"str":12,"con":0,"agi":10,"wis":6},"base_attack":38,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '剑身碧绿如水，轻灵异常', 1),
       ('紫电剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":42,"base_stat_bonus":{"str":18,"con":0,"agi":5,"wis":3},"base_attack":42,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '剑身紫电缠绕，出鞘时有雷鸣之音', 1),
       ('天罡剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":48,"base_stat_bonus":{"str":20,"con":3,"agi":4,"wis":3},"base_attack":48,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '引天罡之力铸就的神剑，剑气浩瀚如星河', 1),
       ('仙剑', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":50,"base_stat_bonus":{"str":20,"con":0,"agi":8,"wis":5},"base_attack":50,"base_defense":0,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '仙人遗留的神剑', 1),
       ('诛仙剑', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":55,"base_stat_bonus":{"str":25,"con":0,"agi":5,"wis":6},"base_attack":58,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '上古至宝，传说能斩灭仙人元神', 1);

-- 装备 —— 护甲
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('竹甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":1,"base_stat_bonus":{"str":0,"con":1,"agi":0,"wis":0},"base_attack":0,"base_defense":2,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '竹片编成的简陋护甲', 1),
       ('布甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":3,"base_stat_bonus":{"str":0,"con":2,"agi":1,"wis":0},"base_attack":0,"base_defense":3,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '灵布缝制的轻便护甲，不碍行动', 1),
       ('铜甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":5,"base_stat_bonus":{"str":0,"con":3,"agi":-1,"wis":0},"base_attack":0,"base_defense":7,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '铜制的轻甲', 1),
       ('皮甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":10,"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":0},"base_attack":0,"base_defense":5,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '简单的皮革护甲', 1),
       ('铁甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":15,"base_stat_bonus":{"str":0,"con":6,"agi":-1,"wis":0},"base_attack":0,"base_defense":12,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '沉重的铁制铠甲', 1),
       ('锁子甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":20,"base_stat_bonus":{"str":0,"con":8,"agi":2,"wis":0},"base_attack":0,"base_defense":15,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '千环相扣的锁子甲，防御灵活兼备', 1),
       ('寒铁甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":25,"base_stat_bonus":{"str":0,"con":10,"agi":0,"wis":0},"base_attack":0,"base_defense":20,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '寒铁铸就的铠甲，触之冰凉如雪', 1),
       ('灵甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":30,"base_stat_bonus":{"str":0,"con":12,"agi":2,"wis":3},"base_attack":0,"base_defense":30,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '蕴含灵力的护甲', 1),
       ('墨鳞甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":35,"base_stat_bonus":{"str":0,"con":15,"agi":0,"wis":3},"base_attack":0,"base_defense":35,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '以墨蛟鳞片缝制，水火不侵', 1),
       ('龙鳞甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":45,"base_stat_bonus":{"str":2,"con":18,"agi":3,"wis":5},"base_attack":0,"base_defense":50,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '以真龙之鳞缝制，寻常法宝难伤分毫', 1),
       ('炎帝甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":50,"base_stat_bonus":{"str":3,"con":20,"agi":2,"wis":5},"base_attack":0,"base_defense":55,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '炎帝遗留的神甲，烈火环绕', 1),
       ('金缕衣', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":55,"base_stat_bonus":{"str":0,"con":15,"agi":10,"wis":8},"base_attack":0,"base_defense":45,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '万缕金丝织就，轻若鸿毛坚如金石', 1);

-- 装备 —— 饰品
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('铜环', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ACCESSORY","equip_level":5,"base_stat_bonus":{"str":0,"con":0,"agi":1,"wis":1},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '朴素的铜指环', 1),
       ('玉佩', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":10,"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":35,"RARE":20,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '温润的玉佩，可凝神静气', 1),
       ('银坠', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":15,"base_stat_bonus":{"str":0,"con":1,"agi":2,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":35,"RARE":20,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '银制吊坠', 1),
       ('定颜珠', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":25,"base_stat_bonus":{"str":0,"con":5,"agi":2,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '传说佩戴者容颜不老', 1),
       ('灵戒', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":20,"base_stat_bonus":{"str":2,"con":2,"agi":2,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '蕴含灵力的戒指', 1),
       ('避水珠', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":30,"base_stat_bonus":{"str":0,"con":5,"agi":5,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '佩戴者可入水不溺，江河倒流亦不能近身', 1),
       ('火凤环', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":35,"base_stat_bonus":{"str":5,"con":3,"agi":3,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '火凤内丹所化，佩戴者周身火焰不侵', 1),
       ('乾坤戒', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":40,"base_stat_bonus":{"str":5,"con":5,"agi":5,"wis":8},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '内含一方小世界，可纳百川', 1),
       ('龙凤佩', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":45,"base_stat_bonus":{"str":8,"con":8,"agi":5,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '龙凤呈祥，佩戴者气运加身', 1);
