-- 进化石
INSERT INTO xt_item_template (name, type, properties, tags, description, max_stack) VALUES
('初级进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","applicable_tiers":["T1","T2"],"success_rate_bonus":0}'::jsonb,
 '["evolution","common"]'::jsonb,
 '蕴含微薄灵气的进化石，仅供T1→T2突破使用——聊胜于无', 999),
('进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","applicable_tiers":["T1","T2"],"success_rate_bonus":0.1}'::jsonb,
 '["evolution","rare"]'::jsonb,
 '最通用的进化石，T1→T2成功率+10%。每个修士背包里都有几块', 999),
('中级进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","applicable_tiers":["T2","T3"],"success_rate_bonus":0}'::jsonb,
 '["evolution","rare"]'::jsonb,
 '蕴含的灵气比初级高了一个量级——当然价格也是', 999),
('高级进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","applicable_tiers":["T3","T4"],"success_rate_bonus":0.2}'::jsonb,
 '["evolution","epic"]'::jsonb,
 'T3→T4突破成功率+20%——剩下的八成看命', 999),
('超级进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","applicable_tiers":["T2","T3","T4"],"success_rate_bonus":0.1}'::jsonb,
 '["evolution","epic"]'::jsonb,
 '跨阶突破专用，聊以慰藉那微薄的突破概率', 999),
('传说进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"tier","guaranteed":true}'::jsonb,
 '["evolution","legendary"]'::jsonb,
 '天地初开时便存在的灵石——必定成功，童叟无欺', 999),
('纯净进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"purify"}'::jsonb,
 '["evolution","rare"]'::jsonb,
 '可重置灵兽品质，从头来过——修炼界的后悔药', 999),
('属性进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"attribute"}'::jsonb,
 '["evolution","epic"]'::jsonb,
 '为灵兽附加新属性——五行缺啥补啥', 999),
('变异催化石', 'EVOLUTION_STONE',
 '{"evolution_type":"mutation","mutation_rate_bonus":0.3}'::jsonb,
 '["evolution","epic"]'::jsonb,
 '变异概率+30%——赌一赌，灵兽变神兽', 999),
('混沌进化石', 'EVOLUTION_STONE',
 '{"evolution_type":"chaos","guaranteed":true,"mutation_rate_bonus":0.5}'::jsonb,
 '["evolution","legendary"]'::jsonb,
 '混沌初开时的原石，必成且变异率+50%——可遇不可求', 999);
