-- 材料 —— 珍礼类 (id 128-145)
INSERT INTO xt_item_template (id, name, type, rarity, properties, tags, description, max_stack) VALUES
(128, '月光石', 'MATERIAL', 'COMMON', '{}'::jsonb, '["gem","moon","common"]'::jsonb, '在月光下散发幽光的石头', 10),
(129, '灵酒', 'MATERIAL', 'COMMON', '{}'::jsonb, '["wine","spirit","common"]'::jsonb, '灵气浓郁的酒水，适合送给喜欢饮酒的NPC', 20),
(130, '长寿面', 'MATERIAL', 'COMMON', '{}'::jsonb, '["food","common","warm"]'::jsonb, '一碗简单的长寿面', 20),
(131, '星尘水晶', 'MATERIAL', 'RARE', '{}'::jsonb, '["gem","shiny","magic","rare"]'::jsonb, '璀璨的星尘水晶', 5),
(132, '暖玉', 'MATERIAL', 'RARE', '{}'::jsonb, '["gem","rare","warm"]'::jsonb, '握在手中温暖如春的宝玉', 5),
(133, '镇魂铃', 'MATERIAL', 'RARE', '{}'::jsonb, '["bell","spirit","rare"]'::jsonb, '轻轻摇动可安魂定魄', 3),
(134, '定风珠', 'MATERIAL', 'RARE', '{}'::jsonb, '["gem","wind","rare"]'::jsonb, '佩戴者不为狂风所动', 3),
(135, '琉璃心', 'MATERIAL', 'RARE', '{}'::jsonb, '["gem","rare","art"]'::jsonb, '琉璃制成的精致心形', 5),
(136, '玲珑棋局', 'MATERIAL', 'RARE', '{}'::jsonb, '["game","wisdom","rare"]'::jsonb, '上古大能留下的残局', 3),
(137, '鲛人泪', 'MATERIAL', 'EPIC', '{}'::jsonb, '["gem","sea","epic"]'::jsonb, '深海鲛人的眼泪化作的珍珠', 3),
(138, '金乌羽', 'MATERIAL', 'EPIC', '{}'::jsonb, '["feather","sun","epic"]'::jsonb, '金乌的羽毛，触之温热', 3),
(139, '玄黄尺', 'MATERIAL', 'EPIC', '{}'::jsonb, '["ruler","ancient","epic"]'::jsonb, '玄黄二气铸造的古老法器', 1),
(140, '古玉', 'MATERIAL', 'EPIC', '{}'::jsonb, '["gem","ancient","prestige","epic"]'::jsonb, '传承千年的古玉', 3),
(141, '紫金葫芦', 'MATERIAL', 'EPIC', '{}'::jsonb, '["vessel","magic","prestige","epic"]'::jsonb, '紫金炼制的葫芦，可收万物', 1),
(142, '万兽丹', 'MATERIAL', 'EPIC', '{}'::jsonb, '["beast","epic","utility"]'::jsonb, '可吸引万兽的奇丹', 5),
(143, '龙鳞', 'MATERIAL', 'LEGENDARY', '{}'::jsonb, '["scale","dragon","prestige","legendary"]'::jsonb, '传说中的龙鳞，极为珍贵的礼物', 1),
(144, '河图洛书', 'MATERIAL', 'LEGENDARY', '{}'::jsonb, '["book","ancient","prestige","legendary","unique"]'::jsonb, '河出图洛出书，记载天地至理的太古奇书', 1),
(145, '先天八卦', 'MATERIAL', 'LEGENDARY', '{}'::jsonb, '["diagram","ancient","legendary"]'::jsonb, '伏羲先天八卦图', 1);
