-- 装备 —— 武器
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('木剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":1,"base_stat_bonus":{"str":1,"con":0,"agi":0,"wis":0},"base_attack":2,"base_defense":0,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '百年灵木所削——其实是昨天刚砍的', 1),
       ('匕首', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":2,"base_stat_bonus":{"str":0,"con":0,"agi":1,"wis":0},"base_attack":2,"base_defense":0,"drop_weight":{"BROKEN":65,"COMMON":25,"RARE":8,"EPIC":2,"LEGENDARY":0}}',
        '[]'::jsonb, '短小精悍——据说用好了能越级反杀，说这话的人已经不在了', 1),
       ('竹剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":3,"base_stat_bonus":{"str":2,"con":0,"agi":1,"wis":0},"base_attack":3,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '青竹削制，轻便顺手——就是不太耐用', 1),
       ('木刀', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":4,"base_stat_bonus":{"str":1,"con":1,"agi":0,"wis":0},"base_attack":3,"base_defense":0,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '木刀也是刀，被它砍了一样疼', 1),
       ('青铜剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":5,"base_stat_bonus":{"str":3,"con":0,"agi":1,"wis":0},"base_attack":5,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '入门级制式兵器，各大仙门标配，人手一把', 1),
       ('练功棍', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":6,"base_stat_bonus":{"str":1,"con":1,"agi":0,"wis":0},"base_attack":4,"base_defense":0,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '师门演武场同款兵器——打不坏人也打不坏桩', 1),
       ('龙泉剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":8,"base_stat_bonus":{"str":2,"con":0,"agi":1,"wis":1},"base_attack":4,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '剑身刻有龙纹，据传是欧冶子所铸——欧冶子本人并未证实', 1),
       ('铁剑', 'EQUIPMENT', 'BROKEN',
        '{"slot":"WEAPON","equip_level":10,"base_stat_bonus":{"str":3,"con":0,"agi":1,"wis":0},"base_attack":5,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '普通铁匠打造，没什么特别的——但胜在便宜', 1),
       ('红缨枪', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":12,"base_stat_bonus":{"str":3,"con":1,"agi":0,"wis":0},"base_attack":8,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '红缨如火，枪出如龙——至于龙不龙，全看人', 1),
       ('柳叶刀', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":14,"base_stat_bonus":{"str":2,"con":0,"agi":2,"wis":0},"base_attack":9,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '刀身似柳叶，轻快凌厉，适合快刀手', 1),
       ('精铁剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":15,"base_stat_bonus":{"str":5,"con":0,"agi":2,"wis":0},"base_attack":10,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '百锻精铁打造，比铁剑强了一截——也贵了一截', 1),
       ('陨铁短刃', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":16,"base_stat_bonus":{"str":3,"con":0,"agi":2,"wis":0},"base_attack":11,"base_defense":0,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '从天外陨铁上敲下来的一块边角料打的——捡漏捡来的', 1),
       ('分水刺', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":18,"base_stat_bonus":{"str":1,"con":0,"agi":4,"wis":0},"base_attack":13,"base_defense":0,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '水下搏杀的奇门兵器——虽然你大部分时候不在水下', 1),
       ('紫檀棍', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":19,"base_stat_bonus":{"str":3,"con":3,"agi":0,"wis":0},"base_attack":12,"base_defense":0,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '紫檀灵木所制，坚硬沉重还带点木香——闻着挺安心', 1),
       ('赤霄剑', 'EQUIPMENT', 'COMMON',
        '{"slot":"WEAPON","equip_level":20,"base_stat_bonus":{"str":4,"con":0,"agi":1,"wis":1},"base_attack":12,"base_defense":0,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '据说和汉高祖斩白蛇那把是同一款——但高祖那把好像不长这样', 1),
       ('灵剑', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":20,"base_stat_bonus":{"str":8,"con":0,"agi":3,"wis":2},"base_attack":15,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '剑身刻有聚灵阵，能自行吸纳灵气——不用自己充能', 1),
       ('九环刀', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":22,"base_stat_bonus":{"str":5,"con":2,"agi":0,"wis":0},"base_attack":18,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '九环叮当作响，气势逼人——就是没法偷袭，十里外都听得见', 1),
       ('青锋剑', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":24,"base_stat_bonus":{"str":3,"con":0,"agi":2,"wis":1},"base_attack":17,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '三尺青锋，削铁如泥——当然只削得动一般的铁', 1),
       ('玄铁剑', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":25,"base_stat_bonus":{"str":10,"con":2,"agi":2,"wis":0},"base_attack":20,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '玄铁铸剑，寒光凛冽。就是有点沉——就当锻炼臂力了', 1),
       ('龙骨鞭', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":26,"base_stat_bonus":{"str":1,"con":0,"agi":5,"wis":1},"base_attack":20,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '据说是龙筋所制——至于是哪条龙捐的筋，无人知晓', 1),
       ('银月戟', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":27,"base_stat_bonus":{"str":6,"con":3,"agi":0,"wis":0},"base_attack":22,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '戟杆镔铁打造，月下一点寒芒——帅是真的帅', 1),
       ('寒冰剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":28,"base_stat_bonus":{"str":4,"con":0,"agi":3,"wis":2},"base_attack":25,"base_defense":0,"drop_weight":{"BROKEN":35,"COMMON":30,"RARE":22,"EPIC":10,"LEGENDARY":3}}',
        '[]'::jsonb, '剑身三尺冰封，出鞘寒气逼人——建议戴手套，别问为什么', 1),
       ('碎岳锤', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":30,"base_stat_bonus":{"str":8,"con":4,"agi":-2,"wis":0},"base_attack":28,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '一锤碎山岳——锤子是这么说的，山岳没同意', 1),
       ('破军刀', 'EQUIPMENT', 'RARE',
        '{"slot":"WEAPON","equip_level":30,"base_stat_bonus":{"str":13,"con":5,"agi":-2,"wis":0},"base_attack":28,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '铸此刀者曾被刀修同门嘲笑"莽夫"，于是他造了一把更莽的', 1),
       ('冰魄弓', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":32,"base_stat_bonus":{"str":0,"con":0,"agi":6,"wis":2},"base_attack":30,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '冰魄雕琢之弓，箭出如流星寒星——但箭得另外买', 1),
       ('方天画戟', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":34,"base_stat_bonus":{"str":8,"con":3,"agi":1,"wis":0},"base_attack":33,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '某位三国猛将的同款兵器——至于是哪位，记不清了', 1),
       ('青云剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":35,"base_stat_bonus":{"str":15,"con":0,"agi":8,"wis":5},"base_attack":35,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '青云山镇山之宝——当然，每座山都有镇山之宝', 1),
       ('打神鞭', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":36,"base_stat_bonus":{"str":4,"con":0,"agi":6,"wis":3},"base_attack":32,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '封神时期遗宝，专打人不打神——说明书上这么写的', 1),
       ('碧海潮生箫', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":37,"base_stat_bonus":{"str":0,"con":0,"agi":4,"wis":6},"base_attack":31,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '以音波伤敌，威力不俗——前提是你得吹响它', 1),
       ('碎星刀', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":38,"base_stat_bonus":{"str":17,"con":4,"agi":4,"wis":0},"base_attack":40,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '据说全力挥刀可碎星辰——但没人真的见过', 1),
       ('飞星剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":38,"base_stat_bonus":{"str":6,"con":0,"agi":5,"wis":3},"base_attack":36,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '剑出如流星赶月，转瞬即逝——确实快，但你也得看得清', 1),
       ('碧水剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":40,"base_stat_bonus":{"str":12,"con":0,"agi":10,"wis":6},"base_attack":38,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '剑身碧绿如水，轻灵异常——据说是铸剑师失手把颜料倒进去了', 1),
       ('霜月刀', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":40,"base_stat_bonus":{"str":8,"con":2,"agi":4,"wis":0},"base_attack":38,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '刀身如霜，刀芒如月——适合月圆之夜拿出来用', 1),
       ('紫电剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":42,"base_stat_bonus":{"str":18,"con":0,"agi":5,"wis":3},"base_attack":42,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '出鞘有雷鸣之音，剑身紫电缠绕——电池需自备', 1),
       ('离火剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":42,"base_stat_bonus":{"str":10,"con":0,"agi":3,"wis":3},"base_attack":42,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '剑身离火缠绕，百邪不侵——就是握把有点烫手', 1),
       ('风雷扇', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":44,"base_stat_bonus":{"str":2,"con":0,"agi":6,"wis":6},"base_attack":44,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '一扇风雷动，再扇日月明——连扇三下就手抽筋了', 1),
       ('万象拂尘', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":46,"base_stat_bonus":{"str":2,"con":0,"agi":4,"wis":8},"base_attack":43,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '拂尘一扫，万象皆空——平时用来扫扫灰也挺好使', 1),
       ('天罡剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":48,"base_stat_bonus":{"str":20,"con":3,"agi":4,"wis":3},"base_attack":48,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '引天罡星力铸就，剑如其名——就是催债的也追不上', 1),
       ('斩龙剑', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":48,"base_stat_bonus":{"str":10,"con":3,"agi":2,"wis":2},"base_attack":46,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '名字很霸气，但铸成之后还没真的斩过龙', 1),
       ('乾坤圈', 'EQUIPMENT', 'EPIC',
        '{"slot":"WEAPON","equip_level":50,"base_stat_bonus":{"str":5,"con":5,"agi":5,"wis":3},"base_attack":48,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '乾天坤地，圈锁乾坤——丢出去之后记得收回来', 1),
       ('仙剑', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":50,"base_stat_bonus":{"str":20,"con":0,"agi":8,"wis":5},"base_attack":50,"base_defense":0,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '仙人遗留之剑——至于是哪路仙人，他说忘了', 1),
       ('盘古斧', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":52,"base_stat_bonus":{"str":12,"con":5,"agi":-3,"wis":0},"base_attack":55,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '说是上古遗物——但说不定是哪位铁匠随手打的', 1),
       ('轩辕剑', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":54,"base_stat_bonus":{"str":8,"con":0,"agi":5,"wis":5},"base_attack":56,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '此剑有些来历——但剑主人不太爱提往事', 1),
       ('诛仙剑', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":55,"base_stat_bonus":{"str":25,"con":0,"agi":5,"wis":6},"base_attack":58,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '诛仙剑阵起，道友请留步——先问过这口剑答不答应', 1),
       ('混沌钟', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"WEAPON","equip_level":55,"base_stat_bonus":{"str":5,"con":8,"agi":2,"wis":5},"base_attack":60,"base_defense":0,"drop_weight":{"BROKEN":10,"COMMON":20,"RARE":25,"EPIC":25,"LEGENDARY":20}}',
        '[]'::jsonb, '钟声浑厚，能震慑心神——别在自己洞府里敲', 1);

-- 装备 —— 护甲
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('竹甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":1,"base_stat_bonus":{"str":0,"con":1,"agi":0,"wis":0},"base_attack":0,"base_defense":2,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '竹片编成，聊胜于无——至少比不穿强', 1),
       ('藤甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":2,"base_stat_bonus":{"str":0,"con":1,"agi":0,"wis":0},"base_attack":0,"base_defense":2,"drop_weight":{"BROKEN":65,"COMMON":25,"RARE":8,"EPIC":2,"LEGENDARY":0}}',
        '[]'::jsonb, '灵藤编织，轻便透气——唯一的缺点是怕火', 1),
       ('布甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":3,"base_stat_bonus":{"str":0,"con":2,"agi":1,"wis":0},"base_attack":0,"base_defense":3,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '灵布缝制，轻便透气——修仙界的速干衣', 1),
       ('麻衣', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":4,"base_stat_bonus":{"str":0,"con":1,"agi":0,"wis":1},"base_attack":0,"base_defense":3,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '粗麻所制，朴素实用——穿上颇有苦修者的气质', 1),
       ('铜甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":5,"base_stat_bonus":{"str":0,"con":3,"agi":-1,"wis":0},"base_attack":0,"base_defense":7,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '铜制轻甲，防御尚可——就是穿久了身上一股铜臭味', 1),
       ('软猬甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":6,"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":0},"base_attack":0,"base_defense":5,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '浑身尖刺，拥抱前请先打个招呼', 1),
       ('玄布甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":8,"base_stat_bonus":{"str":0,"con":2,"agi":1,"wis":0},"base_attack":0,"base_defense":6,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '玄铁丝混织，看起来薄薄一层，实际上比铁甲还扛揍', 1),
       ('皮甲', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ARMOR","equip_level":10,"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":0},"base_attack":0,"base_defense":5,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '兽皮鞣制而成，原始而实用——走在路上很有野性美', 1),
       ('皮裘', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":12,"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":0},"base_attack":0,"base_defense":8,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '妖兽皮毛所制，暖和又抗揍——冬天穿尤其合适', 1),
       ('银鳞甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":14,"base_stat_bonus":{"str":0,"con":4,"agi":0,"wis":0},"base_attack":0,"base_defense":10,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '银光闪闪的鳞甲，穿上去很拉风——就是容易被盯上', 1),
       ('铁甲', 'EQUIPMENT', 'COMMON',
        '{"slot":"ARMOR","equip_level":15,"base_stat_bonus":{"str":0,"con":6,"agi":-1,"wis":0},"base_attack":0,"base_defense":12,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '铁制板甲，结实耐造——就是穿上了就别想跑太快', 1),
       ('灵绸袍', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":16,"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":2},"base_attack":0,"base_defense":12,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '灵绸织就的道袍，仙风道骨气质+10——防不防打是其次', 1),
       ('虎皮披风', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":18,"base_stat_bonus":{"str":0,"con":4,"agi":0,"wis":0},"base_attack":0,"base_defense":13,"drop_weight":{"BROKEN":45,"COMMON":30,"RARE":18,"EPIC":5,"LEGENDARY":2}}',
        '[]'::jsonb, '吊睛白额大虫的皮做的——至于那大虫后来怎么样了，别问', 1),
       ('锁子甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":20,"base_stat_bonus":{"str":0,"con":8,"agi":2,"wis":0},"base_attack":0,"base_defense":15,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '千环相扣，兼顾防御与灵活——织了整整三年', 1),
       ('金丝甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":22,"base_stat_bonus":{"str":0,"con":5,"agi":1,"wis":0},"base_attack":0,"base_defense":16,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '金丝软甲，内穿外用皆可——就是金丝容易被勾出来', 1),
       ('玄铁甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":24,"base_stat_bonus":{"str":0,"con":8,"agi":-1,"wis":0},"base_attack":0,"base_defense":18,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '玄铁重甲，刀枪不入——穿上了就别想自己脱', 1),
       ('寒铁甲', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":25,"base_stat_bonus":{"str":0,"con":10,"agi":0,"wis":0},"base_attack":0,"base_defense":20,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '寒铁铸甲，触手冰凉——夏天穿很爽，冬天穿要命', 1),
       ('夜行衣', 'EQUIPMENT', 'RARE',
        '{"slot":"ARMOR","equip_level":26,"base_stat_bonus":{"str":0,"con":4,"agi":2,"wis":1},"base_attack":0,"base_defense":16,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '漆黑如夜，穿行无影——白天穿的话有点显眼', 1),
       ('天蚕甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":28,"base_stat_bonus":{"str":0,"con":5,"agi":2,"wis":2},"base_attack":0,"base_defense":22,"drop_weight":{"BROKEN":35,"COMMON":30,"RARE":22,"EPIC":10,"LEGENDARY":3}}',
        '[]'::jsonb, '天蚕丝织就，薄如蝉翼——穿上去像没穿一样，防御也像……开玩笑的', 1),
       ('灵甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":30,"base_stat_bonus":{"str":0,"con":12,"agi":2,"wis":3},"base_attack":0,"base_defense":30,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '灵力灌注的护甲，会自动修复轻微损伤——懒人福音', 1),
       ('八卦仙衣', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":32,"base_stat_bonus":{"str":0,"con":8,"agi":2,"wis":3},"base_attack":0,"base_defense":27,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '八卦绣于衣上，行走间自带仙风道骨BGM', 1),
       ('百花战裙', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":34,"base_stat_bonus":{"str":0,"con":6,"agi":3,"wis":2},"base_attack":0,"base_defense":25,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '百朵灵花绣于战裙之上——好看是真的好看，打架也是真的能打', 1),
       ('墨鳞甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":35,"base_stat_bonus":{"str":0,"con":15,"agi":0,"wis":3},"base_attack":0,"base_defense":35,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '墨蛟鳞片缝制，水火不侵——就是味儿有点大', 1),
       ('墨蛟皮甲', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":36,"base_stat_bonus":{"str":0,"con":10,"agi":2,"wis":1},"base_attack":0,"base_defense":30,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '墨蛟皮鞣制，水火不侵还透气——味道比鳞甲那件好多了', 1),
       ('紫绶仙衣', 'EQUIPMENT', 'EPIC',
        '{"slot":"ARMOR","equip_level":38,"base_stat_bonus":{"str":0,"con":10,"agi":2,"wis":3},"base_attack":0,"base_defense":32,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '紫气东来，仙绶飘飘——穿上它感觉修为都涨了一截', 1),
       ('金蝉衣', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":42,"base_stat_bonus":{"str":0,"con":10,"agi":5,"wis":3},"base_attack":0,"base_defense":38,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '金蝉脱壳，可挡一劫——但没人说得清是哪一劫', 1),
       ('龙鳞甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":45,"base_stat_bonus":{"str":2,"con":18,"agi":3,"wis":5},"base_attack":0,"base_defense":50,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '真龙之鳞缝制而成，刀枪不入——就是真龙不太好找', 1),
       ('玄武甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":48,"base_stat_bonus":{"str":0,"con":15,"agi":0,"wis":3},"base_attack":0,"base_defense":48,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '玄武甲壳淬炼而成，说明书写着"此甲扛得住天劫"——希望是真的', 1),
       ('炎帝甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":50,"base_stat_bonus":{"str":3,"con":20,"agi":2,"wis":5},"base_attack":0,"base_defense":55,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '炎帝遗留神甲，烈火环绕——防火性能极佳', 1),
       ('混元道袍', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":50,"base_stat_bonus":{"str":0,"con":12,"agi":4,"wis":5},"base_attack":0,"base_defense":45,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '混元一气织就的道袍，返璞归真——乍一看就是件普通道袍', 1),
       ('金缕衣', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":55,"base_stat_bonus":{"str":0,"con":15,"agi":10,"wis":8},"base_attack":0,"base_defense":45,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '万缕金丝织就，轻若鸿毛坚如金石——就是容易勾丝', 1),
       ('不灭金身甲', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ARMOR","equip_level":55,"base_stat_bonus":{"str":2,"con":20,"agi":0,"wis":5},"base_attack":0,"base_defense":58,"drop_weight":{"BROKEN":10,"COMMON":20,"RARE":25,"EPIC":25,"LEGENDARY":20}}',
        '[]'::jsonb, '据说是某位炼体大能晚年所制——穿上去感觉确实不一样', 1);

-- 装备 —— 饰品
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack)
VALUES ('木符', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ACCESSORY","equip_level":3,"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":80,"COMMON":15,"RARE":4,"EPIC":1,"LEGENDARY":0}}',
        '[]'::jsonb, '入门级护身符，据说找大师开过光——但大师可能不认识你', 1),
       ('铜环', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ACCESSORY","equip_level":5,"base_stat_bonus":{"str":0,"con":0,"agi":1,"wis":1},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":55,"COMMON":30,"RARE":12,"EPIC":3,"LEGENDARY":0}}',
        '[]'::jsonb, '一枚朴素的铜指环——大概是某位前辈从地摊上淘的', 1),
       ('玉镯', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":8,"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":2},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '灵玉手镯，送道侣的入门款——不贵且体面，寓意也好', 1),
       ('骨戒', 'EQUIPMENT', 'BROKEN',
        '{"slot":"ACCESSORY","equip_level":10,"base_stat_bonus":{"str":1,"con":0,"agi":0,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":60,"COMMON":25,"RARE":10,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '不知名妖兽指骨打磨而成——戴上颇有原始风情', 1),
       ('玉佩', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":10,"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":35,"RARE":20,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '温润玉佩，可凝神静气——大师开光，灵不灵看缘分', 1),
       ('兽骨项链', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":12,"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":50,"COMMON":30,"RARE":15,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '某只妖兽的颈椎骨串成的项链——挂着挺唬人的', 1),
       ('银坠', 'EQUIPMENT', 'COMMON',
        '{"slot":"ACCESSORY","equip_level":15,"base_stat_bonus":{"str":0,"con":1,"agi":2,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":35,"RARE":20,"EPIC":4,"LEGENDARY":1}}',
        '[]'::jsonb, '银制吊坠，款式经典——送道侣首选', 1),
       ('血玉戒指', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":18,"base_stat_bonus":{"str":2,"con":0,"agi":0,"wis":2},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '据说戴久了会微微发热——也可能是心理作用', 1),
       ('灵戒', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":20,"base_stat_bonus":{"str":2,"con":2,"agi":2,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '灵力充沛的戒指，各项属性都有提升——万金油选手', 1),
       ('玄木簪', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":20,"base_stat_bonus":{"str":0,"con":0,"agi":0,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '万年玄木雕成的发簪——男女皆宜，盘发束发都好使', 1),
       ('聚灵佩', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":22,"base_stat_bonus":{"str":0,"con":2,"agi":0,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '可缓慢汇聚天地灵气——戴着修炼，聊胜于无', 1),
       ('定颜珠', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":25,"base_stat_bonus":{"str":0,"con":5,"agi":2,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '可保容颜不老——但修为该老还是得老，别指望太多', 1),
       ('招财铃', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":26,"base_stat_bonus":{"str":0,"con":0,"agi":3,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":40,"COMMON":30,"RARE":20,"EPIC":8,"LEGENDARY":2}}',
        '[]'::jsonb, '摇铃招财运——据说有奇效，但也可能是巧合', 1),
       ('锁魂链', 'EQUIPMENT', 'RARE',
        '{"slot":"ACCESSORY","equip_level":28,"base_stat_bonus":{"str":2,"con":4,"agi":0,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":35,"COMMON":30,"RARE":22,"EPIC":10,"LEGENDARY":3}}',
        '[]'::jsonb, '此链锁魂，戴上后灵魂出窍也能拉回来——虽然你还没出过窍', 1),
       ('避水珠', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":30,"base_stat_bonus":{"str":0,"con":5,"agi":5,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '入水不溺，江河倒灌亦不能近身——建议先学会游泳以防万一', 1),
       ('镇魂印', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":32,"base_stat_bonus":{"str":0,"con":3,"agi":0,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '一方镇魂法印，可安魂定魄——对隔壁吵闹的道侣也有效', 1),
       ('火凤环', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":35,"base_stat_bonus":{"str":5,"con":3,"agi":3,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '火凤内丹所化，烈火不侵——冬天戴特别暖和', 1),
       ('如意环', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":35,"base_stat_bonus":{"str":3,"con":0,"agi":3,"wis":3},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '心随意转，如意随心——其实就是个做工精巧的镯子', 1),
       ('阴阳镜', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":38,"base_stat_bonus":{"str":0,"con":0,"agi":4,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":25,"COMMON":30,"RARE":25,"EPIC":15,"LEGENDARY":5}}',
        '[]'::jsonb, '阴阳两面，可照妖照人——也能当镜子梳头，一镜多用', 1),
       ('乾坤戒', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":40,"base_stat_bonus":{"str":5,"con":5,"agi":5,"wis":8},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '内含一方小世界，可纳百川——但装不进去另一枚乾坤戒', 1),
       ('缚灵索', 'EQUIPMENT', 'EPIC',
        '{"slot":"ACCESSORY","equip_level":40,"base_stat_bonus":{"str":3,"con":5,"agi":0,"wis":0},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":30,"COMMON":30,"RARE":25,"EPIC":12,"LEGENDARY":3}}',
        '[]'::jsonb, '缚灵之索，可困住灵体——对活人效果一般', 1),
       ('九天玄女坠', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":42,"base_stat_bonus":{"str":0,"con":5,"agi":0,"wis":8},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":20,"COMMON":30,"RARE":25,"EPIC":20,"LEGENDARY":5}}',
        '[]'::jsonb, '据说是九天玄女同款——高仿，但仿得很用心', 1),
       ('龙凤佩', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":45,"base_stat_bonus":{"str":8,"con":8,"agi":5,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '龙凤呈祥，气运加身——据说是某对仙侣的定情信物', 1),
       ('昆仑镜', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":48,"base_stat_bonus":{"str":0,"con":0,"agi":6,"wis":8},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '昆仑仙境的宝镜——照一照，能看到明天的自己', 1),
       ('太极图', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":50,"base_stat_bonus":{"str":0,"con":5,"agi":0,"wis":10},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":15,"COMMON":25,"RARE":25,"EPIC":25,"LEGENDARY":10}}',
        '[]'::jsonb, '太极生两仪，两仪生四象——挂在脖子上颇有算命先生的范儿', 1),
       ('混沌珠', 'EQUIPMENT', 'LEGENDARY',
        '{"slot":"ACCESSORY","equip_level":55,"base_stat_bonus":{"str":5,"con":5,"agi":5,"wis":5},"base_attack":0,"base_defense":0,"drop_weight":{"BROKEN":10,"COMMON":20,"RARE":25,"EPIC":25,"LEGENDARY":20}}',
        '[]'::jsonb, '混沌灵气凝结而成的宝珠，颇为稀有——拿在手里感觉很踏实', 1);
