-- 丹药 / 消耗品
INSERT INTO xt_item_template (name, type, rarity, properties, tags, description, max_stack) VALUES
('气血散', 'POTION', 'COMMON', '{}'::jsonb, '["healing","potion","common"]'::jsonb, '服用后恢复25点生命值', 16),
('活血散', 'POTION', 'COMMON', '{}'::jsonb, '["healing","potion","common"]'::jsonb, '服用后恢复40点生命值', 16),
('疗伤丹', 'POTION', 'COMMON', '{}'::jsonb, '["healing","potion","combat"]'::jsonb, '服用后恢复50点生命值', 16),
('聚气丹', 'POTION', 'RARE', '{}'::jsonb, '["healing","potion","combat","rare"]'::jsonb, '服用后恢复100点生命值', 16),
('金创药', 'POTION', 'RARE', '{}'::jsonb, '["healing","potion","combat","rare"]'::jsonb, '服用后恢复150点生命值', 16),
('回春丹', 'POTION', 'RARE', '{}'::jsonb, '["healing","potion","regen","rare"]'::jsonb, '服用后每秒恢复5%生命值，持续10秒', 16),
('大还丹', 'POTION', 'RARE', '{}'::jsonb, '["healing","potion","rare","combat"]'::jsonb, '恢复100% HP', 16),
('续命丹', 'POTION', 'RARE', '{}'::jsonb, '["revive","potion","rare"]'::jsonb, '历练战败后自动使用，避免死亡惩罚，限一次', 16),
('清心丹', 'POTION', 'COMMON', '{}'::jsonb, '["curative","potion","common"]'::jsonb, '服用后清除一个负面状态', 16),
('九花玉露', 'POTION', 'RARE', '{}'::jsonb, '["healing","potion","rare"]'::jsonb, '服用后恢复60%生命值与50点体力', 16),
('辟谷丹', 'POTION', 'COMMON', '{}'::jsonb, '["stamina","potion","common"]'::jsonb, '服用后立即恢复50点体力', 16),
('回灵丹', 'POTION', 'RARE', '{}'::jsonb, '["stamina","potion","rare"]'::jsonb, '服用后恢复100点体力', 16),
('敏捷药剂', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","agi","rare"]'::jsonb, '历练增益，持续2小时内，敏捷+50', 16),
('蛮力药剂', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","str","rare"]'::jsonb, '历练增益，持续2小时内，力量+50', 16),
('智慧药剂', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","wis","rare"]'::jsonb, '历练增益，持续2小时内，智慧+50', 16),
('疾风丹', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","agi","rare"]'::jsonb, '历练增益，持续2小时内，敏捷+80', 16),
('铁骨丹', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","con","rare"]'::jsonb, '历练增益，持续2小时内，体质+80', 16),
('凝神丹', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","wis","rare"]'::jsonb, '历练增益，持续2小时内，智慧+80', 16),
('破甲丹', 'POTION', 'EPIC', '{}'::jsonb, '["buff","potion","str","epic"]'::jsonb, '历练增益，持续2小时内，力量+60', 16),
('轻身丹', 'POTION', 'RARE', '{}'::jsonb, '["buff","potion","agi","rare"]'::jsonb, '历练增益，持续2小时内，敏捷+60', 16),
('续骨丹', 'POTION', 'EPIC', '{}'::jsonb, '["buff","potion","con","epic"]'::jsonb, '历练增益，持续2小时内，体质+60', 16),
('通慧丹', 'POTION', 'EPIC', '{}'::jsonb, '["buff","potion","wis","epic"]'::jsonb, '历练增益，持续2小时内，智慧+60', 16),
('金刚丹', 'POTION', 'EPIC', '{}'::jsonb, '["buff","potion","str","con","epic"]'::jsonb, '历练增益，持续2小时内，力量+40 体质+40', 16),
('龟息丹', 'POTION', 'RARE', '{}'::jsonb, '["stamina","potion","rare"]'::jsonb, '服用后体力恢复速度翻倍，持续4小时', 16),
('聚灵丹', 'POTION', 'EPIC', '{}'::jsonb, '["spirit","potion","epic"]'::jsonb, '历练中获得灵石概率翻倍，持续1小时', 16),
('筑基丹', 'POTION', 'RARE', '{}'::jsonb, '["level_up","potion","rare"]'::jsonb, '服用后直升一级，每次突破后仅可使用一次', 16),
('破境丹', 'POTION', 'EPIC', '{}'::jsonb, '["breakthrough","potion","epic"]'::jsonb, '破而后立之丹，突破时使用可提升20%成功率', 16),
('培元丹', 'POTION', 'RARE', '{}'::jsonb, '["permanent","potion","rare"]'::jsonb, '服用后永久增加全属性+1，每人最多服用5次', 16),
('铸魂丹', 'POTION', 'EPIC', '{}'::jsonb, '["breakthrough","potion","epic"]'::jsonb, '突破时使用，失败后保留50%经验值', 16),
('九转金丹', 'POTION', 'LEGENDARY', '{}'::jsonb, '["full_restore","potion","legendary"]'::jsonb, '瞬间恢复全部HP与体力，并清除所有负面状态', 16);
